### ISSUE TITLE
Pixel XL 7.1.2 failed to load example app

### ISSUE THREAD

**Issue by LoSealL** [google-ar/arcore-android-sdk#10]
>FATAL EXCEPTION: main
                                                                                          Process: com.google.ar.core.examples.java.helloar, PID: 27755
                                                                                          java.lang.UnsatisfiedLinkError: No implementation found for int com.google.atap.tango.TangoJNINative.Initialize(android.content.Context) (tried Java_com_google_atap_tango_TangoJNINative_Initialize and Java_com_google_atap_tango_TangoJNINative_Initialize__Landroid_content_Context_2)
                                                                                              at com.google.atap.tango.TangoJNINative.Initialize(Native Method)
                                                                                              at com.google.atap.tangoservice.Tango.<init>(Tango.java:385)
                                                                                              at com.google.ar.core.TangoWrapper.createInstance(TangoWrapper.java:32)
                                                                                              at com.google.ar.core.Session.bindTangoService(Session.java:425)
                                                                                              at com.google.ar.core.Session.resume(Session.java:153)
                                                                                              at com.google.ar.core.examples.java.helloar.HelloArActivity.onResume(HelloArActivity.java:136)
                                                                                              at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1269)
                                                                                              at android.app.Activity.performResume(Activity.java:6786)
                                                                                              at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3407)
                                                                                              at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3470)
                                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2733)
                                                                                              at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
                                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                              at android.os.Looper.loop(Looper.java:154)
                                                                                              at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by LoSealL** [comment]
Why seems it need to load tango libs?

**Comment by cpinan** [comment]
Have you installed arcore apk?

**Comment by LoSealL** [comment]
Oh, I solved this by installing [arcore_preview.apk](https://github.com/google-ar/arcore-android-sdk/releases/download/sdk-preview/arcore-preview.apk)
Thanks for @cpinan's advice!
