### ISSUE TITLE
Can't run app on android emulator.

### ISSUE THREAD

**Issue by georgetas123** [google-ar/arcore-android-sdk#1014]
Hello I have a problem with running the hellosceneform on an android emulator. I followed each step and also followed other steps shown on this issue but none of the seem to work. Does anyone have a clue on how to solve this?

Log : 
2020-03-09 12:20:26.441 8864-8864/? I/.helloscenefor: Not late-enabling -Xcheck:jni (already on)
2020-03-09 12:20:26.450 8864-8864/? I/.helloscenefor: Unquickening 13 vdex files!
2020-03-09 12:20:26.451 8864-8864/? W/.helloscenefor: Unexpected CPU variant for X86 using defaults: x86
2020-03-09 12:20:26.615 8864-8864/com.google.ar.sceneform.samples.hellosceneform I/.helloscenefor: The ClassLoaderContext is a special shared library.
2020-03-09 12:20:26.914 8864-8899/com.google.ar.sceneform.samples.hellosceneform D/libEGL: loaded /vendor/lib/egl/libEGL_emulation.so
2020-03-09 12:20:26.915 8864-8899/com.google.ar.sceneform.samples.hellosceneform D/libEGL: loaded /vendor/lib/egl/libGLESv1_CM_emulation.so
2020-03-09 12:20:26.917 8864-8899/com.google.ar.sceneform.samples.hellosceneform D/libEGL: loaded /vendor/lib/egl/libGLESv2_emulation.so
2020-03-09 12:20:27.009 8864-8864/com.google.ar.sceneform.samples.hellosceneform W/.helloscenefor: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
2020-03-09 12:20:27.010 8864-8864/com.google.ar.sceneform.samples.hellosceneform W/.helloscenefor: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
2020-03-09 12:20:27.040 8864-8864/com.google.ar.sceneform.samples.hellosceneform I/Filament: Filament library loaded.
2020-03-09 12:20:27.043 8864-8864/com.google.ar.sceneform.samples.hellosceneform D/HostConnection: HostConnection::get() New Host Connection established 0xe35c5f10, tid 8864
2020-03-09 12:20:27.044 8864-8864/com.google.ar.sceneform.samples.hellosceneform D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_ignored_handles GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0 
2020-03-09 12:20:27.051 8864-8864/com.google.ar.sceneform.samples.hellosceneform D/EGL_emulation: eglCreateContext: 0xc3450ea0: maj 3 min 0 rcv 3
2020-03-09 12:20:27.078 8864-8864/com.google.ar.sceneform.samples.hellosceneform D/EGL_emulation: eglMakeCurrent: 0xc3450ea0: ver 3 0 (tinfo 0xe15296d0)
2020-03-09 12:20:27.088 8864-8864/com.google.ar.sceneform.samples.hellosceneform I/Filament: FEngine (32 bits) created at 0xc27d7d00 (threading is enabled)
2020-03-09 12:20:27.091 8864-8901/com.google.ar.sceneform.samples.hellosceneform D/Filament: Using ASurfaceTexture
2020-03-09 12:20:27.091 8864-8901/com.google.ar.sceneform.samples.hellosceneform D/Filament: FEngine resolved backend: OpenGL
2020-03-09 12:20:27.094 8864-8901/com.google.ar.sceneform.samples.hellosceneform D/HostConnection: HostConnection::get() New Host Connection established 0xe366d0a0, tid 8901
2020-03-09 12:20:27.097 8864-8901/com.google.ar.sceneform.samples.hellosceneform D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_ignored_handles GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0 
2020-03-09 12:20:27.119 8864-8901/com.google.ar.sceneform.samples.hellosceneform D/EGL_emulation: eglCreateContext: 0xc34511a0: maj 3 min 0 rcv 3
2020-03-09 12:20:27.122 8864-8901/com.google.ar.sceneform.samples.hellosceneform D/EGL_emulation: eglMakeCurrent: 0xc34511a0: ver 3 0 (tinfo 0xe1529850)
2020-03-09 12:20:27.124 8864-8901/com.google.ar.sceneform.samples.hellosceneform E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008a30
2020-03-09 12:20:27.124 8864-8901/com.google.ar.sceneform.samples.hellosceneform E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008a30
2020-03-09 12:20:27.159 8864-8864/com.google.ar.sceneform.samples.hellosceneform I/SceneView: Optional library com.google.ar.sceneform.animation not present. Sceneform animation disabled
2020-03-09 12:20:27.351 8864-8895/com.google.ar.sceneform.samples.hellosceneform D/HostConnection: HostConnection::get() New Host Connection established 0xd685a370, tid 8895
2020-03-09 12:20:27.351 8864-8895/com.google.ar.sceneform.samples.hellosceneform D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_ignored_handles GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0 
2020-03-09 12:20:27.351 8864-8895/com.google.ar.sceneform.samples.hellosceneform W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
2020-03-09 12:20:27.355 8864-8895/com.google.ar.sceneform.samples.hellosceneform D/EGL_emulation: eglCreateContext: 0xd681a0c0: maj 3 min 0 rcv 3
2020-03-09 12:20:27.382 8864-8895/com.google.ar.sceneform.samples.hellosceneform D/EGL_emulation: eglMakeCurrent: 0xd681a0c0: ver 3 0 (tinfo 0xd680f370)
2020-03-09 12:20:27.420 8864-8895/com.google.ar.sceneform.samples.hellosceneform I/Gralloc4: mapper 4.x is not supported
2020-03-09 12:20:27.421 8864-8895/com.google.ar.sceneform.samples.hellosceneform W/Gralloc3: mapper 3.x is not supported
2020-03-09 12:20:27.422 8864-8895/com.google.ar.sceneform.samples.hellosceneform D/HostConnection: createUnique: call
2020-03-09 12:20:27.423 8864-8895/com.google.ar.sceneform.samples.hellosceneform D/HostConnection: HostConnection::get() New Host Connection established 0xe366f8a0, tid 8895
2020-03-09 12:20:27.423 8864-8895/com.google.ar.sceneform.samples.hellosceneform D/eglCodecCommon: allocate: Ask for block of size 0x100
2020-03-09 12:20:27.423 8864-8895/com.google.ar.sceneform.samples.hellosceneform D/eglCodecCommon: allocate: ioctl allocate returned offset 0x3f8ce9000 size 0x2000
2020-03-09 12:20:27.426 8864-8895/com.google.ar.sceneform.samples.hellosceneform D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_ignored_handles GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0 
2020-03-09 12:20:27.431 8864-8895/com.google.ar.sceneform.samples.hellosceneform D/EGL_emulation: eglMakeCurrent: 0xd681a0c0: ver 3 0 (tinfo 0xd680f370)
2020-03-09 12:20:29.953 8864-8864/com.google.ar.sceneform.samples.hellosceneform I/ARCore-ArCoreApk: Starting setup activity
2020-03-09 12:20:30.338 8864-8864/com.google.ar.sceneform.samples.hellosceneform I/ARCore-ArCoreApk: Starting setup activity
2020-03-09 12:20:30.823 8864-8864/com.google.ar.sceneform.samples.hellosceneform I/ARCore-ArCoreApk: Starting setup activity
2020-03-09 12:20:31.210 8864-8864/com.google.ar.sceneform.samples.hellosceneform I/third_party/arcore/ar/core/android/sdk/session_create.cc: Entering ArSession_createWithFeatures
2020-03-09 12:20:31.210 8864-8864/com.google.ar.sceneform.samples.hellosceneform I/third_party/arcore/ar/core/android/sdk/session_create.cc: ARCore Version: SDK build name: 1.15
2020-03-09 12:20:31.212 8864-8864/com.google.ar.sceneform.samples.hellosceneform I/third_party/arcore/ar/core/android/sdk/session_create.cc: ARCore Version: APK version code: 200121043
2020-03-09 12:20:31.253 8864-8864/com.google.ar.sceneform.samples.hellosceneform I/third_party/arcore/ar/core/android/sdk/session_create.cc: Dynamite load ok.
2020-03-09 12:20:31.253 8864-8864/com.google.ar.sceneform.samples.hellosceneform I/third_party/arcore/java/com/google/vr/dynamite/client/native/dynamite_client.cc: Attempting to load native library arcore_c from package com.google.ar.core
2020-03-09 12:20:31.256 8864-8864/com.google.ar.sceneform.samples.hellosceneform E/DynamiteClient: Failed to load native library [packageName=com.google.ar.core,libraryName=arcore_c] from remote package:
      
    java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.google.ar.core-pXvNrKTi0BEIQZbexaR8Pw==/lib/arm/libarcore_c.so" is for EM_ARM (40) instead of EM_386 (3)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1661)
        at com.google.vr.dynamite.NativeLibraryLoader.a(PG:32)
        at com.google.vr.dynamite.NativeLibraryLoader.initializeAndLoadNativeLibrary(PG:18)
        at fib.a(PG:5)
        at acg.onTransact(PG:13)
        at android.os.Binder.transact(Binder.java:1010)
        at com.google.a.a.b.transactAndReadException(BaseProxy.java:10)
        at com.google.vr.dynamite.client.b.initializeAndLoadNativeLibrary(INativeLibraryLoader.java:5)
        at com.google.vr.dynamite.client.DynamiteClient.loadNativeRemoteLibrary(DynamiteClient.java:26)
        at com.google.ar.core.Session.nativeCreateSessionAndWrapperWithFeatures(Native Method)
    	at com.goo
2020-03-09 12:20:31.256 8864-8864/com.google.ar.sceneform.samples.hellosceneform I/third_party/arcore/java/com/google/vr/dynamite/client/native/dynamite_client.cc: Dynamite::LoadNativeRemoteLibrary handle=0
2020-03-09 12:20:31.256 8864-8864/com.google.ar.sceneform.samples.hellosceneform E/third_party/arcore/ar/core/android/sdk/session_create.cc: Dynamite failed to load remote library
2020-03-09 12:20:31.256 8864-8864/com.google.ar.sceneform.samples.hellosceneform E/third_party/arcore/ar/core/android/sdk/session_create.cc: LoadSymbolsDynamite returning AR_ERROR_FATAL.
2020-03-09 12:20:31.256 8864-8864/com.google.ar.sceneform.samples.hellosceneform E/third_party/arcore/ar/core/android/sdk/session_create.cc: LoadSymbols returning status.
2020-03-09 12:20:31.269 8864-8864/com.google.ar.sceneform.samples.hellosceneform E/StandardArFragment: Error: Failed to create AR session
    com.google.ar.core.exceptions.UnavailableException
        at com.google.ar.sceneform.ux.BaseArFragment.initializeSession(BaseArFragment.java:391)
        at com.google.ar.sceneform.ux.BaseArFragment.onResume(BaseArFragment.java:338)
        at android.support.v4.app.Fragment.performResume(Fragment.java:2498)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1501)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
        at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:3241)
        at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:223)
        at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:538)
    	at android.support.v4.app.FragmentActivity.onPostResume(Fragm
2020-03-09 12:20:31.356 8864-8895/com.google.ar.sceneform.samples.hellosceneform D/EGL_emulation: eglMakeCurrent: 0xd681a0c0: ver 3 0 (tinfo 0xd680f370)
2020-03-09 12:20:31.401 8864-8895/com.google.ar.sceneform.samples.hellosceneform D/EGL_emulation: eglMakeCurrent: 0xd681a0c0: ver 3 0 (tinfo 0xd680f370)

**Comment by maltezc** [comment]
i just got a similar error. did you figure out how to fix it?

**Comment by devbridie** [comment]
In case anybody finds this in search results:

1. Ensure that your emulator is x86 (Google APIs) e.g. Pixel 3 API 29 x86 Google APIs.
2. Ensure that the ARCore apk you're using in the emulator is the emulator version e.g. (`Google_Play_Services_for_AR_1.22.0_x86_for_emulator.apk`)

If this is still an issue for you, please open a new issue so we can take a closer look. Closing this one due to age.
