### ISSUE TITLE
This device does not support AR 

### ISSUE THREAD

**Issue by varunsurpurkar** [google-ar/arcore-android-sdk#1082]
Android SDK Version - 

Android Studio 4.0

Virtual Device Configuration - 

Name : Pixel 3 API 30
Target : Android 10 + 
CPU : x86

Sample Application : Computer Vision - ARCore sample 

Error on the virtual device -> This device does not support AR .

Error Logs : 

8:02 AM	Emulator: emulator: ERROR: VkCommonOperations.cpp:496: Failed to create Vulkan instance.

8:02 AM	Emulator: emulator: ERROR: VkCommonOperations.cpp:496: Failed to create Vulkan instance.

E/DynamiteClient: Failed to load native library [packageName=com.google.ar.core,libraryName=arcore_c] from remote package:
      
    java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/~~QhF6-MY8xfEzD-xCoLtBqw==/com.google.ar.core-6AzfBJIQFxGmToHPqIIiPw==/lib/arm/libarcore_c.so" is for EM_ARM (40) instead of EM_386 (3)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
   I/third_party/arcore/java/com/google/vr/dynamite/client/native/dynamite_client.cc: Dynamite::LoadNativeRemoteLibrary handle=0
E/third_party/arcore/ar/core/android/sdk/session_create.cc: Dynamite failed to load remote library

W/System.err: com.google.ar.core.exceptions.FatalException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at com.google.ar.core.Session.throwExceptionFromArStatus(Session.java:100)
        at com.google.ar.core.Session.nativeCreateSessionAndWrapperWithFeatures(Native Method)
        at com.google.ar.core.Session.<init>(Session.java:11)
        at com.google.ar.core.Session.<init>(Session.java:4)
        at com.google.ar.core.examples.java.computervision.ComputerVisionActivity.onResume(ComputerVisionActivity.java:190)

**Comment by dvdhfnr** [comment]
Which OS are you using?

**Comment by devbridie** [comment]
In case somebody comes across this in search results:

Make sure you've installed a `*_for_emulator.apk` ARCore build from [ARCore Releases](https://github.com/google-ar/arcore-android-sdk/releases) in your emulator.
