### ISSUE TITLE
How to use ARCore and Camera2 at the same time ? (CAMERA_DISCONNECTED)

### ISSUE THREAD

**Issue by agGitHub** [google-ar/arcore-android-sdk#1146]
### SPECIFIC ISSUE ENCOUNTERED

I am trying to use ARCore and Camera2 at the same time.

My problem is that I get the following error:

```
2020-10-15 13:56:33.244 2559-2559/com.google.ar.core.examples.java.helloar E/CameraCaptureSession: Session 0: Exception while unconfiguring outputs: 
    android.hardware.camera2.CameraAccessException: CAMERA_DISCONNECTED (2): checkPidStatus:2193: The camera device has been disconnected
        at android.hardware.camera2.CameraManager.throwAsPublicException(CameraManager.java:1149)
        at android.hardware.camera2.impl.ICameraDeviceUserWrapper.waitUntilIdle(ICameraDeviceUserWrapper.java:181)
        at android.hardware.camera2.impl.CameraDeviceImpl.waitUntilIdle(CameraDeviceImpl.java:1174)
        at android.hardware.camera2.impl.CameraDeviceImpl.configureStreamsChecked(CameraDeviceImpl.java:443)
        at android.hardware.camera2.impl.CameraCaptureSessionImpl$IdleDrainListener.onDrained(CameraCaptureSessionImpl.java:951)
        at android.hardware.camera2.utils.TaskDrainer.lambda$postDrained$0$TaskDrainer(TaskDrainer.java:207)
        at android.hardware.camera2.utils.-$$Lambda$TaskDrainer$Jb53sDskEXp_qIjiikQeCRx0wJs.run(Unknown Source:2)
```

I saw the page here:
https://developers.google.com/ar/develop/java/camera-sharing

but, if I understand well, it explains how to use Camera2 and ARCore akternatively but not at the same time. It required to switch off ARCore while Camera2 is used.

So how to use ARCore and Camera2 at the same time ? 

Thanks !

### VERSIONS USED
- Android Studio: 4.0
- ARCore SDK for Android: 1.18
- Device manufacturer, model, and O/S: Samsung S20+

**Comment by devbridie** [comment]
I'll have to inquire to be sure, but I would be surprised if you could use ARCore at the same time as camera2 on the same device.

**Comment by agGitHub** [comment]
> I'll have to inquire to be sure, but I would be surprised if you could use ARCore at the same time as camera2 on the same device.

Yes, please check this very important point. If not possible, how can you use the ToF sensor depth map at the same time as ARCore ? As far as I know, the Depth API doesn't use the ToF sensor data for now, and that is a big problem.

Thanks for your help.

**Comment by devbridie** [comment]
Could you help me understand the use case? If you're interested in ToF information, is using a configuration filtered by [`DepthSensorUsage.REQUIRE_AND_USE`](https://developers.google.com/ar/reference/java/com/google/ar/core/CameraConfig.DepthSensorUsage?hl=en#public-static-final-cameraconfig.depthsensorusage-require_and_use) not working as expected?

**Comment by devbridie** [comment]
> Thanks. How do you define this configuration ? May you give more detailed code ?

Check out the [Camera configs](https://developers.google.com/ar/develop/java/camera-configs) page on the ARCore documentation for some sample code-- if it's not clear, please help me understand where it can be improved :)

> Once this configuration chosen, will Image frame.acquireDepthImage() return a depthImage obtained by the ToF sensor ? Will it have the same resolution as the ToF sensor ?

My understanding is that this is device dependent.

**Comment by agGitHub** [comment]
Thanks. There is an error in the doc. It is not:
CameraConfig[] cameraConfigList = session.getSupportedCameraConfigs(filter);
session.setCameraConfig(cameraConfigList[0]);

but:
List<CameraConfig> cameraConfigList = session.getSupportedCameraConfigs(filter);
session.setCameraConfig(cameraConfigList.get(0));

I will test this and tell you if it works as I expect.

Thanks.

**Comment by agGitHub** [comment]
So, I use on my Samsung S20+ the following code:

     CameraConfigFilter filter = new CameraConfigFilter(session);
        filter.setDepthSensorUsage(EnumSet.of(CameraConfig.DepthSensorUsage.REQUIRE_AND_USE));
        List<CameraConfig> cameraConfigList = session.getSupportedCameraConfigs(filter); // Returns a list with 3 items
        session.setCameraConfig(cameraConfigList.get(0)); 


cameraConfigList contains 3 CameraConfigs (instead of 6 when I don't use any filter on the configs). I tested my app with the 3 CameraConfigs and it seems that none of them allows getting an accuracy better than before (seems that the ToF sensor is not used). Additionally, when I do frame.acquireDepthImage() with these 3 configs, I get a depth image with a size 360x640 (like when I apply no filter on the configs) ; this resolution doesn't correspond to the resolution of the S20+ ToF sensor resolution which is 480x640 => these filtered configs really do not seem to correspond to the ToF sensor. 

By the way, note that I can't use the hello_ar_java project (that I slightly modified) with filtered configs in a dark room (without light) ; I get a NotYetAvailableException on frame.acquireDepthImage(). So it really seems that the ToF sensor is not used as I should be able to get a depthMap in a dark room when the ToF sensor is used (I manage to do it with Camera2)

May you tell me how I can get the depthMap from the ToF Sensor ? Or a solution to use Camera2 at the same time as ARCore ? (or this bug should be fixed)

Thanks a lot !

PS: May you also tell me to what corresponds the 3 configs obtained when I set the DepthSensorUsage.REQUIRE_AND_USE filter ? I see that if I apply an additional filter TargetFps.TARGET_FPS_60, I get 0 config. If I apply an additional filter TargetFps.TARGET_FPS_30, I remain with 3 configs. Why 3 configs ? What is the difference between these configs ? How to know which one I should use ? Thanks.

**Comment by iliuxaar** [comment]
@agGitHub, Do you have any results with creating your android app for receiving point cloud from depth camera?
Thank you

**Comment by agGitHub** [comment]
@iliuxaar No, I didn't manage to get proper results with the ToF camera. So I just used the Depth API that is enough for my needs.

**Comment by iliuxaar** [comment]
> @iliuxaar No, I didn't manage to get proper results with the ToF camera. So I just used the Depth API that is enough for my needs.

@agGitHub , is it possible for you to write me in my email?

**Comment by iliuxaar** [comment]
@agGitHub , as I understand you have the same goal with me. I'm also need to work with Depth API like you. Can you please help me? Write me please in my public email. I will be very grateful for you.

**Comment by iliuxaar** [comment]
@agGitHub , I reread long post about Depth API and camera 2 api. I need in converting depth data and coloured data in world space(point cloud). Is it possible for you to share code with me. I don't really understand how can I receive x,y,z world coordinations without camera2 api lens intrinsics. Thank you
