### ISSUE TITLE
ARCore 1.22.0 Native Error AR_ERROR_MISSING_GL_CONTEXT

### ISSUE THREAD

**Issue by rramprasad** [google-ar/arcore-android-sdk#1181]
I am using ARCore SDK 1.22.0 and Sceneform SDK 1.15.0 for my app with Augmented images and Surface detection. Recently I am getting following crash on Pixel 4 XL device. Before this kind of issue not occured.

################ ARCore Native Error ##################
    BUILD_CHANGELIST:344925174
    BUILD_BASELINE_CHANGELIST:342918918
    ################### Stack Trace Begin ################
    ARCoreError: third_party/arcore/ar/core/session.cc:1591	https://cs.corp.google.com/piper///depot/google3/third_party/arcore/ar/core/session.cc?g=0&l=1591
    ARCoreError: third_party/arcore/ar/core/c_api/session_lite_c_api.cc:75	https://cs.corp.google.com/piper///depot/google3/third_party/arcore/ar/core/c_api/session_lite_c_api.cc?g=0&l=75
    ################### Stack Trace End #################
    
    ################### Undecorated Trace Begin  #################
    FAILED_PRECONDITION: 
    ARCoreError: third_party/arcore/ar/core/session.cc:1591
     at third_party/arcore/ar/core/session.cc:1591 [type.googleapis.com/util.ErrorSpacePayload='ArStatusErrorSpace::AR_ERROR_MISSING_GL_CONTEXT']
    ################### Undecorated Trace End  #################
2021-01-05 13:04:04.703 17764-17764/com.rramprasad.arapp D/AndroidRuntime: Shutting down VM
2021-01-05 13:04:04.703 17764-17764/com.rramprasad.arapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.rramprasad.arapp, PID: 17764
    com.google.ar.core.exceptions.MissingGlContextException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at com.google.ar.core.Session.throwExceptionFromArStatus(Session.java:16)
        at com.google.ar.core.Session.nativeUpdate(Native Method)
        at com.google.ar.core.Session.update(Session.java:2)
        at com.google.ar.sceneform.ArSceneView.onBeginFrame(SourceFile:102)
        at com.google.ar.sceneform.SceneView.doFrameNoRepost(SourceFile:90)
        at com.google.ar.sceneform.SceneView.doFrame(SourceFile:86)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:965)
        at android.view.Choreographer.doCallbacks(Choreographer.java:791)
        at android.view.Choreographer.doFrame(Choreographer.java:722)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by devbridie** [comment]
`AR_ERROR_MISSING_GL_CONTEXT` occurs when `Session.update` is called on a thread that isn't the GL thread. In this situation, [`eglGetCurrentContext()`](https://developer.android.com/reference/javax/microedition/khronos/egl/EGL10#eglGetCurrentContext()) returns `null`.

**Comment by developernaman** [comment]
What is the solution for this error
