### ISSUE TITLE
" java.lang.UnsatisfiedLinkError: (...) couldn't find "libarcore_sdk_jni.so" " From App Installed from APK

### ISSUE THREAD

**Issue by Jackaroo05** [google-ar/arcore-android-sdk#1182]
### SPECIFIC ISSUE ENCOUNTERED
Error from Logcat when Launched:

1-01-07 12:08:28.052 24211-24211/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.epaga.smoothtrack, PID: 24211
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.epaga.smoothtrack-q8PjryNZl0FFsYy_y0HHxw==/base.apk"],nativeLibraryDirectories=[/data/app/com.epaga.smoothtrack-q8PjryNZl0FFsYy_y0HHxw==/lib/arm64, /system/lib64, /system/product/lib64]]] couldn't find "libarcore_sdk_jni.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at com.google.ar.core.Session.<init>(Session.java:6)
        at com.epaga.smoothtrack.SmoothTrackActivity.onResume(SmoothTrackActivity.java:417)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1475)
        at android.app.Activity.performResume(Activity.java:7954)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4410)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4452)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2183)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:241)
        at android.app.ActivityThread.main(ActivityThread.java:7617)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)

### VERSIONS USED
- Android Studio: 4.1.1
- ARCore SDK for Android: N/A
- Device manufacturer, model, and O/S:
1. Acer Chromebook Spin 11 CP311-1HN-C2DV - ChromeOS with Linux
2. Motorola z4 XT1980-4 - Android 10
- Google Play Services for AR (ARCore):  1.22.203220503
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`: google/coral/coral_cheets:9/R87-13505.73.0/7017315:user/release-keys

### STEPS TO REPRODUCE THE ISSUE
 1. Install App on mobile device and launch
 2. Allow permissions and read "(App) has stopped"
 3. Launch app and read "(App) keeps stopping"

### WORKAROUNDS (IF ANY)
None

### ADDITIONAL COMMENTS
All other AR Apps work fine except for this one. I believe that apps installed from APKs do not work with AR Services, but I may be mistaken.

**Comment by devbridie** [comment]
Apps installed from APKs should work fine with AR Services. Since other applications seem to be working, I would suggest contacting the developer of the application in this case; there isn't a fix I can suggest in your scenario.

**Comment by Jackaroo05** [comment]
Yeah they should now that I look at it... I already have contacted the dev, but for everyone else it is working even on the same phone i have

**Comment by Jackaroo05** [comment]
Also after I clear the storage of the app and I launch it, it comes up with the camera permission (which it needs) and when i press allow it crashes and it wont launch until i clear storage and relaunch it- putting me into an infinite loop. Is that something of interest to look at?

**Comment by devbridie** [comment]
The problem is probably related to the packaging or distribution of the application; I don't think there are any steps you can take without contacting the developer. You can direct them here if they aren't sure how to continue.
