### ISSUE TITLE
Unable to obtain device profile from the content provider: NOT_FOUND: Device is not supported.

### ISSUE THREAD

**Issue by minmax9493** [google-ar/arcore-android-sdk#1195]
### SPECIFIC ISSUE ENCOUNTERED
 Hi ARCore SDK developers,

   I have faced "Device is not supported" issue on Huawei P20 Pro. 

```
2021-02-15 10:14:47.475 15204-15204/xxx.xxx E/native: session_create_implementation_shared.cc:2051 Unable to obtain device profile from the content provider: NOT_FOUND: Device is not supported.
2021-02-15 10:14:47.475 15204-15204/xxx.xxx E/native: session_create_implementation_shared.cc:2395 Failed to create calibration config and device profile.
2021-02-15 10:14:47.476 15204-15204/xxx.xxx E/native: error_policy_util.cc:261 
    ################ ARCore Native Error ##################
    BUILD_CHANGELIST:331869482
    BUILD_BASELINE_CHANGELIST:331085015
    ################### Stack Trace Begin ################
    ARCoreError: third_party/arcore/ar/core/android/implementation/session_create_implementation_shared.cc:2055	https://cs.corp.google.com/piper///depot/google3/third_party/arcore/ar/core/android/implementation/session_create_implementation_shared.cc?g=0&l=2055
    ARCoreError: third_party/arcore/ar/core/android/implementation/session_create_implementation.cc:293	https://cs.corp.google.com/piper///depot/google3/third_party/arcore/ar/core/android/implementation/session_create_implementation.cc?g=0&l=293
    ARCoreError: third_party/arcore/ar/core/android/implementation/session_create_implementation.cc:377	https://cs.corp.google.com/piper///depot/google3/third_party/arcore/ar/core/android/implementation/session_create_implementation.cc?g=0&l=377
    ################### Stack Trace End #################
2021-02-15 10:14:47.488 15204-15204/xxx.xxx E/AndroidRuntime: FATAL EXCEPTION: main
    Process: xxx.xxx, PID: 15204
    com.google.ar.core.exceptions.UnavailableDeviceNotCompatibleException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at com.google.ar.core.Session.throwExceptionFromArStatus(Session.java:105)
        at com.google.ar.core.Session.nativeCreateSessionAndWrapperWithFeatures(Native Method)
        at com.google.ar.core.Session.<init>(Session.java:11)
        at com.google.ar.core.Session.<init>(Session.java:4)
        at xxx.xxx.ui.screens.capturing.Fragment.initializeSession(Fragment.kt:336)
        at xxx.xxx.ui.screens.capturing.Fragment.access$initializeSession(Fragment.kt:57)
        at xxx.xxx.ui.screens.capturing.TrackingFragment$trackingCameraStateObserver$1$1.invokeSuspend(Fragment.kt:296)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:227)
        at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:362)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:396)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:388)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:484)
        at kotlinx.coroutines.android.HandlerContext$scheduleResumeAfterDelay$$inlined$Runnable$1.run(Runnable.kt:19)
        at android.os.Handler.handleCallback(Handler.java:809)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7377)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)


```

  I'll provide below my function to check if the ARCore is supported:

```private fun checkArCore(block: () -> Unit) {
        try {
            val availability = ArCoreApk.getInstance().checkAvailability(this)
            if (availability.isTransient) {
                // re-query at 5Hz while we check compatibility.
                Handler().postDelayed({ checkArCore(block) }, 200)
            }
            if (availability.isSupported) {
                if (availability != ArCoreApk.Availability.SUPPORTED_INSTALLED) {
                    ArCoreApk.getInstance().requestInstall(this, mUserRequestedInstall)
                } else {
                    block()
                }
            } else { // unsupported or unknown
                Toast.makeText(this, "Error with AR Core: unsupported or unknown", Toast.LENGTH_SHORT).show()
            }
        } catch (e: UnavailableUserDeclinedInstallationException) {
            Toast.makeText(this, "Error with AR Core: $e", Toast.LENGTH_SHORT).show()
        }
    }```

### VERSIONS USED
- Android Studio: 4.1.2
- ARCore SDK for Android: 1.20.0 and 1.22.0
- Device manufacturer, model, and O/S: Huawei
- Google Play Services for AR (ARCore):  1.22.203220523
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`: 


### STEPS TO REPRODUCE THE ISSUE
 1. After checking the availability of ARCore, initialize a Session, and app crashes with the above issue****

**Comment by devbridie** [comment]
Hi, please provide the following information so I can get more clarity on this:

- Device manufacturer, model, and O/S:
- Output of `adb shell getprop ro.build.fingerprint`:
