### ISSUE TITLE
java.lang.UnsatisfiedLinkError: No implementation found for int com.google.atap.tango.TangoJNINative.Initialize

### ISSUE THREAD

**Issue by wangkangmao** [google-ar/arcore-android-sdk#12]
When I use the Pixel runtime，The log shows java.lang.UnsatisfiedLinkError: No implementation found for int com.google.atap.tango.TangoJNINative.Initialize

**Comment by mindwing** [comment]
I just meet the same situation.
There is no "*.so" file.

**Comment by kpbird** [comment]
I am having same error in Google Pixel

Here is full error log

I/TangoClientLibLoader: Pure Java path, not loading libtango_client_api.so at all.
E/Tango: Java version of Tango Service not found, falling back to tangoservice_d.
E/zygote64: No implementation found for int com.google.atap.tango.TangoJNINative.Initialize(android.content.Context) (tried Java_c
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.google.ar.core.examples.java.helloar, PID: 18446
                  java.lang.UnsatisfiedLinkError: No implementation found for int com.google.atap.tango.TangoJNINative.Initialize(
                      at com.google.atap.tango.TangoJNINative.Initialize(Native Method)
                      at com.google.atap.tangoservice.Tango.<init>(Tango.java:385)
                      at com.google.ar.core.TangoWrapper.createInstance(TangoWrapper.java:32)
                      at com.google.ar.core.Session.bindTangoService(Session.java:425)
                      at com.google.ar.core.Session.resume(Session.java:153)
                      at com.google.ar.core.examples.java.helloar.HelloArActivity.onResume(HelloArActivity.java:136)
                      at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1354)
                      at android.app.Activity.performResume(Activity.java:7079)
                      at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3620)
                      at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3685)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2898)
                      at android.app.ActivityThread.-wrap11(Unknown Source:0)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                      at android.os.Handler.dispatchMessage(Handler.java:105)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6541)

                                                       at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by cpinan** [comment]
Have you installed arcore.apk?

**Comment by jguomoto** [comment]
Installing arcore_preview.apk should fix this problem. You could find it in the "Prepare Your Device" section: https://developers.google.com/ar/develop/java/getting-started

**Comment by jessyuan24** [comment]
You need to install ARCore Service by arcore-preview.apk

**Comment by MarkBennett** [comment]
I'm pretty new to development using `adb` and didn't realize the the command was installing to my phone. If you know that then obvisouly, this would require connecting the phone but if you don't know what it's doing then you might not have it attached and could miss the error in the `adb` output.

The directions don't indicate you need to connect your phone until the step after the `adb install`, so just indicating you need to plug in your phone earlier should help here.

**Comment by nathanmartz** [comment]
@MarkBennett thank you for the feedback. We will look into updating our devsite to be more clear in this regard.

**Comment by nathanmartz** [comment]
Closing this issue as the original problem has been addressed.

**Comment by MarkBennett** [comment]
Thanks @nathanmartz!
