### ISSUE TITLE
i create session it throws  java.lang.ClassNotFoundException: com.google.android.gms.location.LocationServices

### ISSUE THREAD

**Issue by steven-gao** [google-ar/arcore-android-sdk#1240]
### SPECIFIC ISSUE ENCOUNTERED
hello,
i used sceneform library to show models,i release my memory after exist my activity. Then i reentry my activity,it crashed.
please help me ,Thanks!
log as follows:

`E/ARCore-LocationProvider: Exception during FLP api client construction: com.google.android.gms.location.LocationServices
    java.lang.ClassNotFoundException: com.google.android.gms.location.LocationServices
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
        at com.google.ar.core.services.LocationProvider.loadClass(PG:1)
        at com.google.ar.core.services.LocationProvider.setupFusedLocationProviderApi(PG:1)
        at com.google.ar.core.services.LocationProvider.<init>(PG:7)
        at com.google.ar.core.Session.nativeCreateSessionAndWrapperWithFeatures(Native Method)
        at com.google.ar.core.Session.<init>(Session.java:11)
        at com.google.ar.sceneform.ux.BaseArFragment.createSessionWithFeatures(BaseArFragment.java:424)
        at com.google.ar.sceneform.ux.BaseArFragment.createSession(BaseArFragment.java:409)
        at com.google.ar.sceneform.ux.BaseArFragment.initializeSession(BaseArFragment.java:379)
        at com.google.ar.sceneform.ux.BaseArFragment.onResume(BaseArFragment.java:338)`

### VERSIONS USED
- Android Studio: 4.1.2
- ARCore SDK for Android: 1.22.0
- Device manufacturer, model, and O/S: samsung galaxy S10
- Google Play Services for AR (ARCore):  1.23.210260663
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
Packages:
    versionName=1.23.210260663
Hidden system packages:
    versionName=0
- Output of `adb shell getprop ro.build.fingerprint`: 
samsung/beyond1qltezc/beyond1q:9/PPR1.180610.011/G9730ZCS2ASJU:user/release-keys

### STEPS TO REPRODUCE THE ISSUE
 1.open the activity use ArFragment
 2.close above activity
 3.open the activity again

**Comment by devbridie** [comment]
Please see https://github.com/google-ar/arcore-android-sdk/issues/1186#issuecomment-792828106-- this error most likely isn't related to your crash; it's an error that looks like one, unfortunately. The real source of your crash should be located somewhere below this message!
