### ISSUE TITLE
  java.lang.IllegalArgumentException: Could not find tag for key

### ISSUE THREAD

**Issue by mikelhm** [google-ar/arcore-android-sdk#1261]
java.lang.IllegalArgumentException: Could not find tag for key 'com.oppo.feature.motion.tracking.camera.name')
        at android.hardware.camera2.impl.CameraMetadataNative.nativeGetTagFromKeyLocal(Native Method)
        at android.hardware.camera2.impl.CameraMetadataNative.getBase(CameraMetadataNative.java:555)
        at android.hardware.camera2.impl.CameraMetadataNative.get(CameraMetadataNative.java:441)
        at android.hardware.camera2.impl.CameraMetadataNative.get(CameraMetadataNative.java:410)
        at android.hardware.camera2.CameraCharacteristics.get(CameraCharacteristics.java:239)
        at eny.b(PG:6)
        at eog.a(PG:4)
        at com.google.ar.core.services.CalibrationContentResolver.readDeviceProfile(PG:25)
        at com.google.ar.core.Session.nativeCreateSessionAndWrapperWithFeatures(Native Method)
        at com.google.ar.core.Session.<init>(Session.java:11)
        at com.google.ar.core.Session.<init>(Session.java:4)
        at com.google.ar.core.examples.java.helloar.HelloArActivity.onResume(HelloArActivity.java:260)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1457)
        at android.app.Activity.performResume(Activity.java:8289)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4758)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4806)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:187)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:102)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2310)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:263)
        at android.app.ActivityThread.main(ActivityThread.java:8258)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)

my apk start ar report these stack.
hello_ar  demo   also  has  these  stack?       but the apk is not crashed.

is this a problem??

**Comment by devbridie** [comment]
I don't believe this is a problem; I'll check in with the team && try to get the warning silenced if it's meaningless.

**Comment by mikelhm** [comment]
> I don't believe this is a problem; I'll check in with the team && try to get the warning silenced if it's meaningless.

it is better not a  problem,  wait for your answer.   
Maybe in different phone  it performs different, I 'm not sure.  Hello_ar also reported. 

 Thank you very much.

**Comment by sandyfriend** [comment]
That is device specific, maybe update the Oppo system to see if the error still here.  ARCore had the mechanism of fallback mode if not finding  key 'com.oppo.feature.motion.tracking.camera.name. should not affect the ARCore usage.

**Comment by raheemadamboev** [comment]
How did u fix it guys?
