### ISSUE TITLE
ARCore 1.26.0 - Realme 8 pro Android 11

### ISSUE THREAD

**Issue by ThomasGorisse** [google-ar/arcore-android-sdk#1282]
Hi,

Thanks for the 1.26.0. It seems to work well and after our first tests, it feels like some ImageReader leaks are fixed.

We have a specific crash on Realme phones (others are working great with the same code) here: https://github.com/ThomasGorisse/sceneform-android-sdk/issues/145

```
I/native: I0824 21:59:33.048375    5292 session.cc:3320] Update Frame Delay to 0 frames.
E/libEGL: Invalid file path for libcolorx-loader.so
E/Parcel: Reading a NULL string not supported here.
I/native: I0824 21:59:33.741704    5549 logger.h:28] DataSourceMetrics: kFirstGlCallback: 1.015956458s
E/NativeImageStreamCallback: Failed to get image metadata
    java.util.concurrent.TimeoutException: Waited 60 milliseconds (plus 924062 nanoseconds delay) for fnj@7413b69[status=PENDING, info=[inputFuture=[fne@31679ee[status=PENDING]], remaining delay=[9928 ms]]]
        at fkt.get(PG:50)
        at com.google.ar.infrastructure.nativedatasource.imagesubsystem.NativeImageStreamCallback.a(PG:9)
        at eku.onImageAvailable(PG:16)
        at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:819)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:254)
        at android.os.HandlerThread.run(HandlerThread.java:67)
E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-8
    Process: com.XXX.XXX, PID: 5292
    java.lang.IllegalArgumentException: Unrecognized auto exposure mode: 126
        at eio.d(PG:7)
        at dsj.f(PG:17)
        at dwm.a(PG:14)
        at hpt.i(PG:7)
        at hoo.a(PG:1)
        at hgz.e(PG:3)
        at hkz.run(PG:14)
        at hpx.f(PG:1)
        at hpw.run(PG:7)
E/NativeImageStreamCallback: Failed to get image metadata
    java.util.concurrent.TimeoutException: Waited 60 milliseconds (plus 453073 nanoseconds delay) for fnj@240bb52[status=PENDING, info=[inputFuture=[fne@20eee23[status=PENDING]], remaining delay=[9935 ms]]]
        at fkt.get(PG:50)
        at com.google.ar.infrastructure.nativedatasource.imagesubsystem.NativeImageStreamCallback.a(PG:9)
        at eku.onImageAvailable(PG:16)
        at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:819)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:254)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

Thanks

**Comment by devbridie** [comment]
I'll comment on https://github.com/ThomasGorisse/sceneform-android-sdk/issues/145.

**Comment by devbridie** [comment]
My understanding is that this has been resolved in a configuration push; could you verify that this is the case? Thanks.

**Comment by Ibrahimjo** [comment]
@devbridie  Yes, it has. Thanks.

**Comment by ThomasGorisse** [comment]
Resolved in a configuration push

**Comment by AndroidStudio** [comment]
Hello please reopen this issue i have still this crash on my Samsung Galaxy A50, Android 11

com.google.ar:core:1.28.0
com.google.ar.sceneform.ux:sceneform-ux:1.17.1

E/NativeImageStreamCallback: Failed to get image metadata
    java.util.concurrent.TimeoutException: Waited 60 milliseconds (plus 196115 nanoseconds delay) for fmt@804cd5[status=PENDING, info=[inputFuture=[fmo@fc7ccea[status=PENDING]], remaining delay=[9939 ms]]]
        at fke.get(PG:50)
        at com.google.ar.infrastructure.nativedatasource.imagesubsystem.NativeImageStreamCallback.a(PG:7)
        at eks.onImageAvailable(PG:16)
        at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:812)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by Noltibus** [comment]
We also see this problem on realme 6 Pro, realme 7 Pro, and realme 8 Pro devices in production. Please reopen (or also fix by a configuration push)!
