### ISSUE TITLE
Library arcore_c loaded in the same classloader context as library null

### ISSUE THREAD

**Issue by Pawel-Dybowski-1000realities** [google-ar/arcore-android-sdk#1287]
For some reason the arcore library stopped working in unity on some devices that it worked before, but still works on others.

I have a few devices, and been developing app using arcore for some time. Recently I noticed that my apps, even apks that worked before, stopped working on some devices with error log given below.

For example it still works on Samsung S7 (SM-G930U) but stopped working on Samsung S20 (SM-G980F).
The same app that worked before now outputs this error on the second device:

```
2021-09-16 13:39:54.888 31259-1897/? I/third_party/arcore/ar/core/android/sdk/session_create.cc: Entering ArSession_createWithFeatures
2021-09-16 13:39:54.888 31259-1897/? I/third_party/arcore/ar/core/android/sdk/session_create.cc: ARCore Version: SDK build name: 1.22
2021-09-16 13:39:54.888 31259-1897/? I/third_party/arcore/ar/core/android/sdk/session_create.cc: ARCore Version: APK version code: 212010383
2021-09-16 13:39:54.888 31259-1897/? I/third_party/arcore/ar/core/android/sdk/session_create.cc: Dynamite load ok.
2021-09-16 13:39:54.888 31259-1897/? I/third_party/arcore/java/com/google/vr/dynamite/client/native/dynamite_client.cc: Attempting to load native library arcore_c from package com.google.ar.core
2021-09-16 13:39:54.889 31259-1897/? E/DynamiteClient: Failed to load native library [packageName=com.google.ar.core,libraryName=arcore_c] from remote package:
      
    java.lang.IllegalStateException: Library arcore_c loaded in the same classloader context as library null
        at com.google.vr.dynamite.NativeLibraryLoader.initializeAndLoadNativeLibrary(PG:1)
        at gan.A(PG:6)
        at agy.onTransact(PG:3)
        at android.os.Binder.transact(Binder.java:1079)
        at com.google.a.a.a.b(BaseProxy.java:2)
        at com.google.vr.dynamite.client.b.initializeAndLoadNativeLibrary(INativeLibraryLoader.java:3)
        at com.google.vr.dynamite.client.DynamiteClient.loadNativeRemoteLibrary(DynamiteClient.java:8)
        at com.google.ar.core.Session.nativeCreateSessionAndWrapperWithFeatures(Native Method)
        at com.google.ar.core.Session.<init>(Session.java:11)
2021-09-16 13:39:54.889 31259-1897/? I/third_party/arcore/java/com/google/vr/dynamite/client/native/dynamite_client.cc: Dynamite::LoadNativeRemoteLibrary handle=0
2021-09-16 13:39:54.889 31259-1897/? E/third_party/arcore/ar/core/android/sdk/session_create.cc: Dynamite failed to load remote library
2021-09-16 13:39:54.889 31259-1897/? E/third_party/arcore/ar/core/android/sdk/session_create.cc: LoadSymbolsDynamite returning AR_ERROR_FATAL.
2021-09-16 13:39:54.889 31259-1897/? E/third_party/arcore/ar/core/android/sdk/session_create.cc: LoadSymbols returning status.
2021-09-16 13:39:54.889 31259-1897/? E/ARCorePlus: Failed to start ARCore
2021-09-16 13:39:54.889 31259-1897/? W/System.err: com.google.ar.core.exceptions.FatalException
2021-09-16 13:39:54.889 31259-1897/? W/System.err:     at java.lang.reflect.Constructor.newInstance0(Native Method)
2021-09-16 13:39:54.889 31259-1897/? W/System.err:     at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
2021-09-16 13:39:54.889 31259-1897/? W/System.err:     at com.google.ar.core.Session.throwExceptionFromArStatus(Session.java:16)
2021-09-16 13:39:54.889 31259-1897/? W/System.err:     at com.google.ar.core.Session.nativeCreateSessionAndWrapperWithFeatures(Native Method)
2021-09-16 13:39:54.889 31259-1897/? W/System.err:     at com.google.ar.core.Session.<init>(Session.java:11)
```

I know that there is a separate repo for arcore for unity, but for some reason it has been archived and it's impossible to write an issue there.

**Comment by devbridie** [comment]
I think this is related to the [ARCore 64-bit requirement](https://developers.google.com/ar/64bit). This would line up with what's happening on your devices:

* S20: 32-bit version of ARCore is removed, leaving only the 64-bit version. In this situation your application may be built in 32 bit mode only, which leads to a crash due to an ABI mismatch (related to [this article](https://blog.chromium.org/2021/03/advanced-memory-management-and-more.html)),
* S7: retains both 32-bit and 64-bit versions, which allows ARCore to select the correct ABI and does not crash.

You would likely see this if your Unity application is compiled in 32-bit mode only; in this configuration, ARCore native libraries can't be loaded due to the ABI mismatch. Check out [this page on ARCore 64-bit compatibility](https://developers.google.com/ar/64bit) for mitigations.

**Comment by Pawel-Dybowski-1000realities** [comment]
After a little fight with il2cpp (because mono is not supported for 64-bit architectures) I managed to get it to run and it actually works in 64-bit version.
Thank you very much.
