### ISSUE TITLE
ar core error

### ISSUE THREAD

**Issue by wizVR-zhangjun** [google-ar/arcore-android-sdk#1518]
2022-06-22 16:53:21.751 8223-8253/? E/DynamiteClient: Failed to load native library [packageName=com.google.ar.core,libraryName=arcore_c] from remote package:
      
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libarcore_c.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at com.google.vr.dynamite.NativeLibraryLoader.b(PG:5)
        at com.google.vr.dynamite.NativeLibraryLoader.initializeAndLoadNativeLibrary(PG:2)
        at fea.A(PG:8)
        at afz.onTransact(PG:3)
        at android.os.Binder.transact(Binder.java:1043)
        at com.google.a.a.a.b(BaseProxy.java:2)
        at com.google.vr.dynamite.client.b.initializeAndLoadNativeLibrary(INativeLibraryLoader.java:3)
        at com.google.vr.dynamite.client.DynamiteClient.loadNativeRemoteLibrary(DynamiteClient.java:8)
        at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
        at com.unity3d.player.UnityPlayer.access$600(Unknown Source:0)
        at com.unity3d.player.UnityPlayer$g$1.handleMessage(Unknown Source:150)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:236)
        at com.unity3d.player.UnityPlayer$g.run(Unknown Source:20)

**Comment by ovivoda** [comment]
@wizVR-zhangjun have you found any fix for this? I have the same problem when an ARCore instant app is installed and launched from GooglePlay

**Comment by rainerlonau** [comment]
Hi, I´ve got the same error in my Unity project.
Unity 2021.3.10f1
ARFoundation 4.2.7
ARCore XR Plugin 4.2.7
ARKit XR plugin 4.2.7

The app works on iOS. Android crashes...
