### ISSUE TITLE
Black screen on Samsung S7 (Android 7) ; and on other devices/Android versions?

### ISSUE THREAD

**Issue by agGitHub** [google-ar/arcore-android-sdk#1523]
### SPECIFIC ISSUE ENCOUNTERED

On my Samsung S7 (Android 7) (and only on this device among my few test devices), I get a black screen on the AR session. Due to an exception on session.update(). I don't know if this bug occurs on other devices or Android versions. So I consider it as potentially frequent as it happens on one of my test devices. 

Please tell me how to fix this problem.

Here is the error log:

```
2022-06-30 11:49:21.155 10779-11127/com.mycompany.myproject E/native: E0000 00:00:1656582561.155423   11127 error_policy_util.cc:263] 
    ################ ARCore Native Error ##################
    BUILD_CHANGELIST:452219294
    BUILD_BASELINE_CHANGELIST:452219294
    ################### Stack Trace Begin ################
    ARCoreError: third_party/arcore/ar/core/android/implementation/android_frame_manager_gl.cc:351	https://cs.corp.google.com/piper///depot/google3/third_party/arcore/ar/core/android/implementation/android_frame_manager_gl.cc?g=0&l=351
    ARCoreError: third_party/arcore/ar/core/android/implementation/android_frame_manager_gl.cc:60	https://cs.corp.google.com/piper///depot/google3/third_party/arcore/ar/core/android/implementation/android_frame_manager_gl.cc?g=0&l=60
    ARCoreError: third_party/arcore/ar/core/frame_manager.cc:420	https://cs.corp.google.com/piper///depot/google3/third_party/arcore/ar/core/frame_manager.cc?g=0&l=420
    ARCoreError: third_party/arcore/ar/core/frame_manager.cc:328	https://cs.corp.google.com/piper///depot/google3/third_party/arcore/ar/core/frame_manager.cc?g=0&l=328
    ARCoreError: third_party/arcore/ar/core/session.cc:1739	https://cs.corp.google.com/piper///depot/google3/third_party/arcore/ar/core/session.cc?g=0&l=1739
    ARCoreError: third_party/arcore/ar/core/c_api/session_lite_c_api.cc:76	https://cs.corp.google.com/piper///depot/google3/third_party/arcore/ar/core/c_api/session_lite_c_api.cc?g=0&l=76
    ################### Stack Trace End #################
    
    ################### Undecorated Trace Begin  #################
    INTERNAL: 
    ARCoreError: third_party/arcore/ar/core/session.cc:1739
    
    ARCoreError: third_party/arcore/ar/core/frame_manager.cc:328
    
    ARCoreError: third_party/arcore/ar/core/frame_manager.cc:420
    
    ARCoreError: third_party/arcore/ar/core/android/implementation/android_frame_manager_gl.cc:60
    
    ARCoreError: third_party/arcore/ar/core/android/implementation/android_frame_manager_gl.cc:351
     egl_error=12294frame manager shared context: eglCreateContext failed. [type.googleapis.com/util.ErrorSpacePayload='ArStatusErrorSpace::AR_ERROR_FATAL']
    === Source Location Trace: ===
    third_party/arcore/ar/core/status.cc:171
    third_party/arcore/ar/core/android/implementation/android_frame_manager_gl.cc:351
    third_party/arcore/ar/core/android/implementation/android_frame_manager_gl.cc:60
    third_party/arcore/ar/core/frame_manager.cc:420
    third_party/arcore/ar/core/frame_manager.cc:328
    third_party/arcore/ar/core/session.cc:1739
    
    ################### Undecorated Trace End  #################
2022-06-30 11:49:21.160 10779-11127/com.mycompany.myproject E/GLSurfaceRenderer: Exception on the OpenGL thread
    com.google.ar.core.exceptions.FatalException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
        at com.google.ar.core.Session.throwExceptionFromArStatus(Session.java:14)
        at com.google.ar.core.Session.nativeUpdate(Native Method)
        at com.google.ar.core.Session.update(Session.java:2)
        at com.mycompany.myproject.GLSurfaceRenderer.onDrawFrame(GLSurfaceRenderer.java:630)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1562)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1262)
```

### VERSIONS USED
- Android Studio: 
Android Studio Chipmunk | 2021.2.1 Patch 1
Build #AI-212.5712.43.2112.8609683, built on May 18, 2022
- ARCore SDK for Android: 1.32.0 (also happens on 1.31 and 1.30)
- Device manufacturer, model, and O/S: Samsung Galaxy S7
- Google Play Services for AR (ARCore):  =1.32.221520023
- Output of `adb shell getprop ro.build.fingerprint`: samsung/heroltexx/herolte:7.0/NRD90M/G930FXXU2DRD1:user/release-keys

### STEPS TO REPRODUCE THE ISSUE
 1. launch AR session (camera permission is allowed)
 3. black screen !
 

### WORKAROUNDS (IF ANY)
Not found.

### ADDITIONAL COMMENTS
Probably a rare bug, as I don't have many bad feedbacks in production but certainly a few percents of devices ; not acceptable.

**Comment by sandyfriend** [comment]
Could you try on Sample code to see if it works.
from the error log you updated, it seem related with your GL thread.
```
E/GLSurfaceRenderer: Exception on the OpenGL thread
```
