### ISSUE TITLE
Crash when the Play Store is disabled on the device

### ISSUE THREAD

**Issue by bherbst** [google-ar/arcore-android-sdk#1542]
### SPECIFIC ISSUE ENCOUNTERED
ARCore crashes when the Play Store is disabled on the device, but an update to Play Services for AR is required.

The root cause is 
> android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=market://details?id=com.google.ar.core }

Ideally this would result in an error message instead of crashing.

Second, we **are** checking availability via `ArCoreApk.getInstance().checkAvailability(context)`, and `isSupported` is true in this case. Even more so than fixing the crash, I would prefer if `checkAvailability()` also checked for this scenario (update needed, but can't use the Play Store to update). That would help prevent us from even offering the option to our users if it is going to fail.

### VERSIONS USED
- Android Studio: N/A - built from CI
- ARCore SDK for Android: 1.21.0
- Device manufacturer, model, and O/S: Zebra Techologies, TC57 (also seen on TC56, TC51), Android 8.1.0
- Google Play Services for AR (ARCore):  v1.7.190128066

Note that these devices are managed devices, not typical consumer devices. That is why the Play Store is installed but not enabled. 

### STEPS TO REPRODUCE THE ISSUE
 1. Get a managed device with the Play Store installed but disabled
 1. Try to use AR Core!

### WORKAROUNDS (IF ANY)
We are adding a check in our app alongside `ArCoreApk.getInstance().checkAvailability()` for the Play Store's status:

```kotlin
fun isPlayStoreEnabled(): Boolean {
    try {
      val playStoreInfo = context.packageManager.getApplicationInfo("com.android.vending", 0)
      return playStoreInfo.enabled
    } catch (e: PackageManager.NameNotFoundException) {
      // Android 11+ limits visibility of packages and the Play Store is not explicitly guaranteed
      // to be visible. We could also just be running on a device without the Play Store at all.
      return false
    }
  }
```

### ADDITIONAL COMMENTS
Full stacktrace:

```
java.lang.RuntimeException: Unable to resume activity {com.target.ui/com.target.siiys.ui.SeeItInYourSpaceActivity}: com.google.ar.core.exceptions.FatalException: Failed to launch installer.
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3584)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3624)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1641)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6518)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

Caused by: com.google.ar.core.exceptions.FatalException: Failed to launch installer.
        at com.google.ar.core.w.o(w:7)
        at com.google.ar.core.w.d(w:12)
        at com.google.ar.core.InstallActivity.startInstaller(InstallActivity:4)
        at com.google.ar.core.InstallActivity.onResume(InstallActivity:3)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1356)
        at android.app.Activity.performResume(Activity.java:7131)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3559)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3624)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2865)
        at android.app.ActivityThread.-wrap11(Unknown)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1592)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6518)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=market://details?id=com.google.ar.core }
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1944)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1618)
        at android.app.Activity.startActivityForResult(Activity.java:4501)
        at android.app.Activity.startActivityForResult(Activity.java:4459)
        at android.app.Activity.startActivity(Activity.java:4820)
        at android.app.Activity.startActivity(Activity.java:4788)
        at com.google.ar.core.w.o(w:6)
        at com.google.ar.core.w.d(w:12)
        at com.google.ar.core.InstallActivity.startInstaller(InstallActivity:4)
        at com.google.ar.core.InstallActivity.onResume(InstallActivity:3)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1356)
        at android.app.Activity.performResume(Activity.java:7131)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3559)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3624)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2865)
        at android.app.ActivityThread.-wrap11(Unknown)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1592)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6518)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by devbridie** [comment]
I saw a fix for this recently; could you verify that the exception will be propagated on recent versions of the SDK instead of triggering a fatal crash? 

In the meantime, looking into your suggestion of catching this case in `checkAvailability`, thanks.

**Comment by bherbst** [comment]
Just tried with 1.33.0 of the SDK and it crashes with the same exception. Certainly possible the fix is going in the next release though!
