### ISSUE TITLE
ar installed, but doesn't start - xiaomi redmi note 11s

### ISSUE THREAD

**Issue by iuiu34** [google-ar/arcore-android-sdk#1554]
Hi,
i have a xiaomi redmi note 11s. I'm able to install google ar. But when i click open, doesn't open.

In google maps, i have available the 'live view' button. When i click, the app suddenly stops.

What i have to do to use ar? in particular, live view?

thanks

**Comment by musilto7** [comment]
I Also have same problem on Xiaomi Redmi Note 11.

There is crash log from crashlytics:

```
Caused by java.lang.IllegalArgumentException: getCameraCharacteristics:756: Unable to retrieve camera characteristics for unknown device 0: No such file or directory (-2)
       at android.hardware.camera2.CameraManager.throwAsPublicException(CameraManager.java:1266)
       at android.hardware.camera2.CameraManager.getCameraCharacteristics(CameraManager.java:553)
       at fqg.e(PG:10)
       at fqg.f(PG:4)
       at cqf.a(:12)
       at fqb.e(PG:5)
       at fuh.run(PG:12)
       at fyl.run(PG:2)
       at fzo.run(PG:1)
       at fzi.f(PG:2)
       at fzh.run(PG:6)
```

I am Using ArFragment. My version of ArCore 1.35.0. Tester says that app becomes unresponsive for few minutes, and after that app is restarted and then ArCore functionality starts to work.

It causes problems only on start I am not doing anything special there. It works on other devices.

**Comment by iuiu34** [comment]
hi,
change region to indonesia (or whatever global one)
install global rom update: SKEEUXM. ( automatically available)

afterword everything with google ar works

**Comment by musilto7** [comment]
> hi, change region to indonesia (or whatever global one) install global rom update: SKEEUXM. ( automatically available)
> 
> afterwards everything with google ar works

Hi,
It is not option to fix it that way. I have to fixed it without forcing users to do these actions.
