### ISSUE TITLE
ARCore crashes on specific devices

### ISSUE THREAD

**Issue by wifisolutionsua** [google-ar/arcore-android-sdk#1594]
### SPECIFIC ISSUE ENCOUNTERED
Some android phones crash on ARcore initialization. All apps downloaded from market are crashing. Tested devices are in supported ArCore list.

Finally I have found the device that reproduces the issue that follows AR-apps for a long time.
Device list faced with this issue: - due to Crashlytics
Samsung: A70, A51, A50, A30, A32
Xiaomi: Note 7Pro, Note 10
Google: Pixel, Pixel 3a.
LG: K61
and some others.
Android versions 10-13.

### VERSIONS USED
- Android Studio: 2022.2.1
- ARCore SDK for Android: 1.37.0
- Device manufacturer, model, and O/S: LG K61 (LM-Q630EAW),  freshly reseted to factory defaults, Google account logged in
- Google Play Services for AR (ARCore):  1.37.231000423
- Output of `adb shell getprop ro.build.fingerprint`: lge/mdh40lm_fne/mdh40lm:11/RKQ1.210420.001/230942131c7f7.OPEN_EU_DS:user/release-keys

### STEPS TO REPRODUCE THE ISSUE
 1. Download any Android sample, for example hello_ar_kotlin
 2. Run the sample, give access to the camera on the phone.
 3. Get the crash:
ARCoreError: third_party/arcore/ar/infrastructure/android_data_source.cc:912
ARCoreError: third_party/arcore/ar/infrastructure/android/android_sensors.cc:118
 Could not create requested uncalibrated gyro.
=== Source Location Trace: === 
third_party/arcore/ar/infrastructure/android/android_sensors.cc:118

### ADDITIONAL COMMENTS
My logcat:
`
12:39:29.799 native                  com....core.examples.kotlin.helloar  I  I0000 00:00:1686908369.799380   21761 session.cc:578] New session config:
                                                                             ArConfig
                                                                              augmented_face_mode:           AR_AUGMENTED_FACE_MODE_DISABLED
                                                                              augmented_image_database:      <null>
                                                                              cloud_anchor_mode:             AR_CLOUD_ANCHOR_MODE_DISABLED
                                                                              depth_mode:                    AR_DEPTH_MODE_DISABLED
                                                                              semantic_mode:                AR_SEMANTIC_MODE_DISABLED
                                                                              focus_mode:                    AR_FOCUS_MODE_FIXED
                                                                              geospatial_mode:               AR_GEOSPATIAL_MODE_DISABLED
                                                                              instant_placement_mode:        AR_INSTANT_PLACEMENT_MODE_DISABLED
                                                                              light_estimation_mode:         AR_LIGHT_ESTIMATION_MODE_ENVIRONMENTAL_HDR
                                                                              plane_finding_mode:            AR_PLANE_FINDING_MODE_HORIZONTAL_AND_VERTICAL
                                                                              update_mode:                   AR_UPDATE_MODE_BLOCKING
12:39:29.799 native                  com....core.examples.kotlin.helloar  I  I0000 00:00:1686908369.799605   21761 session.cc:571] Session::CheckAndWriteCurrentConfig returning OK.
12:39:29.799 native                  com....core.examples.kotlin.helloar  I  I0000 00:00:1686908369.799752   21761 session.cc:1239] Entering Session::Resume.
12:39:29.801 native                  com....core.examples.kotlin.helloar  I  I0000 00:00:1686908369.801126   21761 camera_config_manager.cc:719] UpdateBugFixes on CameraConfigManager is unimplemented!
12:39:29.815 tflite                  com....core.examples.kotlin.helloar  I  Replacing 69 node(s) with delegate (TfLiteXNNPackDelegate) node, yielding 3 partitions for the whole graph.
12:39:29.861 CameraManager           com....core.examples.kotlin.helloar  I  camera Id = 0, packageName = com.google.ar.core.examples.kotlin.helloar
12:39:29.864 native                  com....core.examples.kotlin.helloar  I  I0000 00:00:1686908369.864320   21761 eis_manager.cc:68] EIS turned off
12:39:29.864 native                  com....core.examples.kotlin.helloar  I  I0000 00:00:1686908369.864495   21761 eis_manager.cc:79] current_eis_metadata_.frame_size 1440 x 1080
12:39:29.864 native                  com....core.examples.kotlin.helloar  I  I0000 00:00:1686908369.864524   21761 android_camera.cc:168] Camera start operation timeout set to 4000 ms.
12:39:29.864 native                  com....core.examples.kotlin.helloar  I  I0000 00:00:1686908369.864555   21761 android_camera.cc:1826] Initializing camera manager.
12:39:29.866 ACameraManager          com....core.examples.kotlin.helloar  E  onStatusChangedLocked return!!!
12:39:29.866 ACameraManager          com....core.examples.kotlin.helloar  E  onStatusChangedLocked return!!!
12:39:29.874 native                  com....core.examples.kotlin.helloar  I  I0000 00:00:1686908369.874338   21761 android_camera.cc:1852] Camera manager initialized successfully with 3 cameras.
12:39:29.874 native                  com....core.examples.kotlin.helloar  I  I0000 00:00:1686908369.874513   21761 android_camera.cc:762] [Camera=0; State=CLOSED] Reset cleanly got to CLOSED state.
12:39:29.874 native                  com....core.examples.kotlin.helloar  I  I0000 00:00:1686908369.874933   21761 android_camera.cc:762] [Camera=2; State=CLOSED] Reset cleanly got to CLOSED state.
12:39:29.875 native                  com....core.examples.kotlin.helloar  I  I0000 00:00:1686908369.875298   21761 android_camera.cc:762] [Camera=1; State=CLOSED] Reset cleanly got to CLOSED state.
12:39:29.876 native                  com....core.examples.kotlin.helloar  I  I0000 00:00:1686908369.876392   21761 session.cc:3580] Update Frame Delay to 0 frames.
12:39:29.896 native                  com....core.examples.kotlin.helloar  E  E0000 00:00:1686908369.896757   21761 android_data_source.cc:912] UNAVAILABLE: 
                                                                             ARCoreError: third_party/arcore/ar/infrastructure/android_data_source.cc:912
                                                                             
                                                                             ARCoreError: third_party/arcore/ar/infrastructure/android/android_sensors.cc:118
                                                                             Could not create requested uncalibrated gyro.
                                                                             === Source Location Trace: === 
                                                                             third_party/arcore/ar/infrastructure/android/android_sensors.cc:118
12:39:29.896 native                  com....core.examples.kotlin.helloar  W  W0000 00:00:1686908369.896932   21761 session.cc:1421] UNAVAILABLE: 
                                                                             ARCoreError: third_party/arcore/ar/core/session.cc:1421
                                                                             
                                                                             ARCoreError: third_party/arcore/ar/infrastructure/android_data_source.cc:458
                                                                             
                                                                             ARCoreError: third_party/arcore/ar/infrastructure/android_data_source.cc:912
                                                                             
                                                                             ARCoreError: third_party/arcore/ar/infrastructure/android/android_sensors.cc:118
                                                                             Could not create requested uncalibrated gyro.
                                                                             === Source Location Trace: === 
                                                                             third_party/arcore/ar/infrastructure/android/android_sensors.cc:118
                                                                             third_party/arcore/ar/infrastructure/android_data_source.cc:912
                                                                             third_party/arcore/ar/infrastructure/android_data_source.cc:458
12:39:29.897 native                  com....core.examples.kotlin.helloar  E  E0000 00:00:1686908369.897341   21761 error_policy_util.cc:263] 
                                                                             ################ ARCore Native Error ##################
                                                                             BUILD_CHANGELIST:526077224
                                                                             BUILD_BASELINE_CHANGELIST:523012057
                                                                             ################### Stack Trace Begin ################
                                                                             ARCoreError: third_party/arcore/ar/infrastructure/android/android_sensors.cc:118	https://cs.corp.google.com/piper///depot/google3/third_party/arcore/ar/infrastructure/android/android_sensors.cc?g=0&l=118
                                                                             ARCoreError: third_party/arcore/ar/infrastructure/android_data_source.cc:912	https://cs.corp.google.com/piper///depot/google3/third_party/arcore/ar/infrastructure/android_data_source.cc?g=0&l=912
                                                                             ARCoreError: third_party/arcore/ar/infrastructure/android_data_source.cc:458	https://cs.corp.google.com/piper///depot/google3/third_party/arcore/ar/infrastructure/android_data_source.cc?g=0&l=458
                                                                             ARCoreError: third_party/arcore/ar/core/session.cc:1421	https://cs.corp.google.com/piper///depot/google3/third_party/arcore/ar/core/session.cc?g=0&l=1421
                                                                             ARCoreError: third_party/arcore/ar/core/c_api/session_lite_c_api.cc:50	https://cs.corp.google.com/piper///depot/google3/third_party/arcore/ar/core/c_api/session_lite_c_api.cc?g=0&l=50
                                                                             ################### Stack Trace End #################
                                                                             
                                                                             ################### Undecorated Trace Begin  #################
                                                                             UNAVAILABLE: 
                                                                             ARCoreError: third_party/arcore/ar/core/session.cc:1421
                                                                             
                                                                             ARCoreError: third_party/arcore/ar/infrastructure/android_data_source.cc:458
                                                                             
                                                                             ARCoreError: third_party/arcore/ar/infrastructure/android_data_source.cc:912
                                                                             
                                                                             ARCoreError: third_party/arcore/ar/infrastructure/android/android_sensors.cc:118
                                                                             Could not create requested uncalibrated gyro.
                                                                             === Source Location Trace: === 
                                                                             third_party/arcore/ar/infrastructure/android/android_sensors.cc:118
                                                                             third_party/arcore/ar/infrastructure/android_data_source.cc:912
                                                                             third_party/arcore/ar/infrastructure/android_data_source.cc:458
                                                                             third_party/arcore/ar/core/session.cc:1421
                                                                             
                                                                             ################### Undecorated Trace End  #################
12:39:29.902 AndroidRuntime          com....core.examples.kotlin.helloar  D  Shutting down VM
12:39:29.905 AndroidRuntime          com....core.examples.kotlin.helloar  E  FATAL EXCEPTION: main
                                                                             Process: com.google.ar.core.examples.kotlin.helloar, PID: 21761
                                                                             java.lang.RuntimeException: Unable to resume activity {com.google.ar.core.examples.kotlin.helloar/com.google.ar.core.examples.kotlin.helloar.HelloArActivity}: com.google.ar.core.exceptions.FatalException
                                                                             	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4515)
                                                                             	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4547)
                                                                             	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
                                                                             	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
                                                                             	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
                                                                             	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2084)
                                                                             	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                             	at android.os.Looper.loop(Looper.java:223)
                                                                             	at android.app.ActivityThread.main(ActivityThread.java:7888)
                                                                             	at java.lang.reflect.Method.invoke(Native Method)
                                                                             	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
                                                                             	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
                                                                             Caused by: com.google.ar.core.exceptions.FatalException
                                                                             	at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                             	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
                                                                             	at com.google.ar.core.Session.throwExceptionFromArStatus(Session.java:14)
                                                                             	at com.google.ar.core.Session.nativeResume(Native Method)
                                                                             	at com.google.ar.core.Session.resume(Session.java:1)
                                                                             	at com.google.ar.core.examples.kotlin.common.helpers.ARCoreSessionLifecycleHelper.onResume(ARCoreSessionLifecycleHelper.kt:99)
                                                                             	at androidx.lifecycle.FullLifecycleObserverAdapter.onStateChanged(FullLifecycleObserverAdapter.java:42)
                                                                             	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:361)
                                                                             	at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:300)
                                                                             	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:339)
                                                                             	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:145)
                                                                             	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:131)
                                                                             	at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:123)
                                                                             	at androidx.lifecycle.ReportFragment.onResume(ReportFragment.java:90)
                                                                             	at android.app.Fragment.performResume(Fragment.java:2551)
                                                                             	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1346)
                                                                             	at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1581)
                                                                             	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1642)
                                                                             	at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3052)
                                                                             	at android.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:3014)
                                                                             	at android.app.FragmentController.dispatchResume(FragmentController.java:206)
                                                                             	at android.app.Activity.performResume(Activity.java:8176)
                                                                             	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4505)
                                                                             	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4547) 
                                                                             	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52) 
                                                                             	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
                                                                             	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
                                                                             	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2084) 
                                                                             	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                             	at android.os.Looper.loop(Looper.java:223) 
                                                                             	at android.app.ActivityThread.main(ActivityThread.java:7888) 
                                                                             	at java.lang.reflect.Method.invoke(Native Method) 
                                                                             	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
                                                                             	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981) 
12:39:29.935 Process                 com....core.examples.kotlin.helloar  I  Sending signal. PID: 21761 SIG: 9`

**Comment by ChristopheChevallier** [comment]
Hi everyone!
Has there been any updates on this? I'm running on the same issue on a pixel 6.

Thanks

**Comment by wifisolutionsua** [comment]
Faced with same issue on
Samsung Galaxy A20s Android 11
Huawei Y9 2019 Android 9

**Comment by faysal-swe** [comment]
are there any updates?
because AR Core Crashes apps on Android 14.
