### ISSUE TITLE
Fatal exception on Session.createAnchor

### ISSUE THREAD

**Issue by havel-sophis** [google-ar/arcore-android-sdk#1607]
### SPECIFIC ISSUE ENCOUNTERED
When I call this:
```
if (camera.getTrackingState() == TrackingState.TRACKING) {
    anchor = session.createAnchor(new Pose(pos, rotation));
}
```
my Activity closes with ``FATAL EXCEPTION: GLThread 1617536``. It happens when I do cover camera.
Im probably doing something stupid but as it crashes directly in AR core I have no idea what ... hopefully this stack trace will help:

```
FATAL EXCEPTION: GLThread 1617536
Process: REDACTED, PID: 16011
    com.google.ar.core.exceptions.FatalException
    at java.lang.reflect.Constructor.newInstance0(Native Method)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
    at com.google.ar.core.Session.throwExceptionFromArStatus(Session.java:14)
    at com.google.ar.core.Session.nativeCreateAnchor(Native Method)
    at com.google.ar.core.Session.createAnchor(Session.java:1) ...
```

### VERSIONS USED
- Android Studio: 2021.3.1 Patch 1
- ARCore SDK for Android: 1.38.0
- Device manufacturer, model, and O/S: Samsung, Galaxy Note 9, Android 10
- Google Play Services for AR (ARCore):  1.39.232070583
- Output of `adb shell getprop ro.build.fingerprint`: samsung/crownltexx/crownlte:10/QP1A.190711.020/N960FXXU9FVH1:user/release-keys

**Comment by AAWA-byt** [comment]
@havel-sophis
Hi, I recently encountered exactly the same problem. Have you perhaps found a solution?

**Comment by havel-sophis** [comment]
> @havel-sophis Hi, I recently encountered exactly the same problem. Have you perhaps found a solution?

No, let me know if you will have some luck but its probably on Google's side and as they do not seems to care ....

**Comment by AAWA-byt** [comment]
> > @havel-sophis Hi, I recently encountered exactly the same problem. Have you perhaps found a solution?
> 
> No, let me know if you will have some luck but its probably on Google's side and as they do not seems to care ....

I don't know in which context you are using arcore, but I have tried to extend this project for my purposes.
In line 246 I get the same error as you. Of course I also changed a few things (maybe that's the problem). Perhaps this will help you.

https://github.com/google-ar/codelab-raw-depth-api/blob/main/part3_completed/src/main/java/com/google/ar/core/codelab/rawdepth/RawDepthCodelabActivity.java

**Comment by behelit** [comment]
Could you at least add logging so that us users know what the actual error is instead of a generic fatal exception. It's so useless.
