### ISSUE TITLE
Issue running in emulator

### ISSUE THREAD

**Issue by gurizilla** [google-ar/arcore-android-sdk#192]
Hi, when trying to run the sample on Android Studio, app is not opening on AVD with "HelloAR Java has stopped" being raised.

Full log is here:

02/24 14:48:24: Launching app
$ adb shell am start -n "com.google.ar.core.examples.java.helloar/com.google.ar.core.examples.java.helloar.HelloArActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Client not ready yet..Connected to process 7811 on device emulator-5556
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/InstantRun: starting instant run server: is main process
W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Swap behavior 1
D/EGL_emulation: eglCreateContext: 0xab2050c0: maj 2 min 0 rcv 2
D/EGL_emulation: eglMakeCurrent: 0xab2050c0: ver 2 0 (tinfo 0xab2037d0)
D/EGL_emulation: eglCreateContext: 0x9dad5800: maj 2 min 0 rcv 2
W/ARCore-IS: bindService returned false.
E/ARCore-IS: Play Store install service could not be bound.
W/ARCore-IA: Preliminary compatibility check failed.
D/EGL_emulation: eglMakeCurrent: 0x9dad5800: ver 2 0 (tinfo 0x9baff4a0)
I/Choreographer: Skipped 44 frames!  The application may be doing too much work on its main thread.
E/ObjectRenderer: Texture loading: glError 1282
E/AndroidRuntime: FATAL EXCEPTION: GLThread 335
                  Process: com.google.ar.core.examples.java.helloar, PID: 7811
                  java.lang.RuntimeException: Texture loading: glError 1282
                      at com.google.ar.core.examples.java.helloar.rendering.ShaderUtil.checkGLError(ShaderUtil.java:73)
                      at com.google.ar.core.examples.java.helloar.rendering.ObjectRenderer.createOnGlThread(ObjectRenderer.java:128)
                      at com.google.ar.core.examples.java.helloar.HelloArActivity.onSurfaceCreated(HelloArActivity.java:250)
                      at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1516)
                      at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1259)
D/EGL_emulation: eglMakeCurrent: 0xab2050c0: ver 2 0 (tinfo 0xab2037d0)
D/EGL_emulation: eglMakeCurrent: 0xab2050c0: ver 2 0 (tinfo 0xab2037d0)
I/Choreographer: Skipped 37 frames!  The application may be doing too much work on its main thread.
Application terminated.

**Details from the Virtual Device:**
Name: Pixel_2_XL_API_25
CPU/ABI: Google APIs Intel Atom (x86)
Path: C:\Users\i826874\.android\avd\Pixel_2_XL_API_25_1.avd
Target: google_apis [Google APIs] (API level 25)
Skin: pixel_2_xl
SD Card: 100M
hw.dPad: no
hw.lcd.height: 2880
runtime.network.speed: full
hw.accelerometer: yes
hw.device.name: pixel_2_xl
vm.heapSize: 256
skin.dynamic: yes
hw.device.manufacturer: Google
hw.lcd.width: 1440
hw.gps: yes
hw.initialOrientation: Portrait
image.androidVersion.api: 25
hw.audioInput: yes
image.sysdir.1: system-images\android-25\google_apis\x86\
tag.id: google_apis
showDeviceFrame: yes
hw.camera.back: emulated
hw.mainKeys: no
AvdId: Pixel_2_XL_API_25
hw.camera.front: emulated
hw.lcd.density: 560
avd.ini.displayname: Pixel 2 XL API 25
hw.gpu.mode: auto
hw.device.hash2: MD5:1a4fa6b2569f0b76bfb9824b6b6fc976
hw.ramSize: 1536
hw.trackBall: no
PlayStore.enabled: false
fastboot.forceColdBoot: no
hw.battery: yes
hw.cpu.ncore: 2
hw.sdCard: yes
tag.display: Google APIs
runtime.network.latency: none
hw.keyboard: yes
hw.sensors.proximity: yes
disk.dataPartition.size: 800M
hw.sensors.orientation: yes
avd.ini.encoding: UTF-8
hw.gpu.enabled: yes

**Comment by imknown** [comment]
The same on `Linux` + `Pixel 2 API 27 Google API x86 Image Rev. 4 emulator` + `AS 3.2 canary 4`:

```
02-26 14:31:32.653 6113-6113/? I/zygote: Not late-enabling -Xcheck:jni (already on)
02-26 14:31:32.663 6113-6113/? W/zygote: Unexpected CPU variant for X86 using defaults: x86
02-26 14:31:32.741 6113-6113/com.google.ar.core.examples.java.helloar W/es.java.helloar: type=1400 audit(0.0:38): avc: denied { read } for name="stat" dev="proc" ino=4026531999 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:proc_stat:s0 tclass=file permissive=0
02-26 14:31:32.753 6113-6113/com.google.ar.core.examples.java.helloar I/native: session_create.cc:71 ArSession_create with info: Entering
02-26 14:31:32.824 6113-6113/com.google.ar.core.examples.java.helloar I/zygote: The ClassLoaderContext is a special shared library.
02-26 14:31:32.821 6113-6113/com.google.ar.core.examples.java.helloar W/es.java.helloar: type=1400 audit(0.0:39): avc: denied { read } for name="stat" dev="proc" ino=4026531999 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:proc_stat:s0 tclass=file permissive=0
02-26 14:31:32.835 6113-6113/com.google.ar.core.examples.java.helloar I/native: version_check.cc:23 ARCore APK version:1.0.180129108, SDK version: 1.0.0
    session_create.cc:37 LoadDynamite with info: Dynamite load ok.
02-26 14:31:32.831 6113-6113/com.google.ar.core.examples.java.helloar W/es.java.helloar: type=1400 audit(0.0:40): avc: denied { read } for name="stat" dev="proc" ino=4026531999 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:proc_stat:s0 tclass=file permissive=0
02-26 14:31:32.846 6113-6113/com.google.ar.core.examples.java.helloar D/MtpDeviceJNI: register_android_mtp_MtpDevice
02-26 14:31:32.847 6113-6113/com.google.ar.core.examples.java.helloar I/native: session_create_implementation.cc:467 Entering ArSession_createImplementation. ARCore SDK version: [1.0.0].
02-26 14:31:32.864 6113-6113/com.google.ar.core.examples.java.helloar W/native: device_profile_proto_io.h:165 Camera id 0 frame rate not set.
    device_profile_proto_io.h:165 Camera id 1 frame rate not set.
    device_profile_proto_io.h:165 Camera id 2 frame rate not set.
    device_profile_proto_io.h:165 Camera id 3 frame rate not set.
02-26 14:31:32.865 6113-6113/com.google.ar.core.examples.java.helloar I/tango-ndk-hal: Found generic_x86: Setting LPF accel: 0.000 ms. gyro: 0.000 ms
02-26 14:31:32.866 6113-6113/com.google.ar.core.examples.java.helloar W/native: performance_manager.cc:18 Cannot get processor data.  Will not pin threads
02-26 14:31:32.868 6113-6113/com.google.ar.core.examples.java.helloar I/native: feature_matching_base.cc:38 Using gyro prediction for matching.
    feature_matcher_bin_manager.cc:157 Neighborhood radius for feature matcher bin-grid-0 is 21.2132 pixels.
    feature_matcher_bin_manager.cc:157 Neighborhood radius for feature matcher bin-grid-1 is 42.4264 pixels.
    feature_matcher_bin_manager.cc:157 Neighborhood radius for feature matcher bin-grid-2 is 64.1467 pixels.
    feature_matcher_bin_manager.cc:157 Neighborhood radius for feature matcher bin-grid-3 is 99.4286 pixels.
    feature_matcher_bin_manager.cc:157 Neighborhood radius for feature matcher bin-grid-4 is 148.18 pixels.
    gyro_feature_matching.cc:20 Running tracker at 10 Hz.
    vio_helper.cc:46 Use uncalibrated IMU scale factors.
    vio_helper.cc:58 Use uncalibrated IMU misalignment factors.
    data_manager.cc:78 Mapping Config: 
    ViwlsConfig: 
    OnlineMappingConfig: 
    enable_online_viwls: 1
    load_online_map_in_vio: 1
    enable_lite_com: 1
    incrementally_build_problem: 0
    
    MapFormulationConfig: 
    vio_drift_tolerance_rotation: 0.05
    vio_drift_tolerance_translation: 0.2
    enable_keypoint_pruning: 1
    enable_local_map_tracking: 1
    add_every_nth_keyframe: 3
    
    WLS_options: 
    estimate_camera_intrinsics: 0
    estimate_imu_camera_extrinsics: 0
    estimate_imu_intrinsics: 0
    calculate_keyframe_covariance: 0
    calculate_landmark_covariance: 0
    calculate_calibration_parameters_covariance: 0
    use_huber_loss_visual_cost_term: 1
    nonlinear_optimization_type: NLWLS
    num_outlier_rejection_loops: 1
    log_viwls_state_estimates_to_file: 0
    minimize_photometric_error: 0
    fail_on_missing_inv_depth_base_keyframe: 1
    enable_lite_com: 1
    ViwlsProblemType: kMarginalizedViwls
    incrementally_build_problem: 0
    
    MapSparsifierConfig: 
    enable_debug_output: 0
    marginalize_n_keyframes: 20
    retain_n_keyframes: 5
    enable_marginalization: 1
    
    MapLandmarkConfig: 
    min_landmark_observations: 5
    LandmarkParam: k3DInverseDepth
    min_depth_of_pointlandmark_from_image_plane: 0.05
    max_depth_of_pointlandmark_from_image_plane: 15
    landmark_covariance_use_approximation: 1
    keypoint_pixel_sigma: 1
    
    Debug_options: 
    simulator_export_state_error_sigma_info: 0
    log_visual_residuals: 0
    evaluation_log_directory: 
    
    
    DataManagerConfig: 
    visualization_enabled: 0
    execute_in_thread: 1
    enable_online_calibration: 0
    log_maps_for_visualization: 0
    fisheye_buffer_size: 7
    save_map_with_uuid_as_filename: 0
    save_map_filename: 
    evaluation_log_directory: 
    
    MapLifeCycleConfig: 
    save_map_for_structure_relocalization: 0
    enable_multi_map_merging: 1
    enable_time_base_map_split: 1
    
    MultiMapManagerConfig: 
    threshold_position_meters: 2
    threshold_orientation_radians: 0.174
    min_num_cross_adf_constraints: 9
    perform_full_multimap_optimization: 0
    merge_active_map_until_stable_coregistration: 1
    min_number_of_keyframes_to_add_adf: 25
02-26 14:31:32.919 6113-6113/com.google.ar.core.examples.java.helloar I/native: backend_base.h:55 LC-backend initialized.
02-26 14:31:32.923 6113-6113/com.google.ar.core.examples.java.helloar I/native: loop_detector_graph.cc:47 Initializing localizer with: loop_detector_engine: inverted_multi_index_pq
    low_power_localization: 0
    feature_descriptor: lens_invariant_ocvfreak
    override projection_matrix: 
    override quantizer: 
    override product quantizer: 
    max_num_of_image_to_image_matches: 1
    use_landmarks_for_relocalization: 0
    use_augmentation_with_previous_matches: 1
    verification_options:
    skip_bad_landmarks: 1
    overwrite_hamming_distance_threshold: -1
    min_geom_inlier_ratio: 0.35
    Ransac structure matching:
    min_num_points: 8
    max_iterations: 50
    confidence: 0.99
    sampson_error_threshold: 0.0008
    use_upright_pose_estimation: 1
    
    Ransac image to image matching:
    min_num_points: 8
    max_iterations: 50
    confidence: 0.99
    sampson_error_threshold: 0.0001
    use_upright_pose_estimation: 1
    
    compute_relative_pose_covariance: 0
    max_num_points_covariance_calc: 60
    min_match_image_time_difference: 10
    gravity_direction_threshold_degrees: 5
    matching_engine_options:
    projected_descriptor_dimensions: 16
    num_closest_words_for_nn_search: 30
    knn_search_epsilon: 2
    knn_max_radius: 100
    num_neighbors: -1
    vote_filter_type: covisibility-graph-filter
    use pose prior for image to image matching: 0
02-26 14:31:32.924 6113-6113/com.google.ar.core.examples.java.helloar I/native: device_provider.cc:715 Identified device type: kEmulator
    calibration_provider.cc:539 Instantiating calibration provider with sources:
    	CAD: 
    	Factory: 
    	Online: 
    	ActiveFile: kHardcodedCadModel
    	Hardcoded CAD model fallback: Disabled
    	Device type: kEmulator
    calibration_provider.cc:379 Successfully parsed requested Hardcoded CAD model for device type: kEmulator.
    tango_calibration_fetcher.cc:85 Fetched Camera Intrinsics from Tango
    tango_calibration_fetcher.cc:59 Camera Model Width/Height:640,480
    session_create_implementation.cc:557 ArSession_createImplementation returning OK.
02-26 14:31:32.937 6113-6113/com.google.ar.core.examples.java.helloar I/native: session.cc:260 Entering Session::Resume.
    android_camera.cc:1120 Initializing camera manager.
02-26 14:31:32.938 6113-6113/com.google.ar.core.examples.java.helloar I/native: android_camera.cc:1135 Camera manager initialized successfully with 1 cameras.
02-26 14:31:32.938 6113-6113/com.google.ar.core.examples.java.helloar E/NdkImageReader: AImageReader_getWindow
02-26 14:31:32.946 6113-6137/com.google.ar.core.examples.java.helloar I/native: cameras.cc:244 Camera changed state from 0 to 1: Camera device opened succesfully.
    cameras.cc:244 Camera changed state from 1 to 2: Capture session starting...
    cameras.cc:244 Camera changed state from 2 to 3: Capture session started streaming.
02-26 14:31:32.947 6113-6113/com.google.ar.core.examples.java.helloar I/tango-ndk-hal: Found calibrated gyro
    Found accelerometer
02-26 14:31:32.947 6113-6113/com.google.ar.core.examples.java.helloar I/native: session.cc:298 Session::Resume returning OK.
02-26 14:31:32.947 6113-6147/com.google.ar.core.examples.java.helloar I/tango-ndk-hal: Temperature sensor Goldfish Temperature sensor
    Gyro min delay 10000, using 10000
02-26 14:31:32.948 6113-6147/com.google.ar.core.examples.java.helloar I/tango-ndk-hal: Accel min delay 10000, using 10000
02-26 14:31:32.952 6113-6148/com.google.ar.core.examples.java.helloar D/OpenGLRenderer: HWUI GL Pipeline
02-26 14:31:33.043 6113-6148/com.google.ar.core.examples.java.helloar I/zygote: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
02-26 14:31:33.043 6113-6148/com.google.ar.core.examples.java.helloar I/OpenGLRenderer: Initialized EGL, version 1.4
02-26 14:31:33.043 6113-6148/com.google.ar.core.examples.java.helloar D/OpenGLRenderer: Swap behavior 1
02-26 14:31:33.101 6113-6148/com.google.ar.core.examples.java.helloar D/EGL_emulation: eglCreateContext: 0xd096b600: maj 3 min 0 rcv 3
02-26 14:31:33.132 6113-6148/com.google.ar.core.examples.java.helloar D/EGL_emulation: eglMakeCurrent: 0xd096b600: ver 3 0 (tinfo 0xd0affef0)
02-26 14:31:33.299 6113-6148/com.google.ar.core.examples.java.helloar D/EGL_emulation: eglMakeCurrent: 0xd096b600: ver 3 0 (tinfo 0xd0affef0)
02-26 14:31:33.300 6113-6129/com.google.ar.core.examples.java.helloar D/EGL_emulation: eglCreateContext: 0xe53840c0: maj 3 min 0 rcv 3
02-26 14:31:33.419 6113-6130/com.google.ar.core.examples.java.helloar I/native: arcore_feature_extractor_wrapper.cc:28 Extracting features using  ArcoreFeatureExtractorWrapper.
    arcore_feature_extractor_wrapper.cc:47 Narrow camera model.
02-26 14:31:33.466 6113-6132/com.google.ar.core.examples.java.helloar W/native: gyro_helper.cc:59 Gyro samples do not cover << [ 0 ; 692.609961004999946 ] sec. Use identity R. Gyro samples cover [ 692.352192360999993 ; 692.850111584000047 ] sec.
    feature_processing.cc:154 Skipping first feature measurement because we don't have a previous to diff against.
02-26 14:31:33.466 6113-6132/com.google.ar.core.examples.java.helloar I/native: vio_initializer.cc:648 Not accepting frame as first BA keyframe.
02-26 14:31:33.581 6113-6129/com.google.ar.core.examples.java.helloar D/EGL_emulation: eglMakeCurrent: 0xe53840c0: ver 3 0 (tinfo 0xe5383200)
02-26 14:31:33.624 6113-6129/com.google.ar.core.examples.java.helloar E/ObjectRenderer: Texture loading: glError 1282
02-26 14:31:33.634 6113-6129/com.google.ar.core.examples.java.helloar E/AndroidRuntime: FATAL EXCEPTION: GLThread 243
    Process: com.google.ar.core.examples.java.helloar, PID: 6113
    java.lang.RuntimeException: Texture loading: glError 1282
        at com.google.ar.core.examples.java.helloar.rendering.ShaderUtil.checkGLError(ShaderUtil.java:73)
        at com.google.ar.core.examples.java.helloar.rendering.ObjectRenderer.createOnGlThread(ObjectRenderer.java:128)
        at com.google.ar.core.examples.java.helloar.HelloArActivity.onSurfaceCreated(HelloArActivity.java:250)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1539)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)
02-26 14:31:33.749 6113-6113/com.google.ar.core.examples.java.helloar I/Choreographer: Skipped 31 frames!  The application may be doing too much work on its main thread.
02-26 14:31:33.764 6113-6132/com.google.ar.core.examples.java.helloar I/native: vio_initializer.cc:648 Not accepting frame as first BA keyframe.
02-26 14:31:33.825 6113-6132/com.google.ar.core.examples.java.helloar I/native: vio_initializer.cc:648 Not accepting frame as first BA keyframe.
02-26 14:31:34.332 6113-6113/com.google.ar.core.examples.java.helloar I/native: session.cc:303 Entering Session::Pause.
02-26 14:31:34.370 6113-6137/com.google.ar.core.examples.java.helloar I/native: cameras.cc:244 Camera changed state from 3 to 4: Capture session stopping...
02-26 14:31:34.582 6113-6125/com.google.ar.core.examples.java.helloar E/ACameraDevice: onDeviceIdle sending state cb
02-26 14:31:34.582 6113-6140/com.google.ar.core.examples.java.helloar I/native: android_camera.cc:1081 Capture sequence completed.
02-26 14:31:34.604 6113-6113/com.google.ar.core.examples.java.helloar I/native: android_camera.cc:1029 Capture session closed for camera 0
02-26 14:31:34.604 6113-6137/com.google.ar.core.examples.java.helloar I/native: cameras.cc:244 Camera changed state from 4 to 1: Capture session finished streaming.
02-26 14:31:34.643 6113-6113/com.google.ar.core.examples.java.helloar I/native: android_camera.cc:611 Reset cleanly got to CLOSED state for camera 0
    session.cc:332 Session::Pause returning OK.
02-26 14:31:34.643 6113-6137/com.google.ar.core.examples.java.helloar I/native: cameras.cc:244 Camera changed state from 1 to 0: Camera device closed succesfully.
02-26 14:31:34.644 6113-6113/com.google.ar.core.examples.java.helloar I/Choreographer: Skipped 53 frames!  The application may be doing too much work on its main thread.
02-26 14:31:34.715 6113-6148/com.google.ar.core.examples.java.helloar D/EGL_emulation: eglMakeCurrent: 0xd096b600: ver 3 0 (tinfo 0xd0affef0)
02-26 14:31:34.937 6113-6186/com.google.ar.core.examples.java.helloar V/StudioProfiler: Acquiring Application for Events
02-26 14:31:34.956 6113-6113/com.google.ar.core.examples.java.helloar V/StudioProfiler: Transformed class: java/net/URL
02-26 14:31:34.957 6113-6113/com.google.ar.core.examples.java.helloar W/zygote: Current dex file has more than one class in it. Calling RetransformClasses on this class might fail if no transformations are applied to it!
02-26 14:31:35.169 6113-6113/com.google.ar.core.examples.java.helloar V/StudioProfiler: Memory control stream started.
    StudioProfilers agent attached.
02-26 14:31:35.169 6113-6113/com.google.ar.core.examples.java.helloar I/Choreographer: Skipped 30 frames!  The application may be doing too much work on its main thread.
02-26 14:31:36.753 6113-6191/com.google.ar.core.examples.java.helloar V/StudioProfiler: Live memory tracking disabled.
02-26 14:31:36.754 6113-6191/com.google.ar.core.examples.java.helloar V/StudioProfiler: Live memory tracking enabled.
    JNIEnv not attached
02-26 14:31:36.766 6113-6191/com.google.ar.core.examples.java.helloar V/StudioProfiler: Loaded classes: 5321
02-26 14:31:36.844 6113-6191/com.google.ar.core.examples.java.helloar V/StudioProfiler: Tracking initialization took: 90004744ns
02-26 14:31:42.932 6113-6131/com.google.ar.core.examples.java.helloar W/native: analytics_logger.cc:189 Could not send event. Event will be dropped.
```

**Comment by tpsiaki** [comment]
Hi - it looks like you are running on an API25 version of the emulator.  Currently, on the emulator, ARCore is only supported in the API27 **Revision 4** builds.  Will you double check that you are running the correct emulator image?  (Note, you may need to go to Tools > SDK Manager > SDK Platforms, Check "Show Packages Details", then verify that **Revision 4** of Google APIs Intel x86 Atom System Image - API Level 27 (Oreo) is installed).

**Comment by inio** [comment]
@tpsiaki thanks for catching that.

**Comment by gurizilla** [comment]
Hey guys, I uninstalled all these previous version as you mentioned, but, when I try to create a AVM with the previously mentioned Android version:
![image](https://user-images.githubusercontent.com/1076839/36703663-74773f3a-1b3b-11e8-9bd5-8a9045dc2b6e.png)
There is this strange "null" target on AVD Manager:
![image](https://user-images.githubusercontent.com/1076839/36703678-90e4fd6a-1b3b-11e8-9fec-7d6801ecb4d7.png)
If I try to run the Virtual Device, I keep getting this:

![image](https://user-images.githubusercontent.com/1076839/36703711-b3f691ec-1b3b-11e8-8d98-ad898c7f99e9.png)
Could you please advise?
Thanks

**Comment by tpsiaki** [comment]
Are you running Android Studio 3.1?  It looks like you're running an earlier version of Android Studio (because your AVD has camera back = emulated, and the target is showing as null).

**Comment by gurizilla** [comment]
I'm on Android Studio 3.0.1.
I tried to find a newer version but I couldn't.
Also, quick start mentions "Install Android Studio version 3.0 or higher ".
Thanks!

**Comment by inio** [comment]
From https://developers.google.com/ar/develop/java/emulator:

> You'll also need [Android Studio 3.1 (Beta)](https://developer.android.com/studio/preview/index.html).

**Comment by tpsiaki** [comment]
the ARCore integration with the Android Emulator is only fully supported in Android Studio 3.1 or higher (which is currently in Beta).  See the [ARCore Emulator Documentation](https://devsite.googleplex.com/ar/develop/java/emulator) for details.

As a workaround, you may be able to edit the config.ini file for your AVD created in Android Studio 3.1 and replace `hw.camera.back: emulated` with `hw.camera.back: virtualscene`, (also make sure you're running emulator 27.1.10 or higher) then restart the emulator, but YMMV as the min fully supported version of Android Studio is 3.1

**Comment by jwmcglynn** [comment]
@gurizilla Did Android Studio 3.1 resolve your issue?

Looking at the debug output, it looks like you are hitting into the texture loading bug with the HelloAR Java example.  I provided a workaround for that here: https://github.com/google-ar/arcore-android-sdk/issues/48#issuecomment-370053162

**Comment by gurizilla** [comment]
Yes, it was solved.
But, it seems like the app is unable to find a surface:

E/native: android_data_source.cc:402 generic::deadline_exceeded: Timed out waiting for metadata. camera_id=MotionTrackingPrimary
E/native: android_cpu_consumer.cc:126 Consumer failed to dequeue Image from ImageReader. status=ImageReaderStatusErrorSpaceClass::AMEDIA_IMGREADER_NO_BUFFER_AVAILABLE: AImageReader_acquireLatestImage image_count=2

**Comment by inio** [comment]
Closing for inactivity.

**Comment by ArunkumarChandraSekar** [comment]
Hi Team., 

I would like to develop ARCore-Location based application using java in android studio.  After doing some research finally I got `https://github.com/appoly/ARCore-Location` this sample code and its working fine. This sample code's TargetSDKVerion 27. 
I would like to use the TargetSDKVerion 29. When I changed the version in my project. Its gets the following error. 

E/Filament: Panic
    in void *filament::CircularBuffer::alloc(size_t):127
    reason: couldn't allocate 6144 KiB of memory for the command buffer

For fix this error., needs to update the ARCore version. My Current ARCore Version **1.0.5** So I tried to update the based on the release notes. The Latest version is : 1.20.0 But I cannot get any samples codes for loation-based AR.  Please help me to overcome from this.


Thanks in Advance!
