### ISSUE TITLE
Weird crash related to AnalyticsClient

### ISSUE THREAD

**Issue by superuserdid** [google-ar/arcore-android-sdk#201]
Ran into a weird crash when using ARCore 1.0. Here is the stacktrace.

> 02-27 12:13:44.406 7443-7443/? E/ActivityThread: Activity com.company.android.company.activities.ar.cupcake.ARCupcakeActivity has leaked ServiceConnection adh@557ce39 that was originally bound here
                                                 android.app.ServiceConnectionLeaked: Activity com.company.android.company.activities.ar.cupcake.ARCupcakeActivity has leaked ServiceConnection adh@557ce39 that was originafolly bound here
                                                     at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1532)
                                                     at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1424)
                                                     at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1605)
                                                     at android.app.ContextImpl.bindService(ContextImpl.java:1557)
                                                     at android.content.ContextWrapper.bindService(ContextWrapper.java:684)
                                                     at com.google.ar.core.services.AnalyticsClient.<init>(PG:10)
                                                     at com.viro.core.RendererARCore.nativeOnARCoreInstalled(Native Method)
                                                     at com.viro.core.RendererARCore.onARCoreInstalled(RendererARCore.java:30)
                                                     at com.viro.core.ViroViewARCore.requestARCoreInstall(ViroViewARCore.java:464)
                                                     at com.viro.core.ViroViewARCore.onActivityResumed(ViroViewARCore.java:629)
                                                     at com.company.android.company.views.ar.ARCupcakeView.onActivityResume(ARCupcakeView.kt:350)
                                                     at com.company.android.company.activities.ar.cupcake.ARCupcakeActivity.onResume(ARCupcakeActivity.kt:280)

It is not easily reproducible, seems to happen randomly and it happens when navigating to my activity which uses ARCore.

**Comment by inio** [comment]
This looks like it could be a bug on our side.  Investigating.

**Comment by inio** [comment]
We've been unable to reproduce this.  If you have reliable repro steps, please let us know.
