### ISSUE TITLE
Samsung S7 SM-G930F - java.lang.RuntimeException: Setting up to draw planes: glError 1282

### ISSUE THREAD

**Issue by abbana** [google-ar/arcore-android-sdk#208]
Seems there could be an issue on my SAM running Hello-AR-Activity

Compiles, downloads AR, starts but fail to render looping the below indefinitely:

02-28 18:27:40.355 13383-13502/xxx E/HelloArActivity: Failed to read obj file
02-28 18:27:40.357 13383-13502/xxx E/HelloArActivity: Failed to read plane texture
02-28 18:27:41.615 13383-13502/xxx E/PlaneRenderer: Setting up to draw planes: glError 1282
02-28 18:27:41.616 13383-13502/xxx E/HelloArActivity: Exception on the OpenGL thread
                                                                              java.lang.RuntimeException: Setting up to draw planes: glError 1282
                                                                                  at xxx.rendering.ShaderUtil.checkGLError(ShaderUtil.java:73)
                                                                                  at xxx.rendering.PlaneRenderer.drawPlanes(PlaneRenderer.java:365)
                                                                                  at xxx.HelloArActivity.onDrawFrame(HelloArActivity.java:351)
                                                                                  at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1562)
                                                                                  at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1262)
02-28 18:27:41.641 13383-13502/xxx E/PlaneRenderer: Setting up to draw planes: glError 1282
02-28 18:27:41.641 13383-13502/xxx E/HelloArActivity: Exception on the OpenGL thread

Any idea?

**Comment by inio** [comment]
This looks a lot like the first two posts of #48.  Would you mind sprinkling checkGLError calls throughout PlaneRenderer.drawPlanes to help narrow down which call is failing?

**Comment by abbana** [comment]
@inio Please give me the exact steps and I ll try to give you what you need. Thanks.

**Comment by inio** [comment]
Lets start with updating the top of drawPlanes to have some extra checks like this:

https://pastebin.com/iS80Y5nB

**Comment by abbana** [comment]
@inio Thanks for that, but instead of try/error, may i know if this simple code has been tested in the lab before marking S7 SM-G930F  as a supported model? It seems to me an issue with the GL rendering on this particular device and if it is not working should be marked as non-supported and the tests/fix done on the lab for the next minor release. What do you think?

**Comment by inio** [comment]
Yes, we've tested Hello AR (Java/C/Unity/Unreal) on every device listed on our supported set.  We've only seen this issue reported by 3 users and haven't been able to reproduce it.

**Comment by abbana** [comment]
@inio Ok in which fund you want to paste that code?  public static void checkGLError(String tag, String label)?

**Comment by inio** [comment]
@abbana in drawPlanes, here's a diff: https://github.com/inio/arcore-android-sdk/commit/8c6d12f9b51ee5afef129c4bce1add93a5fba2e3
