### ISSUE TITLE
HelloAR ClassNotFoundException: HelloArActivity

### ISSUE THREAD

**Issue by zaher88abd** [google-ar/arcore-android-sdk#214]
I tried to run the demo but it doesn't work on those machines and I got this error:
`03-03 10:35:46.344 6103-6103/com.google.ar.core.examples.java.helloar E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                        Process: com.google.ar.core.examples.java.helloar, PID: 6103
                                                                                        java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.google.ar.core.examples.java.helloar/com.google.ar.core.examples.java.helloar.HelloArActivity}: java.lang.ClassNotFoundException: Didn't find class "com.google.ar.core.examples.java.helloar.HelloArActivity" on path: DexPathList[[zip file "/data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/base.apk", zip file "/data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_0_apk.apk", zip file "/data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_1_apk.apk", zip file "/data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_2_apk.apk", zip file "/data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_3_apk.apk", zip file "/data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_4_apk.apk", zip file "/data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_5_apk.apk", zip file "/data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_6_apk.apk", zip file "/data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_7_apk.apk", zip file "/data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_8_apk.apk", zip file "/data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/lib/x86, /data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/base.apk!/lib/x86, /data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_0_apk.apk!/lib/x86, /data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_1_apk.apk!/lib/x86, /data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_2_apk.apk!/lib/x86, /data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_3_apk.apk!/lib/x86, /data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_4_apk.apk!/lib/x86, /data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_5_apk.apk!/lib/x86, /data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_6_apk.apk!/lib/x86, /data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_7_apk.apk!/lib/x86, /data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_8_apk.apk!/lib/x86, /data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_9_apk.apk!/lib/x86, /system/lib, /vendor/lib]]
                                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2718)
                                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                                                                                            at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                            at android.os.Looper.loop(Looper.java:164)
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                                            at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
03-03 10:35:46.346 6103-6103/com.google.ar.core.examples.java.helloar E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.ar.core.examples.java.helloar.HelloArActivity" on path: DexPathList[[zip file "/data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/base.apk", zip file "/data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_0_apk.apk", zip file "/data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_1_apk.apk", zip file "/data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_2_apk.apk", zip file "/data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_3_apk.apk", zip file "/data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_4_apk.apk", zip file "/data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_5_apk.apk", zip file "/data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_6_apk.apk", zip file "/data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_7_apk.apk", zip file "/data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_8_apk.apk", zip file "/data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/lib/x86, /data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/base.apk!/lib/x86, /data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_0_apk.apk!/lib/x86, /data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_1_apk.apk!/lib/x86, /data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_2_apk.apk!/lib/x86, /data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_3_apk.apk!/lib/x86, /data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_4_apk.apk!/lib/x86, /data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_5_apk.apk!/lib/x86, /data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_6_apk.apk!/lib/x86, /data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_7_apk.apk!/lib/x86, /data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_8_apk.apk!/lib/x86, /data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_9_apk.apk!/lib/x86, /system/lib, /vendor/lib]]
                                                                                            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
                                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                            at android.app.Instrumentation.newActivity(Instrumentation.java:1173)
                                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2708)
                                                                                            	... 9 more
                                                                                        	Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/app/AppCompatActivity;
                                                                                            at java.lang.VMClassLoader.findLoadedClass(Native Method)
                                                                                            at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
                                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
                                                                                            		... 12 more
03-03 10:35:46.347 6103-6103/com.google.ar.core.examples.java.helloar E/AndroidRuntime: 	Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.app.AppCompatActivity" on path: DexPathList[[zip file "/data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/base.apk", zip file "/data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_0_apk.apk", zip file "/data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_1_apk.apk", zip file "/data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_2_apk.apk", zip file "/data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_3_apk.apk", zip file "/data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_4_apk.apk", zip file "/data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_5_apk.apk", zip file "/data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_6_apk.apk", zip file "/data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_7_apk.apk", zip file "/data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_8_apk.apk", zip file "/data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/lib/x86, /data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/base.apk!/lib/x86, /data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_0_apk.apk!/lib/x86, /data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_1_apk.apk!/lib/x86, /data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_2_apk.apk!/lib/x86, /data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_3_apk.apk!/lib/x86, /data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_4_apk.apk!/lib/x86, /data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_5_apk.apk!/lib/x86, /data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_6_apk.apk!/lib/x86, /data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_7_apk.apk!/lib/x86, /data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_8_apk.apk!/lib/x86, /data/app/com.google.ar.core.examples.java.helloar-Pv8OO8e40JR3Hz60e6NEoQ==/split_lib_slice_9_apk.apk!/lib/x86, /system/lib, /vendor/lib]]
                                                                                            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
                                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                            		... 15 more
`

**Comment by inio** [comment]
> java.lang.ClassNotFoundException: Didn't find class "com.google.ar.core.examples.java.helloar.HelloArActivity"

Are you using the unmodified HelloAR sample code/project?  That error indicates your AndroidManifest.xml references a class from the sample code that for some reason isn't getting included in the build.

If you haven't changed the build or code at all, try [disabling instant run](https://developer.android.com/studio/run/index.html#disable-ir).  I don't think that would solve this problem but it's the lowest-effort thing to try.

**Comment by kai-dream** [comment]
I am thinking another possibility is you might have obfuscator. If so, you can exclude all classes from com.google.*.

**Comment by inio** [comment]
Closing due to inactivity.

**Comment by SheikhZayed** [comment]
i have the same issue in my oneplus6.
i dont have instant run enabled..still fails
