### ISSUE TITLE
Searching for sufaces forever

### ISSUE THREAD

**Issue by HndsmJohn** [google-ar/arcore-android-sdk#245]
Hello,
I'm trying to launch the hello_ar_java demo on a virtual Pixel 2 (Oreo 8.1) and I encountered 2 issues :
- I had to change the texture file of andy in order to have the app launch (it was crashing on launch due to an texture loading error)
- Once i did that, the app launched but didn't detect any surfaces even when i was approaching a flat surface.

I use the Android Studio 3.1 beta, Android emulator version 27.1.12. Basically i made sure to follow every step in the Get Started section.
Do you have any idea what the problem could be ?
Thank you in advance for your answer

**Comment by jwmcglynn** [comment]
@TheHandsomeJohn The texture loading error is likely #231, which will be fixed in an upcoming release.

For detecting a surface, ARCore's tracking requires some parallax in order to find enough tracking points to detect a plane.  I typically do a combination of some side-to-side movements and rotations, such as strafing around the rug on the floor in order to find the plane.  If that doesn't work, can you post a video?

**Comment by TheHandsomeJohn** [comment]
Indeed, i just had to move around in the virtual environment to detect some surfaces. 
Any idea when the fix for the texture bug might be released ?

**Comment by jwmcglynn** [comment]
The real fix requires a change to the emulator system image.  I don't have an ETA for that yet, but I can update you when that's available.

However, there is a workaround.  We'll be updating the HelloAR Java sample to include the workaround in the next release, but before that happens you can apply the workaround yourself by following this comment: https://github.com/google-ar/arcore-android-sdk/issues/231#issuecomment-372000803

If you're still having issues that aren't fixed by applying the workaround let me know.

**Comment by HndsmJohn** [comment]
I still got some issues even with workaround applied.
On application launch, i got an error saying the obj file couldn't be read. So i can't place the andy model on the plane on the first place. When trying to do so i got these error messages : 

E/ObjectRenderer: After draw: glError 1282
E/HelloArActivity: Exception on the OpenGL thread
                   java.lang.RuntimeException: After draw: glError 1282
                       at com.google.ar.core.examples.java.helloar.rendering.ShaderUtil.checkGLError(ShaderUtil.java:73)
                       at com.google.ar.core.examples.java.helloar.rendering.ObjectRenderer.draw(ObjectRenderer.java:356)
                       at com.google.ar.core.examples.java.helloar.HelloArActivity.onDrawFrame(HelloArActivity.java:379)
                       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1571)
                       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)

Also, I did a run with Hello_ar_c and it works perfectly.

**Comment by ryantancabel** [comment]
Hi there,

I have had similar issues regarding "searching for surfaces".  Upon finding out about the ARCore 1.1 update, I attempted to run it, on my emulated Pixel, but got an error message that I needed to update ARCore on the device. 

Would v1.1 address the aforementioned issue, and would API 27r5 update the device 's ARCore.

Android Studio 3.1/Emulated Google Pixel/ API 27r4 / SDK Build 28

**Comment by inio** [comment]
Closing for inactivity.
