### ISSUE TITLE
IllegalArgumentException SM-G950F

### ISSUE THREAD

**Issue by Aiuspaktyn** [google-ar/arcore-android-sdk#25]
Crash

[com.aiuspaktyn.arcoregr.txt](https://github.com/google-ar/arcore-android-sdk/files/1273338/com.aiuspaktyn.arcoregr.txt)

**Comment by inio** [comment]
This is an interesting crash.  How reproducible is it?

**Comment by inio** [comment]
We think we have identified reproduction steps and a fix, which should be included in the next release.

Were you running an app from Android Studio with the device's screen locked?  For now, make sure to unlock your screen before launching your app.  Alternately, enabling "Stay Awake" in developer options will prevent the device from sleeping while connected to a power source, likely preventing this issue from occurring.

**Comment by Aiuspaktyn** [comment]
Sorry I can't reproduce, It's a Crashlytics report

**Comment by AirrWang** [comment]
据我所知  目前控件并不支持SM-G950F  可以用S8或者谷歌手机来测试

**Comment by gopal-fp** [comment]
Got the same with S8+ G955F with sample helloar sample

Process: com.google.ar.core.examples.java.helloar, PID: 28784
java.lang.IllegalArgumentException: width must be greater than zero
at com.google.ar.core.Session.setDisplayGeometry(Session.java:631)
at com.google.ar.core.Session$3.onDisplayChanged(Session.java:863)
at android.hardware.display.DisplayManagerGlobal$DisplayListenerDelegate.handleMessage(DisplayManagerGlobal.java:939)
 at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154) 
at android.app.ActivityThread.main(ActivityThread.java:6776)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)`

**Comment by inio** [comment]
Given the substantial architectural changes between Developer Preview 1 and Developer Preview 2, I'm going to close this as being likely obsolete.  If you see this again please re-open!
