### ISSUE TITLE
Crash at launch

### ISSUE THREAD

**Issue by chandraveerr** [google-ar/arcore-android-sdk#26]
09-05 12:33:35.399 16496-16496/? I/zygote64: Late-enabling -Xcheck:jni
09-05 12:33:35.465 16496-16504/? I/zygote64: Debugger is no longer active
09-05 12:33:35.614 16496-16496/? I/TangoClientLibLoader: Pure Java path, not loading libtango_client_api.so at all.
09-05 12:33:35.615 16496-16496/? E/Tango: Java version of Tango Service not found, falling back to tangoservice_d.
09-05 12:33:35.615 16496-16496/? E/zygote64: No implementation found for int com.google.atap.tango.TangoJNINative.Initialize(android.content.Context) (tried Java_com_google_atap_tango_TangoJNINative_Initialize and Java_com_google_atap_tango_TangoJNINative_Initialize__Landroid_content_Context_2)
09-05 12:33:35.616 16496-16496/? D/AndroidRuntime: Shutting down VM
09-05 12:33:35.619 16496-16496/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.google.ar.core.examples.java.helloar, PID: 16496
                                                   java.lang.UnsatisfiedLinkError: No implementation found for int com.google.atap.tango.TangoJNINative.Initialize(android.content.Context) (tried Java_com_google_atap_tango_TangoJNINative_Initialize and Java_com_google_atap_tango_TangoJNINative_Initialize__Landroid_content_Context_2)
                                                       at com.google.atap.tango.TangoJNINative.Initialize(Native Method)
                                                       at com.google.atap.tangoservice.Tango.<init>(Tango.java:385)
                                                       at com.google.ar.core.TangoWrapper.createInstance(TangoWrapper.java:32)
                                                       at com.google.ar.core.Session.bindTangoService(Session.java:425)
                                                       at com.google.ar.core.Session.resume(Session.java:153)
                                                       at com.google.ar.core.examples.java.helloar.HelloArActivity.onResume(HelloArActivity.java:136)
                                                       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1354)
                                                       at android.app.Activity.performResume(Activity.java:7079)
                                                       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3620)
                                                       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3685)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2898)
                                                       at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                                                       at android.os.Handler.dispatchMessage(Handler.java:105)
                                                       at android.os.Looper.loop(Looper.java:164)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by chandraveerr** [comment]
I as using Pixel to test the sample

**Comment by nathanmartz** [comment]
You need to install the arcore-preview.apk as described in the instructions.

**Comment by StayZeal** [comment]
My device doesn't support.
https://developers.google.com/ar/discover/#supported_devices
