### ISSUE TITLE
Pixel 2 Emulator not working with arcore-android-sdk-v1.1.0

### ISSUE THREAD

**Issue by Banjorattler** [google-ar/arcore-android-sdk#274]
When I run the project the phone comes up with a message box that says "This application requires the latest version of ARCore." When I tap continue the app displays a new message box that says "HelloAR Java has stopped"

Running Android Studio 3.1 dated at March 26, 2018
Emulator - Pixel 2 API 27 (Android 8.1.0, API 27)

The (arcore-android-sdk-v1.0.0) works with the emulator, but the (arcore-android-sdk-v1.1.0) does not.

**Comment by inio** [comment]
Interesting.  We'll look into it.

**Comment by Banjorattler** [comment]
I can provide more information if needed.

**Comment by inio** [comment]
Unfortunately 1.1 is not supported on the emulator just yet.  The emulator doesn't have access to the Play Store, so it has no way to download a newer version.  We'll release a new OS image shortly that adds 1.1 support.

**Comment by newAndroidDev** [comment]
Name: Pixel_2_API_27_arcore

CPU/ABI: Google APIs Intel Atom (x86)

Path: C:\Users\A003833\.android\avd\Pixel_2_API_27_arcore.avd

Target: google_apis [Google APIs] (API level 27)

Skin: pixel_2

SD Card: 100M

hw.dPad: no

hw.lcd.height: 1920

runtime.network.speed: full

hw.accelerometer: yes

hw.device.name: pixel_2

vm.heapSize: 256

skin.dynamic: yes

hw.device.manufacturer: Google

hw.lcd.width: 1080

hw.gps: yes

hw.initialOrientation: Portrait

image.androidVersion.api: 27

hw.audioInput: yes

image.sysdir.1: system-images\android-27\google_apis\x86\

tag.id: google_apis

showDeviceFrame: yes

hw.camera.back: virtualscene

hw.mainKeys: no

AvdId: Pixel_2_API_27_arcore

hw.camera.front: emulated

hw.lcd.density: 420

avd.ini.displayname: Pixel 2 API 27 arcore

hw.arc: false

hw.gpu.mode: auto

hw.device.hash2: MD5:bc5032b2a871da511332401af3ac6bb0

hw.ramSize: 1536

hw.trackBall: no

PlayStore.enabled: false

fastboot.forceColdBoot: no

hw.battery: yes

hw.cpu.ncore: 2

hw.sdCard: yes

tag.display: Google APIs

runtime.network.latency: none

hw.keyboard: yes

hw.sensors.proximity: yes

disk.dataPartition.size: 800M

hw.sensors.orientation: yes

avd.ini.encoding: UTF-8

hw.gpu.enabled: yes



**this is the error i am getting on logcat**
**Play Store install service could not be bound.**

**Comment by yuzhimin999** [comment]
Hi
I downloaded the latest AR core and installed it on the Pixel 2 Emulator.
I ran HelloAR Java and Crash occurred
Log info：
04-09 16:04:56.993 3093-3093/com.google.ar.core.examples.java.helloar I/third_party/arcore/ar/core/android/sdk/session_create.cc: Entering ArSession_create
04-09 16:04:56.997 3093-3093/com.google.ar.core.examples.java.helloar E/NativeLibraryLoader: version_check not found or not implemented. 
    **java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.google.ar.core-H3NMGHnUACRBdVwNW7azuA==/base.apk"],nativeLibraryDirectories=[/data/app/com.google.ar.core-H3NMGHnUACRBdVwNW7azuA==/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libversion_check.so"**
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1657)
        at com.google.vr.dynamite.NativeLibraryLoader.checkVersion(PG:12)
        at aje.onTransact(PG:13)
        at android.os.Binder.transact(Binder.java:627)
        at com.google.android.aidl.BaseProxy.transactAndReadException(BaseProxy.java:45)
        at com.google.vr.dynamite.client.INativeLibraryLoader$Stub$Proxy.checkVersion(INativeLibraryLoader.java:89)
        at com.google.vr.dynamite.client.DynamiteClient.checkVersion(DynamiteClient.java:46)
        at com.google.ar.core.Session.nativeCreateSession(Native Method)
        at com.google.ar.core.Session.<init>(Session.java:110)
        at com.google.ar.core.examples.java.helloar.HelloArActivity.onResume(HelloArActivity.java:134)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1355)
        at android.app.Activity.performResume(Activity.java:7117)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3556)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3621)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2862)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
04-09 16:04:56.997 3093-3093/com.google.ar.core.examples.java.helloar I/third_party/arcore/ar/core/android/sdk/session_create.cc: ARCore Version: SDK build name: 1.1
04-09 16:04:56.997 3093-3093/com.google.ar.core.examples.java.helloar W/third_party/arcore/ar/core/android/sdk/session_create.cc: LoadDynamite returning AR_ERROR_FATAL.
**04-09 16:04:57.009 3093-3093/com.google.ar.core.examples.java.helloar E/HelloArActivity: Exception creating session**
    com.google.ar.core.exceptions.FatalException
        at com.google.ar.core.Session.throwExceptionFromArStatus(Session.java:349)
        at com.google.ar.core.Session.nativeCreateSession(Native Method)
        at com.google.ar.core.Session.<init>(Session.java:110)
        at com.google.ar.core.examples.java.helloar.HelloArActivity.onResume(HelloArActivity.java:134)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1355)
        at android.app.Activity.performResume(Activity.java:7117)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3556)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3621)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2862)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
@inio

**Comment by inio** [comment]
@yuzhimin999 The emulator requires a custom x86 of ARCore.  Play Store versions won't run on it.

**Comment by anoop4real** [comment]
I am also facing the issue, is this fixed?

**Comment by inio** [comment]
We're working on this.  I'll update the bug as soon as we've figured what's possible.

**Comment by shreyone** [comment]
Ran into the same thing, you can switch to 1.0.0 in the dependencies.
There might be some other features like lighting that might need some tweaking


>>implementation 'com.google.ar:core:1.0.0'

**Comment by anoop4real** [comment]
Yeah finally I have to do that, I had to comment  

 //frame.getLightEstimate().getColorCorrection(colorCorrectionRgba, 0); in HelloArActivity.java

**Comment by inio** [comment]
The x86 build of ARCore has just been added to the [1.1 release files](https://github.com/google-ar/arcore-android-sdk/releases/tag/v1.1.0).  Installing this into the emulator will result in apps built against the 1.1 SDK working in the emulator.
