### ISSUE TITLE
Crash on  Xperia XZ Premium Android 7.1

### ISSUE THREAD

**Issue by yiyiyaya0917** [google-ar/arcore-android-sdk#278]
Hi, 
App crash on  Xperia XZ Premium with following info, seems related with AR core, could any one can have a look?
![crash](https://user-images.githubusercontent.com/37999859/38190167-a89318aa-3695-11e8-81b5-e3d491fa2fad.jpg)
[logcat.txt](https://github.com/google-ar/arcore-android-sdk/files/1867637/logcat.txt)
Thanks,
Crystal

**Comment by inio** [comment]
That is *very* odd.  How are you building ARCore into your application?  If you're building ARCore separately into a library and then linking that library into your app, you'll need to manually propagate the proguard.txt file from our AAR to your final build.

**Comment by Xanvial** [comment]
Hi, I also encounter this issue on Google pre-launch report of our application. Also only happen on XZ Premium device.
```
java.lang.NoSuchMethodError: No static method writeStrongBinder(Landroid/os/Parcel;Landroid/os/IInterface;)V in class Lcom/google/android/aidl/Codecs; or its super classes (declaration of 'com.google.android.aidl.Codecs' appears in /data/app/com.google.android.apps.mtaas.crawler-1/base.apk)
 at com.google.android.play.core.install.protocol.IInstallService$Stub$Proxy.requestInfo(IInstallService.java:136)
 at com.google.ar.core.InstallServiceImpl$2.run(InstallServiceImpl.java:147)
 at com.google.ar.core.InstallServiceImpl.onConnected(InstallServiceImpl.java:377)
 at com.google.ar.core.InstallServiceImpl.access$000(InstallServiceImpl.java:31)
 at com.google.ar.core.InstallServiceImpl.access$100(InstallServiceImpl.java:31)
 at com.google.ar.core.InstallServiceImpl.access$500(InstallServiceImpl.java:31)
 at com.google.ar.core.InstallServiceImpl.access$600(InstallServiceImpl.java:31)
 at com.google.ar.core.InstallServiceImpl$1.onServiceConnected(InstallServiceImpl.java:90)
 at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1474)
 at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1502)
 at android.os.Handler.handleCallback(Handler.java:751)
 at android.os.Handler.dispatchMessage(Handler.java:95)
 at android.os.Looper.loop(Looper.java:241)
 at android.app.ActivityThread.main(ActivityThread.java:6281)
 at java.lang.reflect.Method.invoke(Method.java)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by inio** [comment]
@Xanvial thanks for the report and context (and hopefully easy repro).  That should help track this down.

**Comment by yiyiyaya0917** [comment]
We build ARCore separately into a library and then linking that library into our app, we don't use the proguard.txt file from AAR(ARCORE), also we don't proguard google's AR core(AR core relative namespace com.google.**).

**Comment by inio** [comment]
@yiyiyaya0917 If you proguard your final app, everything built into it will get proguarded.  However, since this only shows up on one device I suspect that's not the issue.  Sorry, we haven't had time to dig any deeper on this one yet - hopefully this week.

**Comment by inio** [comment]
At this point I suspect this is caused by flawed Proguarding of your app.  I was unable to reproduce this failure.

Sample AR-Optional app:
https://github.com/inio/arcore-android-sdk/tree/ar_optional/samples/hello_ar_java

Screenshot from pre-launch report for XZ Premium:
![xperiaxzpremium](https://user-images.githubusercontent.com/458571/38579115-e1f2d31c-3cba-11e8-9133-02436035c47c.png)

**Comment by yiyiyaya0917** [comment]
Hi,
Seems the issue is fixed now, and no more crash on Song device.
Thanks for your suggestion.
