### ISSUE TITLE
Samsung Galaxy Note 8 SC-01K terminal of Japan can't run HelloAR example

### ISSUE THREAD

**Issue by netcafeohashi** [google-ar/arcore-android-sdk#292]
I’m trying to run the helloAR example for AR core on my Galaxy Note 8 but every time I open the app on my phone, I see a screen with a message “This device does not support AR” and app closed.
My device is Samsung Galaxy Note 8 SC-01K from Japanese Docomo devices.

I'm using Unity 2017.3.0f2.

**Comment by inio** [comment]
I see SM-SC01K listed in the supported device list, so this is definitely incorrect behavior.

1. Could you please let us know what build fingerprint your device reports?  `adb shell getprop ro.build.fingerprint` should display it.
2. If you open http://play.google.com/store/apps/details?id=com.google.ar.core on the device, do you see any sort of error message about the app not being supported on your device?
3. To save a round trip, capturing an logcat dump from app launch to the error displaying is the next thing we'd ask for if it looks like the fingerprint *should* be supported.

**Comment by inio** [comment]
Also, in the future Unity issues should be posted to the [Unity issues board](https://github.com/google-ar/arcore-unity-sdk/issues/).  This one doesn't have anything really do to with Unity as far as I can tell so happy to handle it here.

**Comment by netcafeohashi** [comment]
My English isn't so good so, but I will do my best to tell you.
also, I tried running HelloAR Core.java.

1. When you execute the command, the following will be displayed
`samsung/SC-01K/SC-01K:7.1.1/NMF26X/SC01KOMS1ARB1:`

2. I did not receive an error message and I installed it.

3. This is the log displayed when I run the application

```
04-07 20:54:27.853 17123-17123/com.google.ar.core.examples.java.helloar E/Zygote: v2
04-07 20:54:27.853 17123-17123/com.google.ar.core.examples.java.helloar I/libpersona: KNOX_SDCARD checking this for 10331
04-07 20:54:27.853 17123-17123/com.google.ar.core.examples.java.helloar I/libpersona: KNOX_SDCARD not a persona
04-07 20:54:27.854 17123-17123/com.google.ar.core.examples.java.helloar E/Zygote: accessInfo : 0
04-07 20:54:27.855 17123-17123/com.google.ar.core.examples.java.helloar W/SELinux: SELinux selinux_android_compute_policy_index : Policy Index[2],  Con:u:r:zygote:s0 RAM:SEPF_SECMOBILE_7.1.1_0004, [-1 -1 -1 -1 0 1]
04-07 20:54:27.855 17123-17123/com.google.ar.core.examples.java.helloar I/SELinux: SELinux: seapp_context_lookup: seinfo=untrusted, level=s0:c512,c768, pkgname=com.google.ar.core.examples.java.helloar 
04-07 20:54:27.861 17123-17123/com.google.ar.core.examples.java.helloar I/art: Late-enabling -Xcheck:jni
04-07 20:54:27.900 17123-17123/com.google.ar.core.examples.java.helloar W/ActivityThread: Application com.google.ar.core.examples.java.helloar is waiting for the debugger on port 8100...
04-07 20:54:27.901 17123-17123/com.google.ar.core.examples.java.helloar I/System.out: Sending WAIT chunk
04-07 20:54:27.914 17123-17131/com.google.ar.core.examples.java.helloar I/art: Debugger is no longer active
04-07 20:54:27.914 17123-17131/com.google.ar.core.examples.java.helloar I/art: Starting a blocking GC Instrumentation
04-07 20:54:30.207 17123-17131/com.google.ar.core.examples.java.helloar I/art: Debugger is active
04-07 20:54:30.303 17123-17123/com.google.ar.core.examples.java.helloar I/System.out: Debugger has connected
04-07 20:54:30.303 17123-17123/com.google.ar.core.examples.java.helloar I/System.out: waiting for debugger to settle...
04-07 20:54:30.504 17123-17123/com.google.ar.core.examples.java.helloar I/System.out: waiting for debugger to settle...
04-07 20:54:30.704 17123-17123/com.google.ar.core.examples.java.helloar I/System.out: waiting for debugger to settle...
04-07 20:54:30.904 17123-17123/com.google.ar.core.examples.java.helloar I/System.out: waiting for debugger to settle...
04-07 20:54:31.105 17123-17123/com.google.ar.core.examples.java.helloar I/System.out: waiting for debugger to settle...
04-07 20:54:31.306 17123-17123/com.google.ar.core.examples.java.helloar I/System.out: waiting for debugger to settle...
04-07 20:54:31.507 17123-17123/com.google.ar.core.examples.java.helloar I/System.out: waiting for debugger to settle...
04-07 20:54:31.707 17123-17123/com.google.ar.core.examples.java.helloar I/System.out: waiting for debugger to settle...
04-07 20:54:31.908 17123-17123/com.google.ar.core.examples.java.helloar I/System.out: debugger has settled (1410)
04-07 20:54:32.034 17123-17123/com.google.ar.core.examples.java.helloar I/InstantRun: starting instant run server: is main process
04-07 20:54:32.086 17123-17123/com.google.ar.core.examples.java.helloar V/ActivityThread: performLaunchActivity: mActivityCurrentConfig={0 1.0 themeSeq = 0 showBtnBg = 0 440mcc10mnc [ja_JP] ldltr sw411dp w411dp h773dp 420dpi nrml long port ?dc finger -keyb/v/h -nav/h mkbd/h desktop/d s.260}
04-07 20:54:32.099 17123-17123/com.google.ar.core.examples.java.helloar W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
04-07 20:54:32.192 17123-17123/com.google.ar.core.examples.java.helloar I/native: session_create.cc:71 ArSession_create with info: Entering
04-07 20:54:32.230 17123-17123/com.google.ar.core.examples.java.helloar D/ApplicationLoaders: ignored Vulkan layer search path /data/app/com.google.ar.core-2/lib/arm64:/data/app/com.google.ar.core-2/base.apk!/lib/arm64-v8a for namespace 0x7f88bec0f0
04-07 20:54:32.248 17123-17123/com.google.ar.core.examples.java.helloar W/native: commandlineflags.cc:1503 Ignoring RegisterValidateFunction() for flag pointer 0x7f69b5a1a8: no flag found at that address
04-07 20:54:32.248 17123-17123/com.google.ar.core.examples.java.helloar I/native: version_check.cc:23 ARCore Version: APK version:1.1.180312063
04-07 20:54:32.248 17123-17123/com.google.ar.core.examples.java.helloar I/native: version_check.cc:24 ARCore Version: emulated SDK version:1.0.0
04-07 20:54:32.249 17123-17123/com.google.ar.core.examples.java.helloar I/native: session_create.cc:37 LoadDynamite with info: Dynamite load ok.
04-07 20:54:32.281 17123-17123/com.google.ar.core.examples.java.helloar W/native: commandlineflags.cc:1503 Ignoring RegisterValidateFunction() for flag pointer 0x7f69ad6068: no flag found at that address
04-07 20:54:32.286 17123-17123/com.google.ar.core.examples.java.helloar I/native: session_create_implementation.cc:527 Entering ArSession_createImplementation. ARCore SDK version: [1.0.0].
04-07 20:54:32.435 17123-17123/com.google.ar.core.examples.java.helloar E/native: session_create_implementation.cc:219 Device is not supported.
04-07 20:54:32.435 17123-17123/com.google.ar.core.examples.java.helloar E/native: session_create_implementation.cc:546 Failed to create calibration provider
04-07 20:54:32.435 17123-17123/com.google.ar.core.examples.java.helloar W/native: session_create_implementation.cc:547 ArSession_createImplementation returning ArStatusErrorSpace::AR_UNAVAILABLE_DEVICE_NOT_COMPATIBLE: .
04-07 20:54:32.456 17123-17123/com.google.ar.core.examples.java.helloar D/TextView: setTypeface with style : 0
04-07 20:54:32.462 17123-17123/com.google.ar.core.examples.java.helloar E/HelloArActivity: Exception creating session
                                                                                           com.google.ar.core.exceptions.UnavailableDeviceNotCompatibleException
                                                                                               at com.google.ar.core.Session.throwExceptionFromArStatus(Session.java:361)
                                                                                               at com.google.ar.core.Session.nativeCreateSession(Native Method)
                                                                                               at com.google.ar.core.Session.<init>(Session.java:100)
                                                                                               at com.google.ar.core.examples.java.helloar.HelloArActivity.onResume(HelloArActivity.java:155)
                                                                                               at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1277)
                                                                                               at android.app.Activity.performResume(Activity.java:7140)
                                                                                               at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3850)
                                                                                               at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3914)
                                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3070)
                                                                                               at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1659)
                                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                               at android.os.Looper.loop(Looper.java:154)
                                                                                               at android.app.ActivityThread.main(ActivityThread.java:6823)
                                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
                                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)
04-07 20:54:32.477 17123-17123/com.google.ar.core.examples.java.helloar D/ViewRootImpl@1a4186e[HelloArActivity]: ThreadedRenderer.create() translucent=false
04-07 20:54:32.486 17123-17123/com.google.ar.core.examples.java.helloar D/InputTransport: Input channel constructed: fd=88
04-07 20:54:32.486 17123-17123/com.google.ar.core.examples.java.helloar D/ViewRootImpl@1a4186e[HelloArActivity]: setView = DecorView@878479c[HelloArActivity] touchMode=true
04-07 20:54:32.490 17123-17123/com.google.ar.core.examples.java.helloar D/ViewRootImpl@1a4186e[HelloArActivity]: dispatchAttachedToWindow
04-07 20:54:32.534 17123-17123/com.google.ar.core.examples.java.helloar V/Surface: sf_framedrop debug : 0x4f4c, game : false, logging : 0
04-07 20:54:32.541 17123-17123/com.google.ar.core.examples.java.helloar D/ViewRootImpl@1a4186e[HelloArActivity]: Relayout returned: oldFrame=[0,0][0,0] newFrame=[0,0][1080,2220] result=0x27 surface={isValid=true 547242164736} surfaceGenerationChanged=true
04-07 20:54:32.542 17123-17123/com.google.ar.core.examples.java.helloar D/ViewRootImpl@1a4186e[HelloArActivity]: mHardwareRenderer.initialize() mSurface={isValid=true 547242164736} hwInitialized=true
04-07 20:54:32.552 17123-17763/com.google.ar.core.examples.java.helloar D/libEGL: loaded /vendor/lib64/egl/libEGL_adreno.so
04-07 20:54:32.570 17123-17763/com.google.ar.core.examples.java.helloar D/libEGL: loaded /vendor/lib64/egl/libGLESv1_CM_adreno.so
04-07 20:54:32.575 17123-17123/com.google.ar.core.examples.java.helloar V/Surface: sf_framedrop debug : 0x4f4c, game : false, logging : 0
04-07 20:54:32.576 17123-17123/com.google.ar.core.examples.java.helloar D/SurfaceView: Relayout returned: oldFrame=[0,0][0,0] newFrame=[0,63][1080,2094] result=0x7 surface={Surface(name=null)/@0xc54f959 isValid=true 547446194176}
04-07 20:54:32.580 17123-17763/com.google.ar.core.examples.java.helloar D/libEGL: loaded /vendor/lib64/egl/libGLESv2_adreno.so
04-07 20:54:32.593 17123-17763/com.google.ar.core.examples.java.helloar I/Adreno: QUALCOMM build                   : 33f9106, Ia8660bee96
                                                                                  Build Date                       : 08/09/17
                                                                                  OpenGL ES Shader Compiler Version: XE031.14.00.01
                                                                                  Local Branch                     : 
                                                                                  Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.UM.5.7.C2.07.01.01.292.070
                                                                                  Remote Branch                    : NONE
                                                                                  Reconstruct Branch               : NOTHING
04-07 20:54:32.594 17123-17763/com.google.ar.core.examples.java.helloar I/Adreno: PFP: 0x005ff104, ME: 0x005ff063
04-07 20:54:32.596 17123-17763/com.google.ar.core.examples.java.helloar I/OpenGLRenderer: Initialized EGL, version 1.4
04-07 20:54:32.596 17123-17763/com.google.ar.core.examples.java.helloar D/OpenGLRenderer: Swap behavior 1
04-07 20:54:32.692 17123-17129/com.google.ar.core.examples.java.helloar I/art: Do partial code cache collection, code=29KB, data=25KB
04-07 20:54:32.692 17123-17129/com.google.ar.core.examples.java.helloar I/art: After code cache collection, code=29KB, data=25KB
04-07 20:54:32.692 17123-17129/com.google.ar.core.examples.java.helloar I/art: Increasing code cache capacity to 128KB
04-07 20:54:33.143 17123-17129/com.google.ar.core.examples.java.helloar I/art: Do partial code cache collection, code=61KB, data=45KB
04-07 20:54:33.143 17123-17129/com.google.ar.core.examples.java.helloar I/art: After code cache collection, code=57KB, data=42KB
04-07 20:54:33.143 17123-17129/com.google.ar.core.examples.java.helloar I/art: Increasing code cache capacity to 256KB
04-07 20:54:33.293 17123-17123/com.google.ar.core.examples.java.helloar I/Choreographer: Skipped 47 frames!  The application may be doing too much work on its main thread.
04-07 20:54:33.303 17123-17123/com.google.ar.core.examples.java.helloar D/ViewRootImpl@1a4186e[HelloArActivity]: Relayout returned: oldFrame=[0,0][1080,2220] newFrame=[0,0][1080,2220] result=0x1 surface={isValid=true 547242164736} surfaceGenerationChanged=false
04-07 20:54:33.310 17123-17123/com.google.ar.core.examples.java.helloar V/Surface: sf_framedrop debug : 0x4f4c, game : false, logging : 0
04-07 20:54:33.311 17123-17123/com.google.ar.core.examples.java.helloar D/SurfaceView: Relayout returned: oldFrame=[0,63][1080,2094] newFrame=[0,63][1080,2094] result=0x1 surface={Surface(name=null)/@0xc54f959 isValid=true 547446197760}
04-07 20:54:33.367 17123-17123/com.google.ar.core.examples.java.helloar D/ViewRootImpl@1a4186e[HelloArActivity]: MSG_RESIZED_REPORT: frame=Rect(0, 0 - 1080, 2220) ci=Rect(0, 63 - 0, 126) vi=Rect(0, 63 - 0, 126) or=1
04-07 20:54:33.367 17123-17123/com.google.ar.core.examples.java.helloar D/ViewRootImpl@1a4186e[HelloArActivity]: MSG_WINDOW_FOCUS_CHANGED 1
04-07 20:54:33.368 17123-17123/com.google.ar.core.examples.java.helloar D/ViewRootImpl@1a4186e[HelloArActivity]: mHardwareRenderer.initializeIfNeeded()#2 mSurface={isValid=true 547242164736}
04-07 20:54:33.369 17123-17123/com.google.ar.core.examples.java.helloar V/InputMethodManager: Starting input: tba=android.view.inputmethod.EditorInfo@8f91c3b nm : com.google.ar.core.examples.java.helloar ic=null
04-07 20:54:33.369 17123-17123/com.google.ar.core.examples.java.helloar I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
04-07 20:54:33.379 17123-17137/com.google.ar.core.examples.java.helloar D/InputTransport: Input channel constructed: fd=91
04-07 20:54:33.408 17123-17123/com.google.ar.core.examples.java.helloar D/ViewRootImpl@1a4186e[HelloArActivity]: Relayout returned: oldFrame=[0,0][1080,2220] newFrame=[0,0][1080,2220] result=0x1 surface={isValid=true 547242164736} surfaceGenerationChanged=false
04-07 20:54:33.433 17123-17123/com.google.ar.core.examples.java.helloar V/Surface: sf_framedrop debug : 0x4f4c, game : false, logging : 0
04-07 20:54:33.434 17123-17123/com.google.ar.core.examples.java.helloar D/SurfaceView: Relayout returned: oldFrame=[0,63][1080,2094] newFrame=[0,0][1080,2220] result=0x21 surface={Surface(name=null)/@0xc54f959 isValid=true 547446201344}
04-07 20:54:33.490 17123-17123/com.google.ar.core.examples.java.helloar V/InputMethodManager: Starting input: tba=android.view.inputmethod.EditorInfo@8af7196 nm : com.google.ar.core.examples.java.helloar ic=null
04-07 21:10:48.650 17123-17123/com.google.ar.core.examples.java.helloar D/ViewRootImpl@1a4186e[HelloArActivity]: ViewPostImeInputStage processPointer 0
04-07 21:10:48.656 17123-17123/com.google.ar.core.examples.java.helloar D/ViewRootImpl@1a4186e[HelloArActivity]: ViewPostImeInputStage processPointer 1
04-07 21:10:48.808 17123-17123/com.google.ar.core.examples.java.helloar D/ViewRootImpl@1a4186e[HelloArActivity]: ViewPostImeInputStage processPointer 0
04-07 21:10:49.046 17123-17123/com.google.ar.core.examples.java.helloar D/ViewRootImpl@1a4186e[HelloArActivity]: ViewPostImeInputStage processPointer 1
04-07 21:10:49.154 17123-17123/com.google.ar.core.examples.java.helloar D/ViewRootImpl@1a4186e[HelloArActivity]: ViewPostImeInputStage processPointer 0
04-07 21:10:50.254 17123-17123/com.google.ar.core.examples.java.helloar D/ViewRootImpl@1a4186e[HelloArActivity]: ViewPostImeInputStage processPointer 1
04-07 21:38:03.970 17123-17123/com.google.ar.core.examples.java.helloar V/InputMethodManager: Starting input: tba=android.view.inputmethod.EditorInfo@f971e88 nm : com.google.ar.core.examples.java.helloar ic=null
04-07 21:38:03.970 17123-17123/com.google.ar.core.examples.java.helloar I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
04-07 21:38:03.972 17123-17123/com.google.ar.core.examples.java.helloar D/InputTransport: Input channel constructed: fd=92
04-07 21:38:03.972 17123-17123/com.google.ar.core.examples.java.helloar D/InputTransport: Input channel destroyed: fd=91
04-07 21:38:04.676 17123-17123/com.google.ar.core.examples.java.helloar D/ViewRootImpl@1a4186e[HelloArActivity]: MSG_WINDOW_FOCUS_CHANGED 0
04-07 21:38:04.938 17123-17123/com.google.ar.core.examples.java.helloar D/ViewRootImpl@1a4186e[HelloArActivity]: MSG_RESIZED_REPORT: frame=Rect(0, 0 - 1080, 2220) ci=Rect(0, 63 - 0, 126) vi=Rect(0, 63 - 0, 0) or=1
04-07 21:38:04.984 17123-17123/com.google.ar.core.examples.java.helloar D/ViewRootImpl@1a4186e[HelloArActivity]: MSG_RESIZED_REPORT: frame=Rect(0, 0 - 1080, 2220) ci=Rect(0, 63 - 0, 126) vi=Rect(0, 63 - 0, 126) or=1
04-07 21:38:05.060 17123-17123/com.google.ar.core.examples.java.helloar D/ViewRootImpl@1a4186e[HelloArActivity]: Relayout returned: oldFrame=[0,0][1080,2220] newFrame=[0,0][1080,2220] result=0x3 surface={isValid=true 547242164736} surfaceGenerationChanged=false
04-07 21:38:07.544 17123-17123/com.google.ar.core.examples.java.helloar I/native: session_create.cc:71 ArSession_create with info: Entering
04-07 21:38:07.547 17123-17123/com.google.ar.core.examples.java.helloar I/native: version_check.cc:23 ARCore Version: APK version:1.1.180312063
04-07 21:38:07.547 17123-17123/com.google.ar.core.examples.java.helloar I/native: version_check.cc:24 ARCore Version: emulated SDK version:1.0.0
04-07 21:38:07.547 17123-17123/com.google.ar.core.examples.java.helloar I/native: session_create.cc:37 LoadDynamite with info: Dynamite load ok.
04-07 21:38:07.547 17123-17123/com.google.ar.core.examples.java.helloar I/native: session_create_implementation.cc:527 Entering ArSession_createImplementation. ARCore SDK version: [1.0.0].
04-07 21:38:07.649 17123-17123/com.google.ar.core.examples.java.helloar E/native: session_create_implementation.cc:219 Device is not supported.
04-07 21:38:07.649 17123-17123/com.google.ar.core.examples.java.helloar E/native: session_create_implementation.cc:546 Failed to create calibration provider
04-07 21:38:07.649 17123-17123/com.google.ar.core.examples.java.helloar W/native: session_create_implementation.cc:547 ArSession_createImplementation returning ArStatusErrorSpace::AR_UNAVAILABLE_DEVICE_NOT_COMPATIBLE: .
04-07 21:38:07.653 17123-17123/com.google.ar.core.examples.java.helloar D/TextView: setTypeface with style : 0
04-07 21:38:07.658 17123-17123/com.google.ar.core.examples.java.helloar E/HelloArActivity: Exception creating session
                                                                                           com.google.ar.core.exceptions.UnavailableDeviceNotCompatibleException
                                                                                               at com.google.ar.core.Session.throwExceptionFromArStatus(Session.java:361)
                                                                                               at com.google.ar.core.Session.nativeCreateSession(Native Method)
                                                                                               at com.google.ar.core.Session.<init>(Session.java:100)
                                                                                               at com.google.ar.core.examples.java.helloar.HelloArActivity.onResume(HelloArActivity.java:155)
                                                                                               at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1277)
                                                                                               at android.app.Activity.performResume(Activity.java:7140)
                                                                                               at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3850)
                                                                                               at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3914)
                                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1709)
                                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                               at android.os.Looper.loop(Looper.java:154)
                                                                                               at android.app.ActivityThread.main(ActivityThread.java:6823)
                                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
                                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)
04-07 21:38:07.674 17123-17123/com.google.ar.core.examples.java.helloar D/ViewRootImpl@1a4186e[HelloArActivity]: Relayout returned: oldFrame=[0,0][1080,2220] newFrame=[0,0][1080,2220] result=0x1 surface={isValid=true 547242164736} surfaceGenerationChanged=false
04-07 21:38:07.745 17123-17123/com.google.ar.core.examples.java.helloar D/ViewRootImpl@1a4186e[HelloArActivity]: MSG_WINDOW_FOCUS_CHANGED 1
04-07 21:38:07.746 17123-17123/com.google.ar.core.examples.java.helloar D/ViewRootImpl@1a4186e[HelloArActivity]: mHardwareRenderer.initializeIfNeeded()#2 mSurface={isValid=true 547242164736}
04-07 21:38:07.747 17123-17123/com.google.ar.core.examples.java.helloar V/InputMethodManager: Starting input: tba=android.view.inputmethod.EditorInfo@46772f6 nm : com.google.ar.core.examples.java.helloar ic=null
04-07 21:38:07.747 17123-17123/com.google.ar.core.examples.java.helloar I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
04-07 21:38:07.748 17123-17123/com.google.ar.core.examples.java.helloar D/InputTransport: Input channel constructed: fd=106
04-07 21:38:07.748 17123-17123/com.google.ar.core.examples.java.helloar D/InputTransport: Input channel destroyed: fd=92
04-07 21:38:07.763 17123-17123/com.google.ar.core.examples.java.helloar D/ViewRootImpl@1a4186e[HelloArActivity]: Relayout returned: oldFrame=[0,0][1080,2220] newFrame=[0,0][1080,2220] result=0x1 surface={isValid=true 547242164736} surfaceGenerationChanged=false
04-07 21:38:07.824 17123-17129/com.google.ar.core.examples.java.helloar I/art: Do full code cache collection, code=119KB, data=113KB
04-07 21:38:07.824 17123-17129/com.google.ar.core.examples.java.helloar I/art: Starting a blocking GC JitCodeCache
04-07 21:38:07.825 17123-17129/com.google.ar.core.examples.java.helloar I/art: After code cache collection, code=109KB, data=89KB
04-07 21:38:07.973 17123-17123/com.google.ar.core.examples.java.helloar D/ViewRootImpl@1a4186e[HelloArActivity]: MSG_WINDOW_FOCUS_CHANGED 0
04-07 21:38:08.049 17123-17123/com.google.ar.core.examples.java.helloar D/ViewRootImpl@1a4186e[HelloArActivity]: Relayout returned: oldFrame=[0,0][1080,2220] newFrame=[0,0][1080,2220] result=0x3 surface={isValid=true 547242164736} surfaceGenerationChanged=false
04-07 21:38:08.078 17123-17123/com.google.ar.core.examples.java.helloar D/InputTransport: Input channel destroyed: fd=106
04-07 21:38:08.152 17123-17123/com.google.ar.core.examples.java.helloar D/SurfaceView: Relayout returned: oldFrame=[0,0][1080,2220] newFrame=[0,0][1080,2220] result=0x5 surface={Surface(name=null)/@0xc54f959 isValid=false 0}
04-07 21:38:08.212 17123-17123/com.google.ar.core.examples.java.helloar D/ViewRootImpl@1a4186e[HelloArActivity]: mHardwareRenderer.destroy()#1
04-07 21:38:08.230 17123-17123/com.google.ar.core.examples.java.helloar D/ViewRootImpl@1a4186e[HelloArActivity]: Relayout returned: oldFrame=[0,0][1080,2220] newFrame=[0,0][1080,2220] result=0x5 surface={isValid=false 0} surfaceGenerationChanged=true
04-07 21:38:08.530 17123-17123/com.google.ar.core.examples.java.helloar D/ViewRootImpl@1a4186e[HelloArActivity]: mHardwareRenderer.destroy()#4
04-07 21:38:08.530 17123-17123/com.google.ar.core.examples.java.helloar D/ViewRootImpl@1a4186e[HelloArActivity]: dispatchDetachedFromWindow
04-07 21:38:08.533 17123-17123/com.google.ar.core.examples.java.helloar D/InputTransport: Input channel destroyed: fd=88
04-07 21:38:08.534 17123-17123/com.google.ar.core.examples.java.helloar W/SemDesktopModeManager: unregisterListener: Listener is null

```

**Comment by inio** [comment]
Good news!  We found the issue and there was a glitch in our model list for the Note 8.  The next release of ARCore will add support for this model.

**Comment by netcafeohashi** [comment]
@inio 
Thanks! That's very good news.

**Comment by inio** [comment]
This device should be supported with ARCore 1.2, announced today.  You can wait for the Play Store rollout later this week or [sideload it today](https://github.com/google-ar/arcore-android-sdk/releases/tag/v1.2.0).
