### ISSUE TITLE
Fatal Exception: not loading libtango_client_api

### ISSUE THREAD

**Issue by echorebel** [google-ar/arcore-android-sdk#33]
Hey ho,
tried the sample to run on Pixel with Android 8.

Crashes at start, seems it cannot load libtango_client_api which i would expect in the arcore aar.
Here the log, maybe some1 has an idea:

```
? I/zygote64: Late-enabling -Xcheck:jni
com.google.ar.core.examples.java.helloar I/TangoClientLibLoader: Pure Java path, not loading libtango_client_api.so at all.
com.google.ar.core.examples.java.helloar E/Tango: Java version of Tango Service not found, falling back to tangoservice_d.
com.google.ar.core.examples.java.helloar E/zygote64: No implementation found for int com.google.atap.tango.TangoJNINative.Initialize(android.content.Context) (tried Java_com_google_atap_tango_TangoJNINative_Initialize and Java_com_google_atap_tango_TangoJNINative_Initialize__Landroid_content_Context_2)
com.google.ar.core.examples.java.helloar D/AndroidRuntime: Shutting down VM
com.google.ar.core.examples.java.helloar E/AndroidRuntime: FATAL EXCEPTION: main
                                                           Process: com.google.ar.core.examples.java.helloar, PID: 7772
                                                           java.lang.UnsatisfiedLinkError: No implementation found for int com.google.atap.tango.TangoJNINative.Initialize(android.content.Context) (tried Java_com_google_atap_tango_TangoJNINative_Initialize and Java_com_google_atap_tango_TangoJNINative_Initialize__Landroid_content_Context_2)
                                                               at com.google.atap.tango.TangoJNINative.Initialize(Native Method)
                                                               at com.google.atap.tangoservice.Tango.<init>(Tango.java:385)
                                                               at com.google.ar.core.TangoWrapper.createInstance(TangoWrapper.java:32)
                                                               at com.google.ar.core.Session.bindTangoService(Session.java:425)
                                                               at com.google.ar.core.Session.resume(Session.java:153)
                                                               at com.google.ar.core.examples.java.helloar.HelloArActivity.onResume(HelloArActivity.java:136)
                                                               at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1354)
                                                               at android.app.Activity.performResume(Activity.java:7079)
                                                               at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3620)
                                                               at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3685)
                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2898)
                                                               at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                                                               at android.os.Handler.dispatchMessage(Handler.java:105)
                                                               at android.os.Looper.loop(Looper.java:164)
                                                               at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by echorebel** [comment]
ok ok, RTFM :)

**Comment by hannesa2** [comment]
Please tell us, what you forgot

**Comment by aavina** [comment]
@hannesa2 You need to make sure you install the separate ARCore APK onto the device before running the sample app. See below.

![screen shot 2017-10-13 at 1 27 41 pm](https://user-images.githubusercontent.com/1190804/31560562-63fb97a0-b01a-11e7-89b7-c39448591f89.png)
