### ISSUE TITLE
NullPointerException from calling requestInstall()

### ISSUE THREAD

**Issue by drunkenplatypus** [google-ar/arcore-android-sdk#397]
In the DemoUtils file under the createArSession method the app checks if ARCore is installed on the device.

I am getting a NullPointerException when the switch statement atempts to execute the method.

`switch (ArCoreApk.getInstance().requestInstall(activity, !installRequested)) { ... }`

Stacktrace:

2018-05-24 15:03:33.233 5331-5331/com.example.ezio.ar_rf_demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.ezio.ar_rf_demo, PID: 5331
    java.lang.RuntimeException: Unable to resume activity {com.example.ezio.ar_rf_demo/com.example.ezio.ar_rf_demo.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3581)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3621)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2862)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
        at com.google.ar.core.h.e(Unknown Source:39)
        at com.google.ar.core.h.c(Unknown Source:0)
        at com.google.ar.core.h.requestInstall(Unknown Source:0)
        at com.example.ezio.ar_rf_demo.DemoUtils.createArSession(**DemoUtils.java:90**)
        at com.example.ezio.ar_rf_demo.MainActivity.onResume(**MainActivity.java:137**)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1355)
        at android.app.Activity.performResume(Activity.java:7117)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3556)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3621) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2862) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by inio** [comment]
What device and android version generated this?  If possible, could I get the build fingerprint (‘adb shell getprop ro.build.fingerprint’) and Ann all-process logcat coverig about one second leading up to the exception?

**Comment by drunkenplatypus** [comment]
Android Studio 3.2 Canary 13
Build #AI-181.4445.78.32.4749738, built on April 27, 2018
JRE: 1.8.0_152-release-1136-b03 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

Device:
I am using the Android Emulator 27.3.1 (Pixel 2 XL - Android 8.1)

Build Fingerprint:
google/sdk_gphone_x86/generic_x86:8.1.0/OSM1.180201.021/4741582:userdebug/dev-keys

Logcat - no filters - 1 second before the exception (not including the exception):

2018-05-24 16:15:27.387 2367-2455/com.google.android.googlequicksearchbox:search I/AudioController: internalShutdown
2018-05-24 16:15:27.390 2367-2367/com.google.android.googlequicksearchbox:search I/MicroDetector: Keeping mic open: false
2018-05-24 16:15:27.390 2367-2367/com.google.android.googlequicksearchbox:search I/MicroDetectionWorker: #onError(false)
2018-05-24 16:15:27.390 2367-4247/com.google.android.googlequicksearchbox:search I/DeviceStateChecker: DeviceStateChecker cancelled
2018-05-24 16:15:32.233 1653-2904/system_process I/ActivityManager: Force stopping com.example.ezio.ar_rf_demo appid=10080 user=0: from pid 8741
2018-05-24 16:15:32.233 1653-2904/system_process I/ActivityManager: Killing 8271:com.example.ezio.ar_rf_demo/u0a80 (adj 902): stop com.example.ezio.ar_rf_demo
2018-05-24 16:15:32.237 1653-1670/system_process W/zygote: kill(-8271, 9) failed: No such process
2018-05-24 16:15:32.263 1901-1901/com.android.phone D/CarrierSvcBindHelper: No carrier app for: 0
2018-05-24 16:15:32.273 1653-1670/system_process W/zygote: kill(-8271, 9) failed: No such process
2018-05-24 16:15:32.317 1653-1670/system_process W/zygote: kill(-8271, 9) failed: No such process
2018-05-24 16:15:32.317 1653-1670/system_process I/zygote: Successfully killed process cgroup uid 10080 pid 8271 in 79ms
2018-05-24 16:15:32.473 2367-2367/com.google.android.googlequicksearchbox:search I/MicroDetectionWorker: #updateMicroDetector [detectionMode: [mDetectionMode: [1]]]
2018-05-24 16:15:32.473 2367-2367/com.google.android.googlequicksearchbox:search I/MicroDetectionWorker: #startMicroDetector [speakerMode: 0]
2018-05-24 16:15:32.475 2367-2367/com.google.android.googlequicksearchbox:search I/AudioController: Using mInputStreamFactoryBuilder
2018-05-24 16:15:32.477 2367-2367/com.google.android.googlequicksearchbox:search I/MicroDetectionWorker: onReady
2018-05-24 16:15:32.479 2367-2455/com.google.android.googlequicksearchbox:search I/MicroRecognitionRunner: Starting detection.
2018-05-24 16:15:32.482 2367-8240/com.google.android.googlequicksearchbox:search I/MicrophoneInputStream: mic_starting com.google.android.apps.gsa.staticplugins.aa.c@e0dcfcd
2018-05-24 16:15:32.486 1653-3105/system_process I/ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=com.example.ezio.ar_rf_demo/.MainActivity} from uid 2000
2018-05-24 16:15:32.496 1494-8751/? I/AudioFlinger: AudioFlinger's thread 0xe2203180 tid=8751 ready to run
2018-05-24 16:15:32.496 1494-4672/? E/AudioFlinger: not enough memory for AudioTrack size=131296
2018-05-24 16:15:32.497 1494-4672/? D/MemoryDealer:   AudioTrack (0xe617e340, size=4194304)
        0: 0xe617e350 | 0x00000000 | 0x000200E0 | A 
        1: 0xe617e370 | 0x000200E0 | 0x000200E0 | A 
        2: 0xe617e4e0 | 0x000401C0 | 0x000200E0 | A 
        3: 0xe617e720 | 0x000602A0 | 0x000200E0 | A 
        4: 0xe6199250 | 0x00080380 | 0x000200E0 | A 
        5: 0xe61993e0 | 0x000A0460 | 0x000200E0 | A 
        6: 0xe61995b0 | 0x000C0540 | 0x000200E0 | A 
        7: 0xe6199740 | 0x000E0620 | 0x000200E0 | A 
        8: 0xe6199910 | 0x00100700 | 0x000200E0 | A 
        9: 0xe6199aa0 | 0x001207E0 | 0x000200E0 | A 
       10: 0xe6199c00 | 0x001408C0 | 0x000200E0 | A 
       11: 0xe6199d90 | 0x001609A0 | 0x000200E0 | A 
       12: 0xe6199f60 | 0x00180A80 | 0x000200E0 | A 
       13: 0xe4d7f0f0 | 0x001A0B60 | 0x000200E0 | A 
       14: 0xe4d7f280 | 0x001C0C40 | 0x000200E0 | A 
       15: 0xe4d7f410 | 0x001E0D20 | 0x000200E0 | A 
       16: 0xe617eaa0 | 0x00200E00 | 0x000200E0 | A 
       17: 0xe4d7f450 | 0x00220EE0 | 0x000200E0 | A 
       18: 0xe617edb0 | 0x00240FC0 | 0x000200E0 | A 
       19: 0xe617ef90 | 0x002610A0 | 0x000200E0 | A 
       
2018-05-24 16:15:32.497 1494-4672/? E/AudioFlinger: createRecordTrack_l() initCheck failed -12; no control block?
2018-05-24 16:15:32.499 2367-8240/com.google.android.googlequicksearchbox:search E/AudioRecord: AudioFlinger could not create record track, status: -12
2018-05-24 16:15:32.620 2367-8240/com.google.android.googlequicksearchbox:search E/AudioRecord-JNI: Error creating AudioRecord instance: initialization check failed with status -12.
2018-05-24 16:15:32.620 2367-8240/com.google.android.googlequicksearchbox:search E/android.media.AudioRecord: Error code -20 when initializing native AudioRecord object.
2018-05-24 16:15:32.620 2367-8240/com.google.android.googlequicksearchbox:search I/MicrophoneInputStream: mic_started com.google.android.apps.gsa.staticplugins.aa.c@e0dcfcd
2018-05-24 16:15:32.623 1653-2904/system_process W/zygote: Long monitor contention with owner Binder:1653_F (3105) at void com.android.server.wm.WindowManagerService.continueSurfaceLayout()(WindowManagerService.java:2951) waiters=1 in int com.android.server.wm.WindowManagerService.relayoutWindow(com.android.server.wm.Session, android.view.IWindow, int, android.view.WindowManager$LayoutParams, int, int, int, int, android.graphics.Rect, android.graphics.Rect, android.graphics.Rect, android.graphics.Rect, android.graphics.Rect, android.graphics.Rect, android.graphics.Rect, android.util.MergedConfiguration, android.view.Surface) for 102ms
2018-05-24 16:15:32.693 1653-4008/system_process I/ActivityManager: Start proc 8754:com.example.ezio.ar_rf_demo/u0a80 for activity com.example.ezio.ar_rf_demo/.MainActivity
2018-05-24 16:15:32.698 1397-1444/? D/gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 16592896
2018-05-24 16:15:32.705 8754-8754/? I/zygote: Not late-enabling -Xcheck:jni (already on)
2018-05-24 16:15:32.715 2367-8240/com.google.android.googlequicksearchbox:search E/ActivityThread: Failed to find provider info for com.google.android.apps.gsa.testing.ui.audio.recorded
2018-05-24 16:15:32.732 2367-2367/com.google.android.googlequicksearchbox:search I/MicroDetectionWorker: onReady
2018-05-24 16:15:32.735 2367-2367/com.google.android.googlequicksearchbox:search I/MicroDetector: Keeping mic open: false
2018-05-24 16:15:32.737 2367-4247/com.google.android.googlequicksearchbox:search I/DeviceStateChecker: DeviceStateChecker cancelled
2018-05-24 16:15:32.751 2367-2605/com.google.android.googlequicksearchbox:search I/MicroRecognitionRunner: Stopping hotword detection.
2018-05-24 16:15:32.759 8754-8754/? W/zygote: Unexpected CPU variant for X86 using defaults: x86
2018-05-24 16:15:32.767 2367-8240/com.google.android.googlequicksearchbox:search I/MicrophoneInputStream: mic_close com.google.android.apps.gsa.staticplugins.aa.c@e0dcfcd
2018-05-24 16:15:32.769 2367-2455/com.google.android.googlequicksearchbox:search I/MicroRecognitionRunner: Detection finished
2018-05-24 16:15:32.770 2367-8760/com.google.android.googlequicksearchbox:search I/AudioController: internalShutdown
2018-05-24 16:15:32.860 8734-8734/? D/AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 2000 <<<<<<
2018-05-24 16:15:32.863 2367-2524/com.google.android.googlequicksearchbox:search D/EGL_emulation: eglMakeCurrent: 0xe0e84a20: ver 3 1 (tinfo 0xe0e83740)
2018-05-24 16:15:32.873 2283-2410/com.google.android.apps.nexuslauncher D/EGL_emulation: eglMakeCurrent: 0xccb324a0: ver 3 1 (tinfo 0xccb344b0)
2018-05-24 16:15:32.950 8754-8754/com.example.ezio.ar_rf_demo I/zygote: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
2018-05-24 16:15:32.951 8734-8734/? W/app_process: Unexpected CPU variant for X86 using defaults: x86
2018-05-24 16:15:32.954 8734-8734/? I/app_process: The ClassLoaderContext is a special shared library.
2018-05-24 16:15:32.961 8754-8754/com.example.ezio.ar_rf_demo D/EGL_emulation: eglCreateContext: 0xe0e09720: maj 3 min 1 rcv 4
2018-05-24 16:15:32.967 8754-8754/com.example.ezio.ar_rf_demo D/EGL_emulation: eglMakeCurrent: 0xe0e09720: ver 3 1 (tinfo 0xdf732c10)
2018-05-24 16:15:32.967 8754-8754/com.example.ezio.ar_rf_demo E/eglCodecCommon: glUtilsParamSize: unknow param 0x000082da
2018-05-24 16:15:32.967 8754-8754/com.example.ezio.ar_rf_demo E/eglCodecCommon: glUtilsParamSize: unknow param 0x000082da
2018-05-24 16:15:32.970 8754-8754/com.example.ezio.ar_rf_demo I/Filament: FEngine (32 bits) created at 0xe928ee00
2018-05-24 16:15:32.990 8734-8734/? D/AndroidRuntime: Calling main entry com.android.commands.wm.Wm
2018-05-24 16:15:32.995 1653-2282/system_process W/WindowManager: Permission Denial: dismissKeyguard from pid=8734, uid=2000 requires android.permission.CONTROL_KEYGUARD
2018-05-24 16:15:32.995 8734-8734/? D/AndroidRuntime: Shutting down VM
2018-05-24 16:15:33.009 8754-8779/com.example.ezio.ar_rf_demo D/EGL_emulation: eglCreateContext: 0xe0e09a80: maj 3 min 1 rcv 4
2018-05-24 16:15:33.015 8754-8779/com.example.ezio.ar_rf_demo D/EGL_emulation: eglMakeCurrent: 0xe0e09a80: ver 3 1 (tinfo 0xcdae14e0)
2018-05-24 16:15:33.020 8754-8779/com.example.ezio.ar_rf_demo E/eglCodecCommon: glUtilsParamSize: unknow param 0x000082da
2018-05-24 16:15:33.020 8754-8779/com.example.ezio.ar_rf_demo E/eglCodecCommon: glUtilsParamSize: unknow param 0x000082da
2018-05-24 16:15:33.176 8754-8754/com.example.ezio.ar_rf_demo E/EGL_emulation: eglQueryContext 32c0  EGL_BAD_ATTRIBUTE
2018-05-24 16:15:33.176 8754-8754/com.example.ezio.ar_rf_demo E/EGL_emulation: tid 8754: eglQueryContext(1822): error 0x3004 (EGL_BAD_ATTRIBUTE)
2018-05-24 16:15:33.179 1653-2282/system_process I/ActivityManager: START u0 {act=android.content.pm.action.REQUEST_PERMISSIONS pkg=com.google.android.packageinstaller cmp=com.google.android.packageinstaller/com.android.packageinstaller.permission.ui.GrantPermissionsActivity (has extras)} from uid 10080
2018-05-24 16:15:33.199 8754-8754/com.example.ezio.ar_rf_demo W/Bundle: Key com.google.ar.core expected String but value was a java.lang.Boolean.  The default value <null> was returned.
2018-05-24 16:15:33.200 8754-8754/com.example.ezio.ar_rf_demo W/Bundle: Attempt to cast generated internal exception:
    java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
        at android.os.BaseBundle.getString(BaseBundle.java:1121)
        at com.google.ar.core.h.e(Unknown Source:33)
        at com.google.ar.core.h.c(Unknown Source:0)
        at com.google.ar.core.h.requestInstall(Unknown Source:0)
        at com.example.ezio.ar_rf_demo.DemoUtils.createArSession(DemoUtils.java:90)
        at com.example.ezio.ar_rf_demo.MainActivity.onResume(MainActivity.java:137)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1355)
        at android.app.Activity.performResume(Activity.java:7117)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3556)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3621)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2862)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
2018-05-24 16:15:33.200 8754-8754/com.example.ezio.ar_rf_demo D/AndroidRuntime: Shutting down VM

**Comment by inio** [comment]
Thank you very much!  I'll look into this (I'm the primary developer for the ArCoreApk class).

**Comment by inio** [comment]
Sorry about the lag on this.  From what I can see this shouldn't happen.  So we see:

    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean 
    java.lang.String.equals(java.lang.Object)' on a null object reference
    at com.google.ar.core.h.e(Unknown Source:39)
    at com.google.ar.core.h.c(Unknown Source:0)
    at com.google.ar.core.h.requestInstall(Unknown Source:0)

There's two calls to String.equals() in `com.google.ar.core.h` (actualy `ArCoreApkImpl`):

    if (metadata.containsKey(METADATA_KEY_APP_TYPE)) {
      appIsArRequired = metadata.getString(METADATA_KEY_APP_TYPE).equals(AR_REQUIRED_VALUE);
    } else ...

and

      String installActivityName = InstallActivity.class.getCanonicalName();
      ...
        if (installActivityName.equals(info.name)) {

The only thing I can think is that maybe your manifest contains a value for the meta-data "com.google.ar.core" that android detects as something other than a string.  This meta-data should be either "required" or "optional".

**Comment by drunkenplatypus** [comment]
Yeah I had "com.google.ar.core" set to "true" for some reason. I have no idea how, but changing that to required has fixed the error.

Thank you so much for your help!
