### ISSUE TITLE
Unable to view camera while run HEllo AR Core sample application.I am getting black screen with message searching for surface:

### ISSUE THREAD

**Issue by kirankaushal** [google-ar/arcore-android-sdk#408]
When I run Hello AR Core sample app on Samsung J7, I am getting below error:

java.io.FileNotFoundException: shaders/screenquad.vert
at android.content.res.AssetManager.openAsset(Native Method)
at android.content.res.AssetManager.open(AssetManager.java:421)
at android.content.res.AssetManager.open(AssetManager.java:395)
at com.helloarsample.common.rendering.ShaderUtil.readRawTextFileFromAssets(ShaderUtil.java:87)
at com.helloarsample.common.rendering.ShaderUtil.loadGLShader(ShaderUtil.java:37)
at helloarsample.helloar.HelloArActivity.onSurfaceCreated(HelloArActivity.java:221)

**Comment by kirankaushal** [comment]
Please help me If any body have an idea about how to resolve that issue.

**Comment by inio** [comment]
It sounds like your app build isn't including the assets.  Are you using the unmodified HelloAR project?

**Comment by inio** [comment]
Closing for inactivity.

**Comment by kset1595** [comment]
Open Player settings 
Untick multithreading in other settings
And tick ARCore in XR Settings
It should do the job ;)
