### ISSUE TITLE
Unable to access image plane data on Android P

### ISSUE THREAD

**Issue by mralbean** [google-ar/arcore-android-sdk#414]
I've attempted to install the `computervision_java` sample application on my Pixel 2 running Android P, but I'm seeing a crash with the following stack trace:

```
06-04 11:56:36.770 10675-10693/? W/.computervisio: Accessing hidden method Landroid/media/Image$Plane;-><init>()V (blacklist, linking)
    Accessing hidden method Landroid/media/Image$Plane;-><init>()V (blacklist, linking)
06-04 11:56:36.780 10675-10693/? E/AndroidRuntime: FATAL EXCEPTION: GLThread 626
    Process: com.google.ar.core.examples.java.computervision, PID: 10675
    java.lang.NoSuchMethodError: No direct method <init>()V in class Landroid/media/Image$Plane; or its super classes (declaration of 'android.media.Image$Plane' appears in /system/framework/framework.jar)
        at a.a.b.<init>(Unknown Source:0)
        at com.google.ar.core.ArImage$a.<init>(Unknown Source:2)
        at com.google.ar.core.ArImage.getPlanes(Unknown Source:27)
        at com.google.ar.core.examples.java.computervision.ComputerVisionActivity.renderProcessedImageCpuDirectAccess(ComputerVisionActivity.java:268)
        at com.google.ar.core.examples.java.computervision.ComputerVisionActivity.onDrawFrame(ComputerVisionActivity.java:243)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1571)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)
```

Seems like there is an issue with how the `Image#Plane` data is being created within `ArImage`. Are there any workarounds for this issue, or should I expect this to be fixed in an upcoming release?

**Comment by inio** [comment]
We're aware of this and working on it.

**Comment by mralbean** [comment]
This has not been an issue for me since Android P Beta 2 (PPP3.180510.008), which was released a few months ago. Thanks!
