### ISSUE TITLE
Pixel 2 after reinstalling arcore - "This device does not support AR"

### ISSUE THREAD

**Issue by NotASingleSingelton** [google-ar/arcore-android-sdk#469]
When I try to run an app(sceneform example, draw a line, own implementation) with arcore on my pixel 2, where I uninstalled arcore, the install menu pops up as expected. Then after the installation is finished the dialog is closing and "This device does not support AR" toast is showing +BlackScreen or the app closes.

Some logs:
session_create_implementation_shared.cc:406 Device is not supported.
session_create_implementation.cc:91 Failed to create calibration provider.
session_create_implementation.cc:92 ArSession_createImplementation returning ArStatusErrorSpace::AR_UNAVAILABLE_DEVICE_NOT_COMPATIBLE: .

Android: 8.1.0

**Comment by avirodov** [comment]
Hi, can you please provide your device fingerprint by running:
`adb shell getprop ro.build.fingerprint`

Separately, if you re-run the same app after you observe the issue, will it now work? If not, does any other ARCore app works? Please kill the app first in task manager before re-running.

**Comment by inio** [comment]
Thanks for the report.  This looks like a race condition between installation/unpacking of ARCore and device setup that may affect a small number of users with devices far down the alphabet (like walleye).

**Comment by inio** [comment]
This should be fixed with [ARCore 1.5](https://github.com/google-ar/arcore-android-sdk/releases/tag/v1.5.0) which was released today.

**Comment by dharmeshRughani1234** [comment]
Hello @inio i am facing the same problem right now, below is my device fingerprint:
HUAWEI/ANE-AL00/HWANE:8.0.0/HUAWEIANE-AL00/170(C675):user/release-keys

I can able to download ARCore apk but after that i can only see the black screen and i can see the below message.

"This device does not support AR"

**Comment by htrippin** [comment]
@dharmeshRughani1234 I understand this post is a year old and closed, but did you figure out your problem? I am running into the same error message.

**Comment by exbe** [comment]
I am facing similar issue on Android Emulator (30.2.6) and fresh Android studio 4.1.1


Device profile:
```
Name: Pixel_4_API_28
CPU/ABI: Google Play Intel Atom (x86)
Path: C:\Users\Exbe\.android\avd\Pixel_4_API_28.avd
Target: google_apis_playstore [Google Play] (API level 28)
Skin: pixel_4
SD Card: 512M
fastboot.chosenSnapshotFile: 
runtime.network.speed: full
hw.accelerometer: yes
hw.device.name: pixel_4
hw.lcd.width: 1080
hw.initialOrientation: Portrait
image.androidVersion.api: 28
tag.id: google_apis_playstore
hw.mainKeys: no
hw.camera.front: emulated
avd.ini.displayname: Pixel 4 API 28
hw.gpu.mode: auto
hw.ramSize: 1536
PlayStore.enabled: true
fastboot.forceColdBoot: no
hw.cpu.ncore: 4
hw.keyboard: yes
hw.sensors.proximity: yes
hw.dPad: no
hw.lcd.height: 2280
vm.heapSize: 256
skin.dynamic: yes
hw.device.manufacturer: Google
hw.gps: yes
hw.audioInput: yes
image.sysdir.1: system-images\android-28\google_apis_playstore\x86\
showDeviceFrame: yes
hw.camera.back: virtualscene
AvdId: Pixel_4_API_28
hw.lcd.density: 440
hw.arc: false
hw.device.hash2: MD5:6b5943207fe196d842659d2e43022e20
fastboot.forceChosenSnapshotBoot: no
fastboot.forceFastBoot: yes
hw.trackBall: no
hw.battery: yes
hw.sdCard: yes
tag.display: Google Play
runtime.network.latency: none
disk.dataPartition.size: 6442450944
hw.sensors.orientation: yes
avd.ini.encoding: UTF-8
hw.gpu.enabled: yes
```

App log (sample: HelloArActivity)

```
01/04 00:40:16: Launching 'app' on Pixel 4 API 28.
App restart successful without requiring a re-install.
$ adb shell am start -n "com.google.ar.core.examples.java.helloar/com.google.ar.core.examples.java.helloar.HelloArActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 4156 on device 'emulator-5554'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
W/es.java.helloa: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (light greylist, reflection)
    Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (light greylist, reflection)
D/OpenGLRenderer: Skia GL Pipeline
I/ARCore-ArCoreApk: Starting setup activity
D/HostConnection: HostConnection::get() New Host Connection established 0xe222c280, tid 4211
D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0 
I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
    android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Swap behavior 1
W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
D/OpenGLRenderer: Swap behavior 0
D/HostConnection: HostConnection::get() New Host Connection established 0xe0919740, tid 4184
D/eglCodecCommon: setVertexArrayObject: set vao to 0 (0) 0 0
D/EGL_emulation: eglCreateContext: 0xe2204300: maj 3 min 0 rcv 3
D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0 
D/eglCodecCommon: setVertexArrayObject: set vao to 0 (0) 0 0
D/EGL_emulation: eglCreateContext: 0xe036e2a0: maj 3 min 0 rcv 3
D/EGL_emulation: eglMakeCurrent: 0xe2204300: ver 3 0 (tinfo 0xe22036a0)
D/HostConnection: createUnique: call
    HostConnection::get() New Host Connection established 0xe0917e40, tid 4211
D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0 
E/eglCodecCommon: GoldfishAddressSpaceHostMemoryAllocator: ioctl_ping failed for device_type=5, ret=-1
D/EGL_emulation: eglMakeCurrent: 0xe036e2a0: ver 3 0 (tinfo 0xe0373000)
D/EGL_emulation: eglMakeCurrent: 0xe2204300: ver 3 0 (tinfo 0xe22036a0)
D/eglCodecCommon: setVertexArrayObject: set vao to 0 (0) 3 2
D/eglCodecCommon: setVertexArrayObject: set vao to 0 (0) 0 0
D/eglCodecCommon: setVertexArrayObject: set vao to 0 (0) 0 1
D/eglCodecCommon: setVertexArrayObject: set vao to 1 (1) 2 0
D/eglCodecCommon: setVertexArrayObject: set vao to 0 (0) 2 1
D/eglCodecCommon: setVertexArrayObject: set vao to 0 (0) 3 1
    setVertexArrayObject: set vao to 0 (0) 4 1
D/eglCodecCommon: setVertexArrayObject: set vao to 2 (2) 5 0
D/eglCodecCommon: setVertexArrayObject: set vao to 0 (0) 5 1
D/eglCodecCommon: setVertexArrayObject: set vao to 3 (3) 6 0
D/eglCodecCommon: setVertexArrayObject: set vao to 0 (0) 6 1
    setVertexArrayObject: set vao to 4 (4) 7 0
I/es.java.helloa: Background concurrent copying GC freed 76435(2MB) AllocSpace objects, 0(0B) LOS objects, 50% free, 3MB/6MB, paused 3.291ms total 104.140ms
D/eglCodecCommon: setVertexArrayObject: set vao to 0 (0) 7 1
D/eglCodecCommon: setVertexArrayObject: set vao to 0 (0) 8 1
D/eglCodecCommon: setVertexArrayObject: set vao to 0 (0) 9 1
    setVertexArrayObject: set vao to 0 (0) 10 1
D/eglCodecCommon: setVertexArrayObject: set vao to 5 (5) 10 0
D/EGL_emulation: eglMakeCurrent: 0xe2204300: ver 3 0 (tinfo 0xe22036a0)
I/ARCore-ArCoreApk: Starting setup activity
D/EGL_emulation: eglMakeCurrent: 0xe036e2a0: ver 3 0 (tinfo 0xe0373000)
D/EGL_emulation: eglMakeCurrent: 0xe036e2a0: ver 3 0 (tinfo 0xe0373000)
D/EGL_emulation: eglMakeCurrent: 0xe2204300: ver 3 0 (tinfo 0xe22036a0)
D/EGL_emulation: eglMakeCurrent: 0xe2204300: ver 3 0 (tinfo 0xe22036a0)
I/ARCore-ArCoreApk: Starting setup activity
D/EGL_emulation: eglMakeCurrent: 0xe036e2a0: ver 3 0 (tinfo 0xe0373000)
D/EGL_emulation: eglMakeCurrent: 0xe036e2a0: ver 3 0 (tinfo 0xe0373000)
D/EGL_emulation: eglMakeCurrent: 0xe036e2a0: ver 3 0 (tinfo 0xe0373000)
D/EGL_emulation: eglMakeCurrent: 0xe2204300: ver 3 0 (tinfo 0xe22036a0)
D/EGL_emulation: eglMakeCurrent: 0xe2204300: ver 3 0 (tinfo 0xe22036a0)
D/EGL_emulation: eglMakeCurrent: 0xe036e2a0: ver 3 0 (tinfo 0xe0373000)
D/EGL_emulation: eglMakeCurrent: 0xe2204300: ver 3 0 (tinfo 0xe22036a0)
I/third_party/arcore/ar/core/android/sdk/session_create.cc: Entering ArSession_createWithFeatures
    ARCore Version: SDK build name: 1.22
I/third_party/arcore/ar/core/android/sdk/session_create.cc: ARCore Version: APK version code: 203220553
I/third_party/arcore/ar/core/android/sdk/session_create.cc: Dynamite load ok.
I/third_party/arcore/java/com/google/vr/dynamite/client/native/dynamite_client.cc: Attempting to load native library arcore_c from package com.google.ar.core
I/third_party/arcore/java/com/google/vr/dynamite/client/native/dynamite_client.cc: Dynamite::LoadNativeRemoteLibrary handle=184716947
I/third_party/arcore/ar/core/android/sdk/session_create.cc: ARCore SDK: dynamite number_of_symbols_loaded=226
I/native: session_create_implementation.cc:206 Entering createImplementationWithFeaturesAndSettings. ARCore SDK version: [1.22.202940000].
V/third_party/redwood/infrastructure/jni_common/jni_helper.cc: JniHelper: attached thread (Called from line 364).
E/native: session_create_implementation_shared.cc:1954 Unable to obtain device profile from the content provider: NOT_FOUND: Device is not supported.
E/native: session_create_implementation_shared.cc:2268 Failed to create calibration config and device profile.
W/native: session_create_implementation_shared.cc:2269 CreateDeviceProfileDirectDependencies returning NOT_FOUND: 
    ARCoreError: third_party/arcore/ar/core/android/implementation/session_create_implementation_shared.cc:1958
     [type.googleapis.com/util.ErrorSpacePayload='ArStatusErrorSpace::AR_UNAVAILABLE_DEVICE_NOT_COMPATIBLE'].
V/third_party/redwood/infrastructure/jni_common/jni_helper.cc: ~JniHelper: about to detach thread (Called from line 364).
    ~JniHelper: detached thread (Called from line 364).
E/native: error_policy_util.cc:263 
    ################ ARCore Native Error ##################
    BUILD_CHANGELIST:344925174
    BUILD_BASELINE_CHANGELIST:342918918
    ################### Stack Trace Begin ################
    ARCoreError: third_party/arcore/ar/core/android/implementation/session_create_implementation_shared.cc:1958	https://cs.corp.google.com/piper///depot/google3/third_party/arcore/ar/core/android/implementation/session_create_implementation_shared.cc?g=0&l=1958
    ARCoreError: third_party/arcore/ar/core/android/implementation/session_create_implementation.cc:315	https://cs.corp.google.com/piper///depot/google3/third_party/arcore/ar/core/android/implementation/session_create_implementation.cc?g=0&l=315
    ARCoreError: third_party/arcore/ar/core/android/implementation/session_create_implementation.cc:411	https://cs.corp.google.com/piper///depot/google3/third_party/arcore/ar/core/android/implementation/session_create_implementation.cc?g=0&l=411
    ################### Stack Trace End #################
    
    ################### Undecorated Trace Begin  #################
    NOT_FOUND: 
    ARCoreError: third_party/arcore/ar/core/android/implementation/session_create_implementation.cc:315
    
    ARCoreError: third_party/arcore/ar/core/android/implementation/session_create_implementation_shared.cc:1958
     [type.googleapis.com/util.ErrorSpacePayload='ArStatusErrorSpace::AR_UNAVAILABLE_DEVICE_NOT_COMPATIBLE']
    ################### Undecorated Trace End  #################
W/es.java.helloa: Accessing hidden method Landroid/widget/TextView;->getTextDirectionHeuristic()Landroid/text/TextDirectionHeuristic; (light greylist, linking)
E/HelloArActivity: Exception creating session
    com.google.ar.core.exceptions.UnavailableDeviceNotCompatibleException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at com.google.ar.core.Session.throwExceptionFromArStatus(Session.java:16)
        at com.google.ar.core.Session.nativeCreateSessionAndWrapperWithFeatures(Native Method)
        at com.google.ar.core.Session.<init>(Session.java:11)
        at com.google.ar.core.Session.<init>(Session.java:4)
        at com.google.ar.core.examples.java.helloar.HelloArActivity.onResume(HelloArActivity.java:256)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1412)
        at android.app.Activity.performResume(Activity.java:7292)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3776)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3816)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
D/EGL_emulation: eglMakeCurrent: 0xe2204300: ver 3 0 (tinfo 0xe22036a0)
D/EGL_emulation: eglMakeCurrent: 0xe036e2a0: ver 3 0 (tinfo 0xe0373000)
D/EGL_emulation: eglMakeCurrent: 0xe2204300: ver 3 0 (tinfo 0xe22036a0)
D/EGL_emulation: eglMakeCurrent: 0xe2204300: ver 3 0 (tinfo 0xe22036a0)
D/EGL_emulation: eglMakeCurrent: 0xe036e2a0: ver 3 0 (tinfo 0xe0373000)
D/EGL_emulation: eglMakeCurrent: 0xe2204300: ver 3 0 (tinfo 0xe22036a0)
D/EGL_emulation: eglMakeCurrent: 0xe2204300: ver 3 0 (tinfo 0xe22036a0)
```

ARCore version:
```
I/native: session_create_implementation.cc:206 Entering createImplementationWithFeaturesAndSettings. ARCore SDK version: [1.22.202940000].

**Comment by htrippin** [comment]
@exbe I noticed that, pretty strange problem. Hopefully more API's become supported in the future.

**Comment by somethingbeta** [comment]
Didnt work for me in 30 working in 29 though  thanks @exbe

**Comment by CRJain** [comment]
thanks @exbe
