### ISSUE TITLE
glError 1282

### ISSUE THREAD

**Issue by pranavkotecha88** [google-ar/arcore-android-sdk#48]
Hi guys, I am trying the arcore in one of my apps, and I get stuck at this point, where it gives me a glError 1282. 

E/HelloArActivity: Exception on the OpenGL thread
                                                                           java.lang.RuntimeException: Setting up to draw planes: glError 1282
                                                                               at ar.rendering.ShaderUtil.checkGLError(ShaderUtil.java:71)
                                                                               at ar.rendering.PlaneRenderer.drawPlanes(PlaneRenderer.java:359)
                                                                               at ar.HelloArActivity.onDrawFrame(HelloArActivity.java:291)
                                                                               at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1562)
                                                                               at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1262)

Any one faced this issue? I am using s8, and have installed the arcore-preview apk. Strangely the app works independently (HelloAr Java), but when I integrated the app in my custom app, it gives me this exception.

**Comment by mshaileshr** [comment]
PlaneRenderer: Setting up to draw planes: glError 1282
E/MainActivity: Exception on the OpenGL thread
                                                                   java.lang.RuntimeException: Setting up to draw planes: glError 1282
                                                                       at com.contentstack.ar.rendering.ShaderUtil.checkGLError(ShaderUtil.java:65)
                                                                       at com.contentstack.ar.rendering.PlaneRenderer.drawPlanes(PlaneRenderer.java:359)
                                                                       at com.contentstack.ar.MainActivity.onDrawFrame(MainActivity.java:373)
                                                                       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1571)
                                                                       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)
01-23 11:06:09.633 10545-10575/com.contentstack.ar E/native: filter_update_base.cc:86 Temporary visual feature update failed when computing its residual and Jacobian.

**Comment by imknown** [comment]
The same on `Linux` + `Pixel 2 API 27 Google API x86 Image Rev. 4 emulator` + `AS 3.2 canary 4`:

```
02-26 14:31:32.653 6113-6113/? I/zygote: Not late-enabling -Xcheck:jni (already on)
02-26 14:31:32.663 6113-6113/? W/zygote: Unexpected CPU variant for X86 using defaults: x86
02-26 14:31:32.741 6113-6113/com.google.ar.core.examples.java.helloar W/es.java.helloar: type=1400 audit(0.0:38): avc: denied { read } for name="stat" dev="proc" ino=4026531999 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:proc_stat:s0 tclass=file permissive=0
02-26 14:31:32.753 6113-6113/com.google.ar.core.examples.java.helloar I/native: session_create.cc:71 ArSession_create with info: Entering
02-26 14:31:32.824 6113-6113/com.google.ar.core.examples.java.helloar I/zygote: The ClassLoaderContext is a special shared library.
02-26 14:31:32.821 6113-6113/com.google.ar.core.examples.java.helloar W/es.java.helloar: type=1400 audit(0.0:39): avc: denied { read } for name="stat" dev="proc" ino=4026531999 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:proc_stat:s0 tclass=file permissive=0
02-26 14:31:32.835 6113-6113/com.google.ar.core.examples.java.helloar I/native: version_check.cc:23 ARCore APK version:1.0.180129108, SDK version: 1.0.0
    session_create.cc:37 LoadDynamite with info: Dynamite load ok.
02-26 14:31:32.831 6113-6113/com.google.ar.core.examples.java.helloar W/es.java.helloar: type=1400 audit(0.0:40): avc: denied { read } for name="stat" dev="proc" ino=4026531999 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:proc_stat:s0 tclass=file permissive=0
02-26 14:31:32.846 6113-6113/com.google.ar.core.examples.java.helloar D/MtpDeviceJNI: register_android_mtp_MtpDevice
02-26 14:31:32.847 6113-6113/com.google.ar.core.examples.java.helloar I/native: session_create_implementation.cc:467 Entering ArSession_createImplementation. ARCore SDK version: [1.0.0].
02-26 14:31:32.864 6113-6113/com.google.ar.core.examples.java.helloar W/native: device_profile_proto_io.h:165 Camera id 0 frame rate not set.
    device_profile_proto_io.h:165 Camera id 1 frame rate not set.
    device_profile_proto_io.h:165 Camera id 2 frame rate not set.
    device_profile_proto_io.h:165 Camera id 3 frame rate not set.
02-26 14:31:32.865 6113-6113/com.google.ar.core.examples.java.helloar I/tango-ndk-hal: Found generic_x86: Setting LPF accel: 0.000 ms. gyro: 0.000 ms
02-26 14:31:32.866 6113-6113/com.google.ar.core.examples.java.helloar W/native: performance_manager.cc:18 Cannot get processor data.  Will not pin threads
02-26 14:31:32.868 6113-6113/com.google.ar.core.examples.java.helloar I/native: feature_matching_base.cc:38 Using gyro prediction for matching.
    feature_matcher_bin_manager.cc:157 Neighborhood radius for feature matcher bin-grid-0 is 21.2132 pixels.
    feature_matcher_bin_manager.cc:157 Neighborhood radius for feature matcher bin-grid-1 is 42.4264 pixels.
    feature_matcher_bin_manager.cc:157 Neighborhood radius for feature matcher bin-grid-2 is 64.1467 pixels.
    feature_matcher_bin_manager.cc:157 Neighborhood radius for feature matcher bin-grid-3 is 99.4286 pixels.
    feature_matcher_bin_manager.cc:157 Neighborhood radius for feature matcher bin-grid-4 is 148.18 pixels.
    gyro_feature_matching.cc:20 Running tracker at 10 Hz.
    vio_helper.cc:46 Use uncalibrated IMU scale factors.
    vio_helper.cc:58 Use uncalibrated IMU misalignment factors.
    data_manager.cc:78 Mapping Config: 
    ViwlsConfig: 
    OnlineMappingConfig: 
    enable_online_viwls: 1
    load_online_map_in_vio: 1
    enable_lite_com: 1
    incrementally_build_problem: 0
    
    MapFormulationConfig: 
    vio_drift_tolerance_rotation: 0.05
    vio_drift_tolerance_translation: 0.2
    enable_keypoint_pruning: 1
    enable_local_map_tracking: 1
    add_every_nth_keyframe: 3
    
    WLS_options: 
    estimate_camera_intrinsics: 0
    estimate_imu_camera_extrinsics: 0
    estimate_imu_intrinsics: 0
    calculate_keyframe_covariance: 0
    calculate_landmark_covariance: 0
    calculate_calibration_parameters_covariance: 0
    use_huber_loss_visual_cost_term: 1
    nonlinear_optimization_type: NLWLS
    num_outlier_rejection_loops: 1
    log_viwls_state_estimates_to_file: 0
    minimize_photometric_error: 0
    fail_on_missing_inv_depth_base_keyframe: 1
    enable_lite_com: 1
    ViwlsProblemType: kMarginalizedViwls
    incrementally_build_problem: 0
    
    MapSparsifierConfig: 
    enable_debug_output: 0
    marginalize_n_keyframes: 20
    retain_n_keyframes: 5
    enable_marginalization: 1
    
    MapLandmarkConfig: 
    min_landmark_observations: 5
    LandmarkParam: k3DInverseDepth
    min_depth_of_pointlandmark_from_image_plane: 0.05
    max_depth_of_pointlandmark_from_image_plane: 15
    landmark_covariance_use_approximation: 1
    keypoint_pixel_sigma: 1
    
    Debug_options: 
    simulator_export_state_error_sigma_info: 0
    log_visual_residuals: 0
    evaluation_log_directory: 
    
    
    DataManagerConfig: 
    visualization_enabled: 0
    execute_in_thread: 1
    enable_online_calibration: 0
    log_maps_for_visualization: 0
    fisheye_buffer_size: 7
    save_map_with_uuid_as_filename: 0
    save_map_filename: 
    evaluation_log_directory: 
    
    MapLifeCycleConfig: 
    save_map_for_structure_relocalization: 0
    enable_multi_map_merging: 1
    enable_time_base_map_split: 1
    
    MultiMapManagerConfig: 
    threshold_position_meters: 2
    threshold_orientation_radians: 0.174
    min_num_cross_adf_constraints: 9
    perform_full_multimap_optimization: 0
    merge_active_map_until_stable_coregistration: 1
    min_number_of_keyframes_to_add_adf: 25
02-26 14:31:32.919 6113-6113/com.google.ar.core.examples.java.helloar I/native: backend_base.h:55 LC-backend initialized.
02-26 14:31:32.923 6113-6113/com.google.ar.core.examples.java.helloar I/native: loop_detector_graph.cc:47 Initializing localizer with: loop_detector_engine: inverted_multi_index_pq
    low_power_localization: 0
    feature_descriptor: lens_invariant_ocvfreak
    override projection_matrix: 
    override quantizer: 
    override product quantizer: 
    max_num_of_image_to_image_matches: 1
    use_landmarks_for_relocalization: 0
    use_augmentation_with_previous_matches: 1
    verification_options:
    skip_bad_landmarks: 1
    overwrite_hamming_distance_threshold: -1
    min_geom_inlier_ratio: 0.35
    Ransac structure matching:
    min_num_points: 8
    max_iterations: 50
    confidence: 0.99
    sampson_error_threshold: 0.0008
    use_upright_pose_estimation: 1
    
    Ransac image to image matching:
    min_num_points: 8
    max_iterations: 50
    confidence: 0.99
    sampson_error_threshold: 0.0001
    use_upright_pose_estimation: 1
    
    compute_relative_pose_covariance: 0
    max_num_points_covariance_calc: 60
    min_match_image_time_difference: 10
    gravity_direction_threshold_degrees: 5
    matching_engine_options:
    projected_descriptor_dimensions: 16
    num_closest_words_for_nn_search: 30
    knn_search_epsilon: 2
    knn_max_radius: 100
    num_neighbors: -1
    vote_filter_type: covisibility-graph-filter
    use pose prior for image to image matching: 0
02-26 14:31:32.924 6113-6113/com.google.ar.core.examples.java.helloar I/native: device_provider.cc:715 Identified device type: kEmulator
    calibration_provider.cc:539 Instantiating calibration provider with sources:
    	CAD: 
    	Factory: 
    	Online: 
    	ActiveFile: kHardcodedCadModel
    	Hardcoded CAD model fallback: Disabled
    	Device type: kEmulator
    calibration_provider.cc:379 Successfully parsed requested Hardcoded CAD model for device type: kEmulator.
    tango_calibration_fetcher.cc:85 Fetched Camera Intrinsics from Tango
    tango_calibration_fetcher.cc:59 Camera Model Width/Height:640,480
    session_create_implementation.cc:557 ArSession_createImplementation returning OK.
02-26 14:31:32.937 6113-6113/com.google.ar.core.examples.java.helloar I/native: session.cc:260 Entering Session::Resume.
    android_camera.cc:1120 Initializing camera manager.
02-26 14:31:32.938 6113-6113/com.google.ar.core.examples.java.helloar I/native: android_camera.cc:1135 Camera manager initialized successfully with 1 cameras.
02-26 14:31:32.938 6113-6113/com.google.ar.core.examples.java.helloar E/NdkImageReader: AImageReader_getWindow
02-26 14:31:32.946 6113-6137/com.google.ar.core.examples.java.helloar I/native: cameras.cc:244 Camera changed state from 0 to 1: Camera device opened succesfully.
    cameras.cc:244 Camera changed state from 1 to 2: Capture session starting...
    cameras.cc:244 Camera changed state from 2 to 3: Capture session started streaming.
02-26 14:31:32.947 6113-6113/com.google.ar.core.examples.java.helloar I/tango-ndk-hal: Found calibrated gyro
    Found accelerometer
02-26 14:31:32.947 6113-6113/com.google.ar.core.examples.java.helloar I/native: session.cc:298 Session::Resume returning OK.
02-26 14:31:32.947 6113-6147/com.google.ar.core.examples.java.helloar I/tango-ndk-hal: Temperature sensor Goldfish Temperature sensor
    Gyro min delay 10000, using 10000
02-26 14:31:32.948 6113-6147/com.google.ar.core.examples.java.helloar I/tango-ndk-hal: Accel min delay 10000, using 10000
02-26 14:31:32.952 6113-6148/com.google.ar.core.examples.java.helloar D/OpenGLRenderer: HWUI GL Pipeline
02-26 14:31:33.043 6113-6148/com.google.ar.core.examples.java.helloar I/zygote: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
02-26 14:31:33.043 6113-6148/com.google.ar.core.examples.java.helloar I/OpenGLRenderer: Initialized EGL, version 1.4
02-26 14:31:33.043 6113-6148/com.google.ar.core.examples.java.helloar D/OpenGLRenderer: Swap behavior 1
02-26 14:31:33.101 6113-6148/com.google.ar.core.examples.java.helloar D/EGL_emulation: eglCreateContext: 0xd096b600: maj 3 min 0 rcv 3
02-26 14:31:33.132 6113-6148/com.google.ar.core.examples.java.helloar D/EGL_emulation: eglMakeCurrent: 0xd096b600: ver 3 0 (tinfo 0xd0affef0)
02-26 14:31:33.299 6113-6148/com.google.ar.core.examples.java.helloar D/EGL_emulation: eglMakeCurrent: 0xd096b600: ver 3 0 (tinfo 0xd0affef0)
02-26 14:31:33.300 6113-6129/com.google.ar.core.examples.java.helloar D/EGL_emulation: eglCreateContext: 0xe53840c0: maj 3 min 0 rcv 3
02-26 14:31:33.419 6113-6130/com.google.ar.core.examples.java.helloar I/native: arcore_feature_extractor_wrapper.cc:28 Extracting features using  ArcoreFeatureExtractorWrapper.
    arcore_feature_extractor_wrapper.cc:47 Narrow camera model.
02-26 14:31:33.466 6113-6132/com.google.ar.core.examples.java.helloar W/native: gyro_helper.cc:59 Gyro samples do not cover << [ 0 ; 692.609961004999946 ] sec. Use identity R. Gyro samples cover [ 692.352192360999993 ; 692.850111584000047 ] sec.
    feature_processing.cc:154 Skipping first feature measurement because we don't have a previous to diff against.
02-26 14:31:33.466 6113-6132/com.google.ar.core.examples.java.helloar I/native: vio_initializer.cc:648 Not accepting frame as first BA keyframe.
02-26 14:31:33.581 6113-6129/com.google.ar.core.examples.java.helloar D/EGL_emulation: eglMakeCurrent: 0xe53840c0: ver 3 0 (tinfo 0xe5383200)
02-26 14:31:33.624 6113-6129/com.google.ar.core.examples.java.helloar E/ObjectRenderer: Texture loading: glError 1282
02-26 14:31:33.634 6113-6129/com.google.ar.core.examples.java.helloar E/AndroidRuntime: FATAL EXCEPTION: GLThread 243
    Process: com.google.ar.core.examples.java.helloar, PID: 6113
    java.lang.RuntimeException: Texture loading: glError 1282
        at com.google.ar.core.examples.java.helloar.rendering.ShaderUtil.checkGLError(ShaderUtil.java:73)
        at com.google.ar.core.examples.java.helloar.rendering.ObjectRenderer.createOnGlThread(ObjectRenderer.java:128)
        at com.google.ar.core.examples.java.helloar.HelloArActivity.onSurfaceCreated(HelloArActivity.java:250)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1539)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)
02-26 14:31:33.749 6113-6113/com.google.ar.core.examples.java.helloar I/Choreographer: Skipped 31 frames!  The application may be doing too much work on its main thread.
02-26 14:31:33.764 6113-6132/com.google.ar.core.examples.java.helloar I/native: vio_initializer.cc:648 Not accepting frame as first BA keyframe.
02-26 14:31:33.825 6113-6132/com.google.ar.core.examples.java.helloar I/native: vio_initializer.cc:648 Not accepting frame as first BA keyframe.
02-26 14:31:34.332 6113-6113/com.google.ar.core.examples.java.helloar I/native: session.cc:303 Entering Session::Pause.
02-26 14:31:34.370 6113-6137/com.google.ar.core.examples.java.helloar I/native: cameras.cc:244 Camera changed state from 3 to 4: Capture session stopping...
02-26 14:31:34.582 6113-6125/com.google.ar.core.examples.java.helloar E/ACameraDevice: onDeviceIdle sending state cb
02-26 14:31:34.582 6113-6140/com.google.ar.core.examples.java.helloar I/native: android_camera.cc:1081 Capture sequence completed.
02-26 14:31:34.604 6113-6113/com.google.ar.core.examples.java.helloar I/native: android_camera.cc:1029 Capture session closed for camera 0
02-26 14:31:34.604 6113-6137/com.google.ar.core.examples.java.helloar I/native: cameras.cc:244 Camera changed state from 4 to 1: Capture session finished streaming.
02-26 14:31:34.643 6113-6113/com.google.ar.core.examples.java.helloar I/native: android_camera.cc:611 Reset cleanly got to CLOSED state for camera 0
    session.cc:332 Session::Pause returning OK.
02-26 14:31:34.643 6113-6137/com.google.ar.core.examples.java.helloar I/native: cameras.cc:244 Camera changed state from 1 to 0: Camera device closed succesfully.
02-26 14:31:34.644 6113-6113/com.google.ar.core.examples.java.helloar I/Choreographer: Skipped 53 frames!  The application may be doing too much work on its main thread.
02-26 14:31:34.715 6113-6148/com.google.ar.core.examples.java.helloar D/EGL_emulation: eglMakeCurrent: 0xd096b600: ver 3 0 (tinfo 0xd0affef0)
02-26 14:31:34.937 6113-6186/com.google.ar.core.examples.java.helloar V/StudioProfiler: Acquiring Application for Events
02-26 14:31:34.956 6113-6113/com.google.ar.core.examples.java.helloar V/StudioProfiler: Transformed class: java/net/URL
02-26 14:31:34.957 6113-6113/com.google.ar.core.examples.java.helloar W/zygote: Current dex file has more than one class in it. Calling RetransformClasses on this class might fail if no transformations are applied to it!
02-26 14:31:35.169 6113-6113/com.google.ar.core.examples.java.helloar V/StudioProfiler: Memory control stream started.
    StudioProfilers agent attached.
02-26 14:31:35.169 6113-6113/com.google.ar.core.examples.java.helloar I/Choreographer: Skipped 30 frames!  The application may be doing too much work on its main thread.
02-26 14:31:36.753 6113-6191/com.google.ar.core.examples.java.helloar V/StudioProfiler: Live memory tracking disabled.
02-26 14:31:36.754 6113-6191/com.google.ar.core.examples.java.helloar V/StudioProfiler: Live memory tracking enabled.
    JNIEnv not attached
02-26 14:31:36.766 6113-6191/com.google.ar.core.examples.java.helloar V/StudioProfiler: Loaded classes: 5321
02-26 14:31:36.844 6113-6191/com.google.ar.core.examples.java.helloar V/StudioProfiler: Tracking initialization took: 90004744ns
02-26 14:31:42.932 6113-6131/com.google.ar.core.examples.java.helloar W/native: analytics_logger.cc:189 Could not send event. Event will be dropped.
```

**Comment by inio** [comment]
@imknown that's a different error.  It's coming from ObjectRenderer.java:128 while the previous ones were from PlaneRenderer.java:359

@741g @tpsiaki Any clue what's going on in @imknown's post?

**Comment by 741g** [comment]
We'd have to know the user's GPU model here. Seems like a GPU driver issue. Please provide emulator -verbose command line output and logcat from device startup so we see the configuration.

**Comment by imknown** [comment]
@inio @741g @tpsiaki Thank you all~

Here's my avd boot cmd:
``` bash
#!/bin/bash
emulator -avd API-27 -http-proxy http://127.0.0.1:1081 -debug-proxy -dns-server 8.8.8.8 -use-system-libs -verbose
```

Logs below, and thank you all~

- [avd-boot.log](https://github.com/google-ar/arcore-android-sdk/files/1770391/avd-boot.log)
- [logcat-boot.log](https://github.com/google-ar/arcore-android-sdk/files/1770392/logcat-boot.log)

**Comment by 741g** [comment]
What hardware GPU do you have? It looks like you're using Mesa, which is definitely behind Swiftshader in terms of ES 3.0 conformance and behind many modern hardware GPU drivers as well:

03-01 08:40:50.999 1399-1399/? I/SurfaceFlinger: vendor    : Google (X.Org)
03-01 08:40:50.999 1399-1399/? I/SurfaceFlinger: renderer  : Android Emulator OpenGL ES Translator (AMD OLAND (DRM 2.50.0 / 4.13.0-36-generic, LLVM 5.0.0))
03-01 08:40:50.999 1399-1399/? I/SurfaceFlinger: version   : OpenGL ES 3.1 (4.5 (Core Profile) Mesa 17.2.8)

Can you tell us more about your hardware setup? glxinfo on command line can help.

Also, try to launch the emulator with -gpu swiftshader_indirect; that will use the Swiftshader software renderer which is more conformant with ES 3.0.

**Comment by 741g** [comment]
@inio Also, can I get more background on

    02-26 14:31:33.624 6113-6129/com.google.ar.core.examples.java.helloar E/ObjectRenderer: Texture loading: glError 1282

in terms of the sequence of GL calls? It's possible that we could trace down the exact driver bug that is affecting Mesa and Samsung, and de-risk the implementation so that it can work even with those drivers.

**Comment by inio** [comment]
@741g

The `Setting up to draw planes` error shows up on select Samsung S7 devices (we haven't been able to repro).

 `E/ObjectRenderer: Texture loading` is [here](https://github.com/google-ar/arcore-android-sdk/blob/master/samples/hello_ar_java/app/src/main/java/com/google/ar/core/examples/java/helloar/rendering/ObjectRenderer.java#L128).

**Comment by imknown** [comment]
@inio @741g 
Iam using:
`VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Oland XT [Radeon HD 8670 / R7 250/350] (rev 83)`.

No available drivers to be installed in the ubuntu `Additional Drivers`.

Totally i found that `hello_arcore_c` works fine with `ndk-bundle`.

**However...** The `XFCE Window` cannot get the focus to use <kbd>alt</kbd> to move around in the `VirtualCamera`. `Gnome` is ok.

**Comment by 741g** [comment]
@imknown I see, that seems to be an older AMD GPU that can have issues with OpenGL ES conformance. 

For the hello_arcore_c, do you mean that hello_arcore_c works while the Java version throws the 1282 error? That is a very important clue!

The XFCE Window problem is unexpected, hmm. Could explicitly clicking back in the emulator window to regain focus help things?

**Comment by imknown** [comment]
Thank you~

@741g Yes, the `Demo Java` raises the `gl error 1282`, and the `Demo C` does not throw any exceptions.

----

`Explicitly clicking the window multiply times` works for AVD normal screen and it regains **before i use `VitrualScene`**.

But the **new** `VitrualScene` in `System Camera App` and `ARCore Demo` lost focus immediately after the `main avd window` focus regained. I find that the `Press Alt to move camera.` dialog blinks when i **quickly continuously** press <kbd>alt</kbd>.

Already tried: https://stackoverflow.com/a/42720450/2782426

**Comment by jwmcglynn** [comment]
@imknown For the 1282 error, you can work around it by modifying HelloAR Java's ObjectRenderer.createOnGlThread, moving the shader loading code to the top of the function:

```java
    final int vertexShader =
        ShaderUtil.loadGLShader(TAG, context, GLES20.GL_VERTEX_SHADER, R.raw.object_vertex);
    final int fragmentShader =
        ShaderUtil.loadGLShader(TAG, context, GLES20.GL_FRAGMENT_SHADER, R.raw.object_fragment);

    program = GLES20.glCreateProgram();
    GLES20.glAttachShader(program, vertexShader);
    GLES20.glAttachShader(program, fragmentShader);
    GLES20.glLinkProgram(program);
    GLES20.glUseProgram(program);

    ShaderUtil.checkGLError(TAG, "Program creation");

    modelViewUniform = GLES20.glGetUniformLocation(program, "u_ModelView");
    modelViewProjectionUniform = GLES20.glGetUniformLocation(program, "u_ModelViewProjection");

    positionAttribute = GLES20.glGetAttribLocation(program, "a_Position");
    normalAttribute = GLES20.glGetAttribLocation(program, "a_Normal");
    texCoordAttribute = GLES20.glGetAttribLocation(program, "a_TexCoord");

    textureUniform = GLES20.glGetUniformLocation(program, "u_Texture");

    lightingParametersUniform = GLES20.glGetUniformLocation(program, "u_LightingParameters");
    materialParametersUniform = GLES20.glGetUniformLocation(program, "u_MaterialParameters");

    ShaderUtil.checkGLError(TAG, "Program parameters");
```

The error occurs when calling `glGenerateMipmap` before `glUseProgram`.  We're still investigating the root cause.

For the VirtualScene focus bug, I'm investigating and will follow up when I have more information.

**Comment by imknown** [comment]
@jwmcglynn Thanks, and it works~ Now the `Demo Java` does not crash nay more.

**Comment by jwmcglynn** [comment]
@imknown Here's a private build of the emulator on linux that should resolve your VirtualScene focus bug: https://drive.google.com/file/d/1tLRZbEimaC9V9TJpP5EhQlzk-xLkRtwN/view?usp=sharing

**Comment by imknown** [comment]
@jwmcglynn WOW, Thanks! The `VitualScene` bug is **gone**. Now I can move and look around when pressing the <kbd>Alt</kbd>. :laughing: :laughing: :laughing: 

P.S.: Other normal window focus bug is still there. So I cannot use the <kbd>Ctrl</kbd> and mouse to simulate the `double fingers actions`. The mouse wheel works fine. :laughing: :laughing: :laughing:

**Comment by FazalJarral** [comment]
@jwmcglynn 
```
final int vertexShader =
        ShaderUtil.loadGLShader(TAG, context, GLES20.GL_VERTEX_SHADER, VERTEX_SHADER_NAME);
    final int fragmentShader =
        ShaderUtil.loadGLShader(TAG, context, GLES20.GL_FRAGMENT_SHADER, FRAGMENT_SHADER_NAME);
```

    program = GLES20.glCreateProgram();
    GLES20.glAttachShader(program, vertexShader);
    GLES20.glAttachShader(program, fragmentShader);
    GLES20.glLinkProgram(program);
    GLES20.glUseProgram(program);

    ShaderUtil.checkGLError(TAG, "Program creation");`

Still receiving error `com.google.ar.core.examples.java.helloar E/HomeArFragment: Exception on the OpenGL thread
    java.lang.RuntimeException: after update: glError 1282
        at com.google.ar.core.examples.java.common.rendering.ShaderUtil.checkGLError(ShaderUtil.java:74)
        at com.google.ar.core.examples.java.common.rendering.PointCloudRenderer.update(PointCloudRenderer.java:122)
        at com.google.ar.core.examples.java.helloar.HomeArFragment.onDrawFrame(HomeArFragment.java:433)`

**Comment by sanchitpasricha** [comment]
Hi, I started flutter recently and experiencing an issue while running weather app on android emulator console is showing : 

**Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
√ Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...
Debug service listening on ws://127.0.0.1:54857/ZfaRaYtGseU=/ws
Syncing files to device Android SDK built for x86...
D/EGL_emulation( 5539): eglMakeCurrent: 0xf2a7f460: ver 2 0 (tinfo 0x9730ff20)
I/ppbrewery.clim( 5539): Background young concurrent copying GC freed 37943(1287KB) AllocSpace objects, 0(0B) LOS objects, 52% free, 1273KB/2671KB, paused 5.136ms total 22.739ms
I/ppbrewery.clim( 5539): Background young concurrent copying GC freed 37944(1287KB) AllocSpace objects, 0(0B) LOS objects, 52% free, 1279KB/2671KB, paused 5.585ms total 18.680ms**

Please help
Thanks !
