### ISSUE TITLE
HitResult.createAnchor() throws FatalException in situations where there are more appropriate exceptions

### ISSUE THREAD

**Issue by kunalmshah85** [google-ar/arcore-android-sdk#576]
I am constantly running hit test onupdate of frame to place /move my 3d model on detected hit. if I put my camera  against blocking surface (i.e. cover camera with hand or put phone on table) I am getting this exception.

09-21 13:10:07.331 22112-22112/com.test.my.myapplication1 E/native: session.cc:1095 FrameHitTest while not tracking. Returning empty list.
09-21 13:10:09.331 22112-22112/com.test.my.myapplication1 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.test.my.myapplication1, PID: 22112
    com.google.ar.core.exceptions.FatalException
        at com.google.ar.core.U.a(Unknown Source:2)
        at com.google.ar.core.Session.throwExceptionFromArStatus(Unknown Source:4)
        at com.google.ar.core.HitResult.nativeCreateAnchor(Native Method)
        at com.google.ar.core.HitResult.createAnchor(Unknown Source:6)
        at com.test.my.myapplication1.MainActivity.addOrMoveFlag(MainActivity.java:239)
        at com.test.my.myapplication1.MainActivity.onUpdate(MainActivity.java:124)
        at com.test.my.myapplication1.MainActivity.lambda$onCreate$0$MainActivity(MainActivity.java:67)
        at com.test.my.myapplication1.MainActivity$$Lambda$0.onUpdate(Unknown Source:2)
        at com.google.ar.sceneform.Scene.dispatchUpdate(Unknown Source:19)
        at com.google.ar.sceneform.SceneView.doUpdate(Unknown Source:18)
        at com.google.ar.sceneform.SceneView.doFrame(Unknown Source:22)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:655)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by inio** [comment]
From the stack trace it appears the hit test is failing because you're not tracking but you are later calling `HitResult.nativeCreateAnchor`.  Is it possible you're holding on to a HitResult from a previous frame?

**Comment by inio** [comment]
This is fixed in ARCore 1.6 which was released yesterday.

**Comment by sarimmehdi** [comment]
It doesn't say in the [documentation](https://developers.google.com/ar/reference/java/com/google/ar/core/HitResult#createAnchor-) that the function is supposed to throw a NotTrackingException. Can anyone have a look at it and update the documentation regarding this?
