### ISSUE TITLE
Crash due to java.util.concurrent.TimeoutException thrown in Session.finalize()

### ISSUE THREAD

**Issue by CrisBarreiro** [google-ar/arcore-android-sdk#735]
### SPECIFIC ISSUE ENCOUNTERED

ARCore crashes with the following exception:

```
Fatal Exception: java.util.concurrent.TimeoutException: com.google.ar.core.Session.finalize() timed out after 60 seconds
       at android.os.MessageQueue.nativeWake(MessageQueue.java)
       at android.os.MessageQueue.quit(MessageQueue.java:433)
       at android.os.Looper.quit(Looper.java:268)
       at android.os.HandlerThread.quit(HandlerThread.java:126)
       at com.google.ar.persistence.AnchorServiceClient.shutdownChannel(PG:26)
       at com.google.ar.core.Session.nativeDestroySession(Session.java)
       at com.google.ar.core.Session.finalize(Session.java:52)
       at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:252)
       at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:239)
       at java.lang.Daemons$Daemon.run(Daemons.java:105)
       at java.lang.Thread.run(Thread.java:764)
```

A very similar problem was reported on issue #569 and was supposed to be fixed on version 1.5

### VERSIONS USED
- Android Studio: 3.3
- ARCore SDK for Android: 1.7.0
- Device manufacturer, model, and O/S: Xiaomi Mi 8 (MIUI 10.0.3.0, Android 8.1.0)
- ARCore: 
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell getprop ro.build.fingerprint`: 

  Packages:
      versionName=1.7.190128146

### STEPS TO REPRODUCE THE ISSUE
 1. Start and stop ARCore several times

**Comment by devbridie** [comment]
As a part of ongoing efforts to maintain ARCore repositories, I’m closing this issue as stale since it hasn’t had activity in more than 6 months. If this issue is still relevant, please feel free to file a new bug using the latest version of the SDK.
