### ISSUE TITLE
NoClassDefFoundError for Ljava/time/Duration when hosting cloud anchors

### ISSUE THREAD

**Issue by hellmers-intech** [google-ar/arcore-android-sdk#755]
### SPECIFIC ISSUE ENCOUNTERED
When trying to host cloud anchor, my app encounters a ClassNotFound exception within ARCore.

I'm writing a small app to test anchors and especially cloud anchors in ARCore.
Until yesterday I could create and host anchors for placing objects into the virtual scene just fine.
Since yesterday around noon (UTC+1) I cannot host my anchors anymore.
I noticed that this might be coinciding with the 1.8.0 update published yesterday, but I might be wrong.

The problem appears to be a NoClassDefFoundError within the android ARCore build, when invoking session.hostCloudAnchor(anchor).
The particular class that cannot be found is Ljava/time/Duration.
I managed to reproduce the Error with the [cloud_anchor_java](https://github.com/google-ar/arcore-android-sdk/tree/master/samples/cloud_anchor_java) sample from the current version of the arcore-android-sdk.
I am using the [compile options](https://developer.android.com/studio/write/java8-support) for java 1.8 compatibility.

The assosiated Logcat is the following.

```
2019-03-29 17:35:58.530 14112-14480/com.google.ar.core.examples.java.cloudanchor I/native: viwls_optimization.cc:972 Skip Lite-COM due to a significant calibration change.
2019-03-29 17:35:58.574 14112-14469/com.google.ar.core.examples.java.cloudanchor E/native: hit_test.cc:376 generic::internal: No point hit.
2019-03-29 17:35:58.664 14112-14480/com.google.ar.core.examples.java.cloudanchor I/native: viwls_optimization.cc:822 MAP SOLVE: USER_SUCCESS
2019-03-29 17:35:58.680 14112-14480/com.google.ar.core.examples.java.cloudanchor I/native: visual_inertial_wls.cc:254 online_viwls_solve_time in seconds = 0.177783 solve_time_counter_ = 0
2019-03-29 17:35:58.721 14112-14480/com.google.ar.core.examples.java.cloudanchor I/native: multi_map_manager.cc:444 Added ADF into multi_map_manager: daf44c3b-07de-2720-8d85-032a7fb75237
2019-03-29 17:35:58.783 14112-14481/com.google.ar.core.examples.java.cloudanchor W/native: data_manager.cc:273 Switching to track map: daf44c3b-07de-2720-8d85-032a7fb75237
2019-03-29 17:35:58.785 14112-14481/com.google.ar.core.examples.java.cloudanchor I/native: data_manager.cc:593 Refined adf_T_C from: q = [x: 0.576987, y: -0.536491, z: -0.467836, w: 0.40049], p = [x: -0.0117239, y: -0.102585, z: 0.0220459]
    to: q = [x: 0.571755, y: -0.541654, z: -0.461819, w: 0.407959], p = [x: -0.0126145, y: -0.107553, z: 0.00727392]
    rotation change: 1.38479(deg), position change: 0.0156103(m).
2019-03-29 17:35:58.893 14112-14473/com.google.ar.core.examples.java.cloudanchor I/native: pose_manager.cc:212 World pose node changing to MapId:daf44c3b-07de-2720-8d85-032a7fb75237 with 1 opt.
2019-03-29 17:35:59.023 14112-14485/com.google.ar.core.examples.java.cloudanchor V/third_party/redwood/base/jni_common/jni_helper.cc: JniHelper: attached thread (Called from line 167).
2019-03-29 17:35:59.026 14112-14485/com.google.ar.core.examples.java.cloudanchor W/System.err: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Duration;
2019-03-29 17:35:59.026 14112-14485/com.google.ar.core.examples.java.cloudanchor W/System.err:     at atz.<init>(PG:8)
2019-03-29 17:35:59.026 14112-14485/com.google.ar.core.examples.java.cloudanchor W/System.err:     at atg.<init>(PG:4)
2019-03-29 17:35:59.026 14112-14485/com.google.ar.core.examples.java.cloudanchor W/System.err:     at com.google.ar.persistence.AnchorServiceClient.hostAnchor(PG:65)
2019-03-29 17:35:59.026 14112-14485/com.google.ar.core.examples.java.cloudanchor W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "java.time.Duration" on path: DexPathList[[zip file "/data/app/com.google.ar.core-1/base.apk"],nativeLibraryDirectories=[/data/app/com.google.ar.core-1/lib/arm64, /data/app/com.google.ar.core-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
2019-03-29 17:35:59.026 14112-14485/com.google.ar.core.examples.java.cloudanchor W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
2019-03-29 17:35:59.026 14112-14485/com.google.ar.core.examples.java.cloudanchor W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
2019-03-29 17:35:59.026 14112-14485/com.google.ar.core.examples.java.cloudanchor W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
2019-03-29 17:35:59.026 14112-14485/com.google.ar.core.examples.java.cloudanchor W/System.err: 	... 3 more
2019-03-29 17:35:59.026 14112-14485/com.google.ar.core.examples.java.cloudanchor V/third_party/redwood/base/jni_common/jni_helper.cc: ~JniHelper: about to detach thread (Called from line 167).
2019-03-29 17:35:59.026 14112-14485/com.google.ar.core.examples.java.cloudanchor V/third_party/redwood/base/jni_common/jni_helper.cc: ~JniHelper: detached thread (Called from line 167).
2019-03-29 17:35:59.026 14112-14485/com.google.ar.core.examples.java.cloudanchor I/native: hotspot_anchor_hoster.cc:210 Hosting anchor status: ArStatusErrorSpace::AR_ERROR_FATAL: The method call on the Java Client failed.
```

### VERSIONS USED
- Android Studio: 3.3.2
- ARCore SDK for Android: 1.8.0
- Device manufacturer, model, and O/S: ASUS, Zenfone ARES (ASUS_A002), Android 7.0
- ARCore: 1.8.190311076
- Output of `adb shell getprop ro.build.fingerprint`: asus/WW_ASUS_A002/ASUS_A002:7.0/NRD90M/14.1600.1712.41-20171227:user/release-keys

### STEPS TO REPRODUCE THE ISSUE
 1. Open cloud_anchor_java project in android studio
 1. Comment out any firebase related code, since I am not using this, but set currentMode to HOSTING when tapping on the HOST button
 1. Add API key for cloud anchors
 1. Start the app, enter hosting mode and tap anywhere on the screen. Andy appears but the cloud anchor is not being hosted

I've uploaded a diff of the sample project for easier reproduction, since the git.bundle file was too large. 
[bug_diff.txt](https://github.com/google-ar/arcore-android-sdk/files/3023658/bug_diff.txt)

**Comment by devbridie** [comment]
I think this should be solved at this point-- I can't repro nor do I see any references to java8 time APIs. If this still affects you, please feel free to open a new issue.
