### ISSUE TITLE
I receive this message "The device does not support AR":

### ISSUE THREAD

**Issue by Rwaldrighi** [google-ar/arcore-android-sdk#8]
08-29 17:26:06.576 5397-5397/com.google.ar.core.examples.java.helloar E/SupportedDevices: Device calibration unavailable.

08-29 17:27:05.393 5397-5397/com.google.ar.core.examples.java.helloar E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                        Process: com.google.ar.core.examples.java.helloar, PID: 5397
                                                                                        java.lang.IllegalArgumentException: width must be greater than zero
                                                                                            at com.google.ar.core.Session.setDisplayGeometry(Session.java:631)
                                                                                            at com.google.ar.core.Session$3.onDisplayChanged(Session.java:863)
                                                                                            at android.hardware.display.DisplayManagerGlobal$DisplayListenerDelegate.handleMessage(DisplayManagerGlobal.java:462)
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:6186)
                                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by benexus** [comment]
Only Pixel and Samsung S8 are supported right now

**Comment by Rwaldrighi** [comment]
Ok. Tks.
