### ISSUE TITLE
glError 1282 while using the last version of HelloAr application

### ISSUE THREAD

**Issue by kasraouiii** [google-ar/arcore-android-sdk#813]
Hi guys, I am trying the arcore in one of my apps, and I get stuck at this point, where it gives me a glError 1282.

E/HelloArActivity: Exception on the OpenGL thread
    java.lang.RuntimeException: after update: glError 1282
        at .common.rendering.ShaderUtil.checkGLError(ShaderUtil.java:75)
        at .common.rendering.PointCloudRenderer.update(PointCloudRenderer.java:124)
        at .helloar.HelloArActivity.onDrawFrame(HelloArActivity.java:343)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1571)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)
Any one faced this issue? I am using A8, and have installed the arcore-preview apk. Strangely the app works independently (HelloAr Java), but when I integrated the app in my custom app, it gives me this exception.

**Comment by mraznysmh** [comment]
Facing same problem, anyone help?

**Comment by devbridie** [comment]
For anybody else coming across this-- glError 1282 means that the renderers couldn't find the vertex and fragment shaders. Make sure you've included all of the necessary shader files.

Closing due to age, but feel free to open a new issue if you're still having problems.
