### ISSUE TITLE
Android Instant App and arcore

### ISSUE THREAD

**Issue by tillkrempel** [google-ar/arcore-android-sdk#83]
As of now it is needed to install the APK to be able to use the ARCore preview, as it seems to wrap up the TangoService implementation. In an attempt to port an existing ARCore application into an instant app, we now have the problem that the ARCore preview depends on the TangoService implementation, which, as it resides in a different APK, cannot be accessed from an instant app. 

Therefore the "installed" module works fine, the "instant" module crashes when updating the the session frame, with the exception 

 ```
 java.lang.UnsatisfiedLinkError: No implementation found for int com.google.atap.tango.TangoJNINative.Initialize(android.content.Context) (tried Java_com_google_atap_tango_TangoJNINative_Initialize and Java_com_google_atap_tango_TangoJNINative_Initialize__Landroid_content_Context_2)
                                                   at com.google.atap.tango.TangoJNINative.Initialize(Native Method)
                                                   at com.google.atap.tangoservice.Tango.<init>(Tango.java:385)
                                                   at com.google.ar.core.TangoWrapper.createInstance(TangoWrapper.java:32)
                                                   at com.google.ar.core.Session.bindTangoService(Session.java:425)
                                                   at com.google.ar.core.Session.resume(Session.java:153)
```

Is it planned to integrate the service implementation into a gradle dependency in a way that it can be used without the requirement to install a separate APK first ?

**Comment by inio** [comment]
Thanks for the report.

With the release of Developer Preview 2, we *think* this works now.  Please let us know!

**Comment by tillkrempel** [comment]
Yes, I can confirm that it works with the developer preview 2.
