### ISSUE TITLE
Crash on ArSession_createWithFeatures: The AnchorServiceClient could not be created

### ISSUE THREAD

**Issue by Dings3** [google-ar/arcore-android-sdk#850]
### SPECIFIC ISSUE ENCOUNTERED

Any app crashes when starting the AR session.
For example the [Hello Sceneform app](https://github.com/google-ar/sceneform-android-sdk/tree/master/samples/hellosceneform).

Crash log:

```
08-29 09:31:00.019 F/DEBUG   (20146): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
08-29 09:31:00.019 F/DEBUG   (20146): Build fingerprint: 'samsung/dream2qltesq/dream2qltesq:7.0/NRD90M/G955USQS1AQI6:user/release-keys'
08-29 09:31:00.019 F/DEBUG   (20146): Revision: '12'
08-29 09:31:00.019 F/DEBUG   (20146): ABI: 'arm64'
08-29 09:31:00.019 F/DEBUG   (20146): pid: 20082, tid: 20082, name: .hellosceneform  >>> com.google.ar.sceneform.samples.hellosceneform <<<
08-29 09:31:00.019 F/DEBUG   (20146): signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
08-29 09:31:00.023 F/DEBUG   (20146): Abort message: 'anchor_service_client.cc:24 Check failed: obj != nullptr The AnchorServiceClient could not be created.
08-29 09:31:00.023 F/DEBUG   (20146): '
08-29 09:31:00.023 F/DEBUG   (20146):     x0   0000000000000000  x1   0000000000004e72  x2   0000000000000006  x3   0000000000000008
08-29 09:31:00.023 F/DEBUG   (20146):     x4   0000007f76002140  x5   0000007f75e0c6a0  x6   0000007f526e6c1a  x7   0000000003f00ba8
08-29 09:31:00.023 F/DEBUG   (20146):     x8   0000000000000083  x9   0000007f7a970a98  x10  86259e0ec5cf1163  x11  86259e0ec5cf1163
08-29 09:31:00.023 F/DEBUG   (20146):     x12  0000000000000000  x13  0000000000000020  x14  ffffffffffffffdf  x15  0000007f783a4810
08-29 09:31:00.023 F/DEBUG   (20146):     x16  0000007f78399ee0  x17  0000007f7833a6bc  x18  00000000000000da  x19  0000007f7a970b40
08-29 09:31:00.023 F/DEBUG   (20146):     x20  0000000000000006  x21  0000007f7a970a98  x22  0000000000000000  x23  0000000000000018
08-29 09:31:00.023 F/DEBUG   (20146):     x24  0000007fd6793e08  x25  0000007f7a970b30  x26  0000007fd6793f70  x27  000000000000009d
08-29 09:31:00.023 F/DEBUG   (20146):     x28  00000000002000ad  x29  0000007fd6793cd0  x30  0000007f78337924
08-29 09:31:00.023 F/DEBUG   (20146):     sp   0000007fd6793cb0  pc   0000007f7833a6c4  pstate 0000000060000000
08-29 09:31:00.028 D/SystemUI_Clock( 1958): Clock received ACTION_TIME_TICK : start
08-29 09:31:00.029 D/SystemUI_Clock( 1958): Clock received ACTION_TIME_TICK : end
08-29 09:31:00.032 I/Finsky  (14410): [1] ryz.a(57): Skipping DFE self-update. Local Version [81633600] >= Server Version [-1]
08-29 09:31:00.034 F/DEBUG   (20146): 
08-29 09:31:00.034 F/DEBUG   (20146): backtrace:
08-29 09:31:00.035 F/DEBUG   (20146):     #00 pc 000000000007a6c4  /system/lib64/libc.so (tgkill+8)
08-29 09:31:00.035 F/DEBUG   (20146):     #01 pc 0000000000077920  /system/lib64/libc.so (pthread_kill+64)
08-29 09:31:00.035 F/DEBUG   (20146):     #02 pc 000000000002538c  /system/lib64/libc.so (raise+24)
08-29 09:31:00.035 F/DEBUG   (20146):     #03 pc 000000000001d24c  /system/lib64/libc.so (abort+52)
08-29 09:31:00.035 F/DEBUG   (20146):     #04 pc 0000000001e8a60c  /data/app/com.google.ar.core-2/lib/arm64/libarcore_c.so (offset 0xd2d000)
08-29 09:31:00.035 F/DEBUG   (20146):     #05 pc 0000000001e8a5e4  /data/app/com.google.ar.core-2/lib/arm64/libarcore_c.so (offset 0xd2d000)
08-29 09:31:00.035 F/DEBUG   (20146):     #06 pc 0000000001e89e04  /data/app/com.google.ar.core-2/lib/arm64/libarcore_c.so (offset 0xd2d000)
08-29 09:31:00.035 F/DEBUG   (20146):     #07 pc 0000000001e8a7f4  /data/app/com.google.ar.core-2/lib/arm64/libarcore_c.so (offset 0xd2d000)
08-29 09:31:00.035 F/DEBUG   (20146):     #08 pc 0000000000d9472c  /data/app/com.google.ar.core-2/lib/arm64/libarcore_c.so (offset 0xd2d000)
08-29 09:31:00.035 F/DEBUG   (20146):     #09 pc 0000000000d3f10c  /data/app/com.google.ar.core-2/lib/arm64/libarcore_c.so (offset 0xd2d000)
08-29 09:31:00.035 F/DEBUG   (20146):     #10 pc 0000000000d36678  /data/app/com.google.ar.core-2/lib/arm64/libarcore_c.so (offset 0xd2d000)
08-29 09:31:00.035 F/DEBUG   (20146):     #11 pc 0000000000d37aa8  /data/app/com.google.ar.core-2/lib/arm64/libarcore_c.so (offset 0xd2d000)
08-29 09:31:00.035 F/DEBUG   (20146):     #12 pc 0000000000d2e3b4  /data/app/com.google.ar.core-2/lib/arm64/libarcore_c.so (offset 0xd2d000)
08-29 09:31:00.035 F/DEBUG   (20146):     #13 pc 00000000000087a4  /data/app/com.google.ar.sceneform.samples.hellosceneform-1/lib/arm64/libarcore_sdk_c.so (offset 0x8000) (ArSession_createWithFeatures+128)
08-29 09:31:00.035 F/DEBUG   (20146):     #14 pc 000000000000f578  /data/app/com.google.ar.sceneform.samples.hellosceneform-1/lib/arm64/libarcore_sdk_jni.so (offset 0xc000) (Java_com_google_ar_core_Session_nativeCreateSessionAndWrapperWithFeatures+72)
08-29 09:31:00.035 F/DEBUG   (20146):     #15 pc 000000000032dce4  /data/app/com.google.ar.sceneform.samples.hellosceneform-1/oat/arm64/base.odex (offset 0x2ec000)
```

### VERSIONS USED
- Android Studio: 3.5

Device manufacturer, model, and O/S: 
Samsung S8+, Android 7.0

ARCore Version: SDK build name: 1.11
 version_check.cc:23 ARCore Version: APK version:1.11.190715106
version_check.cc:24 ARCore Version: emulated SDK version:1.11.190708000

Build fingerprint: 'samsung/dream2qltesq/dream2qltesq:7.0/NRD90M/G955USQS1AQI6:user/release-keys'

### STEPS TO REPRODUCE THE ISSUE
 1. Install Hello Sceneform or any app using ARCore
 2. Start app

### ADDITIONAL INFO

The logs also contain this output, before the crash:

```
08-29 09:30:59.623 I/ARCore-SetupContentResolver(20082): Post-install failed
08-29 09:30:59.623 I/ARCore-SetupContentResolver(20082): java.lang.IllegalArgumentException: Unknown URI content://com.google.ar.core.services.arcorecontentprovider
08-29 09:30:59.623 I/ARCore-SetupContentResolver(20082): 	at android.content.ContentResolver.call(ContentResolver.java:1446)
08-29 09:30:59.623 I/ARCore-SetupContentResolver(20082): 	at com.google.ar.core.aj.b(SetupContentResolver.java:12)
08-29 09:30:59.623 I/ARCore-SetupContentResolver(20082): 	at com.google.ar.core.h.a(ArCoreApkImpl.java:75)
08-29 09:30:59.623 I/ARCore-SetupContentResolver(20082): 	at com.google.ar.core.h.requestInstall(ArCoreApkImpl.java:39)
08-29 09:30:59.623 I/ARCore-SetupContentResolver(20082): 	at com.google.ar.core.h.requestInstall(ArCoreApkImpl.java:74)
08-29 09:30:59.623 I/ARCore-SetupContentResolver(20082): 	at com.google.ar.sceneform.ux.BaseArFragment.requestInstall(BaseArFragment.java:320)
08-29 09:30:59.623 I/ARCore-SetupContentResolver(20082): 	at com.google.ar.sceneform.ux.BaseArFragment.initializeSession(BaseArFragment.java:350)
08-29 09:30:59.623 I/ARCore-SetupContentResolver(20082): 	at com.google.ar.sceneform.ux.BaseArFragment.onResume(BaseArFragment.java:313)
08-29 09:30:59.623 I/ARCore-SetupContentResolver(20082): 	at android.support.v4.app.Fragment.performResume(Fragment.java:2498)
08-29 09:30:59.623 I/ARCore-SetupContentResolver(20082): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1501)
08-29 09:30:59.623 I/ARCore-SetupContentResolver(20082): 	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
08-29 09:30:59.623 I/ARCore-SetupContentResolver(20082): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
08-29 09:30:59.623 I/ARCore-SetupContentResolver(20082): 	at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
08-29 09:30:59.623 I/ARCore-SetupContentResolver(20082): 	at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:3241)
08-29 09:30:59.623 I/ARCore-SetupContentResolver(20082): 	at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:223)
08-29 09:30:59.623 I/ARCore-SetupContentResolver(20082): 	at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:538)
08-29 09:30:59.623 I/ARCore-SetupContentResolver(20082): 	at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:527)
08-29 09:30:59.623 I/ARCore-SetupContentResolver(20082): 	at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:172)
08-29 09:30:59.623 I/ARCore-SetupContentResolver(20082): 	at android.app.Activity.performResume(Activity.java:7125)
08-29 09:30:59.623 I/ARCore-SetupContentResolver(20082): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3821)
08-29 09:30:59.623 I/ARCore-SetupContentResolver(20082): 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3885)
08-29 09:30:59.623 I/ARCore-SetupContentResolver(20082): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1692)
08-29 09:30:59.623 I/ARCore-SetupContentResolver(20082): 	at android.os.Handler.dispatchMessage(Handler.java:102)
08-29 09:30:59.623 I/ARCore-SetupContentResolver(20082): 	at android.os.Looper.loop(Looper.java:154)
08-29 09:30:59.623 I/ARCore-SetupContentResolver(20082): 	at android.app.ActivityThread.main(ActivityThread.java:6776)
08-29 09:30:59.623 I/ARCore-SetupContentResolver(20082): 	at java.lang.reflect.Method.invoke(Native Method)
08-29 09:30:59.623 I/ARCore-SetupContentResolver(20082): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
08-29 09:30:59.623 I/ARCore-SetupContentResolver(20082): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
08-29 09:30:59.623 W/ChimeraUtils(19027): Non Chimera context
08-29 09:30:59.625 I/third_party/arcore/ar/core/android/sdk/session_create.cc(20082): Entering ArSession_createWithFeatures
08-29 09:30:59.625 I/third_party/arcore/ar/core/android/sdk/session_create.cc(20082): ARCore Version: SDK build name: 1.11
```

**Comment by sandyfriend** [comment]
Could you try to download ARCore from Samsung App store, then try again.
It seem the problem related with Whitelist app list on Samsung side.

**Comment by alexey-pelykh** [comment]
@sandyfriend ARCore is different in Samsung App store?

**Comment by Dings3** [comment]
Downloading ARCore from the Samsung App store solves it.
But how can we enforce the correct version to be installed at runtime?

**Comment by sandyfriend** [comment]
ARCore are the same, while the ROM are not, some OEM have their own control on list of the "good" App. Install through their official channel will solve the problem.

**Comment by Dings3** [comment]
We investigated the issue more.
Even uninstalling ARCore and reinstalling from Google play store solves the issue temporarily.
However, every time the device it restarted, this same crash will happen again and ARCore must be reinstalled - no matter from which store.

**Comment by devbridie** [comment]
My understanding is that this issue has been resolved, so I'll close the issue. If you're still seeing this, please feel free to create a new issue.
