### ISSUE TITLE
Crash on mSession.onResume (problem with IObjectWrapper)

### ISSUE THREAD

**Issue by rcroset** [google-ar/arcore-android-sdk#87]
My app crashes on the call of mSession.onResume (IllegalArgumentException). Here's the stacktrace:

> java.lang.RuntimeException: Unable to resume activity {org.myapp/org.myapp.plugin.map.android.ItineraryActivity}: java.lang.IllegalArgumentException: The concrete class implementing IObjectWrapper must have exactly *one* declared private field for the wrapped object.  Preferably, this is an instance of the ObjectWrapper<T> class.
>                                                                     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3844)
>                                                                     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3885)
>                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3051)
>                                                                     at android.app.ActivityThread.-wrap14(ActivityThread.java)
>                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
>                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
>                                                                     at android.os.Looper.loop(Looper.java:154)
>                                                                     at android.app.ActivityThread.main(ActivityThread.java:6776)
>                                                                     at java.lang.reflect.Method.invoke(Native Method)
>                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
>                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
>                                                                  Caused by: java.lang.IllegalArgumentException: The concrete class implementing IObjectWrapper must have exactly *one* declared private field for the wrapped object.  Preferably, this is an instance of the ObjectWrapper<T> class.
>                                                                     at com.google.tango.loader.ObjectWrapper.unwrap(ObjectWrapper.java:93)
>                                                                     at com.google.tango.jni.TangoCameraNative.initialize(TangoCameraNative.java:56)
>                                                                     at com.google.tango.loader.ITangoCameraNative$Stub.onTransact(ITangoCameraNative.java:57)
>                                                                     at android.os.Binder.transact(Binder.java:507)
>                                                                     at com.google.tango.loader.ITangoCameraNative$Stub$Proxy.initialize(ITangoCameraNative.java:275)
>                                                                     at java.lang.RuntimeException: Unable to resume activity {org.myapp/org.myapp.plugin.map.android.ItineraryActivity}: java.lang.IllegalArgumentException: The concrete class implementing IObjectWrapper must have exactly *one* declared private field for the wrapped object.  Preferably, this is an instance of the ObjectWrapper<T> class.
                                                                    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3844)
                                                                    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3885)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3051)
                                                                    at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:154)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
                                                                 Caused by: java.lang.IllegalArgumentException: The concrete class implementing IObjectWrapper must have exactly *one* declared private field for the wrapped object.  Preferably, this is an instance of the ObjectWrapper<T> class.
                                                                    at com.google.tango.loader.ObjectWrapper.unwrap(ObjectWrapper.java:93)
                                                                    at com.google.tango.jni.TangoCameraNative.initialize(TangoCameraNative.java:56)
                                                                    at com.google.tango.loader.ITangoCameraNative$Stub.onTransact(ITangoCameraNative.java:57)
                                                                    at android.os.Binder.transact(Binder.java:507)
                                                                    at com.google.tango.loader.ITangoCameraNative$Stub$Proxy.initialize(ITangoCameraNative.java:275)
                                                                    at com.google.atap.tangoservice.TangoCameraNativeLoader.initialize(TangoCameraNativeLoader.java:61)
                                                                    at com.google.atap.tangoservice.Tango.<init>(Tango.java:390)
                                                                    at com.google.ar.core.TangoWrapper.createInstance(TangoWrapper.java:32)
                                                                    at com.google.ar.core.Session.bindTangoService(Session.java:425)
                                                                    at com.google.ar.core.Session.resume(Session.java:153)
                                                                    at org.myapp.plugin.map.android.ItineraryActivity.lambda$resumeSession$0$ItineraryActivity(ItineraryActivity.java:209)
                                                                    at org.myapp.plugin.map.android.ItineraryActivity$$Lambda$0.run(Unknown Source)
                                                                    at android.app.Activity.runOnUiThread(Activity.java:6058)
                                                                    at org.myapp.plugin.map.android.ItineraryActivity.resumeSession(ItineraryActivity.java:208)
                                                                    at org.myapp.plugin.map.android.ItineraryActivity.onResume(ItineraryActivity.java:200)
                                                                    at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1277)
                                                                    at android.app.Activity.performResume(Activity.java:7103)
                                                                    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3821)
                                                                    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3885) 
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3051) 
                                                                    at android.app.ActivityThread.-wrap14(ActivityThread.java) 
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                    at android.os.Looper.loop(Looper.java:154) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:6776) 
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410) com.google.atap.tangoservice.TangoCameraNativeLoader.initialize(TangoCameraNativeLoader.java:61)
>                                                                     at com.google.atap.tangoservice.Tango.<init>(Tango.java:390)
>                                                                     at com.google.ar.core.TangoWrapper.createInstance(TangoWrapper.java:32)
>                                                                     at com.google.ar.core.Session.bindTangoService(Session.java:425)
>                                                                     at com.google.ar.core.Session.resume(Session.java:153)
>                                                                     at org.myapp.plugin.map.android.ItineraryActivity.lambda$resumeSession$0$ItineraryActivity(ItineraryActivity.java:209)
>                                                                     at org.myapp.plugin.map.android.ItineraryActivity$$Lambda$0.run(Unknown Source)
>                                                                     at android.app.Activity.runOnUiThread(Activity.java:6058)
>                                                                     at org.myapp.plugin.map.android.ItineraryActivity.resumeSession(ItineraryActivity.java:208)
>                                                                     at org.myapp.plugin.map.android.ItineraryActivity.onResume(ItineraryActivity.java:200)
>                                                                     at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1277)
>                                                                     at android.app.Activity.performResume(Activity.java:7103)
>                                                                     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3821)
>                                                                     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3885) 
>                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3051) 
>                                                                     at android.app.ActivityThread.-wrap14(ActivityThread.java) 
>                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642) 
>                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
>                                                                     at android.os.Looper.loop(Looper.java:154) 
>                                                                     at android.app.ActivityThread.main(ActivityThread.java:6776) 
>                                                                     at java.lang.reflect.Method.invoke(Native Method) 
>                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520) 
>                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

As I saw on issue #61 it was advised to switch to gradle 2.3.3. But I can't, since I'm working on an already existing app with gradle 4.1 (due to dependencies to other stuff). It was running good with gradle 3.5, the bug appeared right after the upgrade to gradle 4.1.

Is there any way to solve this ?

Thanks

**Comment by llDavidll** [comment]
Hi, 
This issue seems to be related to instant run. Disabling it worked for me (Settings -> Build, Execution, Deployment -> Instant Run -> uncheck the first checkbox).
Instant run in version 3.0.x of the gradle plugin must in some way trigger the initialization of a class two times, and this class does not seems to like it.

**Comment by inio** [comment]
Does this issue occur with Developer Preview 2 as well (released today)?

**Comment by rcroset** [comment]
The problem is solved with the Developer Preview 2. Thanks a lot !
