### ISSUE TITLE
FatalException: DeadlineExceededException 

### ISSUE THREAD

**Issue by Tushar-kant-Deo** [google-ar/arcore-android-sdk#896]
when using acquireCameraImage on Scene's Update listener of AugmentedFace Fragment, it is throwing , "com.google.ar.core.exceptions.DeadlineExceededException". 

Code :
Image img = frame.acquireCameraImage();
Bitmap bmp = imageToBitmap(img);
iv.setImageBitmap( bmp );
img.close();

Intention: To acquire camera frame for further image-processing using Face Mesh information.

Log is :- 
2019-09-24 14:17:52.202 17007-17007/com.google.ar.sceneform.samples.augmentedfaces E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.ar.sceneform.samples.augmentedfaces, PID: 17007
    com.google.ar.core.exceptions.DeadlineExceededException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at com.google.ar.core.Session.throwExceptionFromArStatus(Session.java:134)
        at com.google.ar.core.Frame.nativeAcquireCameraImage(Native Method)
        at com.google.ar.core.Frame.acquireCameraImage(Frame.java:62)
        at com.google.ar.sceneform.samples.augmentedfaces.AugmentedFacesActivity.lambda$onCreate$3(AugmentedFacesActivity.java:207)
        at com.google.ar.sceneform.samples.augmentedfaces.-$$Lambda$AugmentedFacesActivity$inBzZloo4XD88nYvPTugi_uRy5g.onUpdate(Unknown Source:6)
        at com.google.ar.sceneform.Scene.dispatchUpdate(SourceFile:111)
        at com.google.ar.sceneform.SceneView.doUpdate(SourceFile:99)
        at com.google.ar.sceneform.SceneView.doFrame(SourceFile:86)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:947)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:693)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6992)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)

**Comment by IvanFiveHundredFourteen** [comment]
@Tushar-kant-Deo can you give me code how to convert image to bitmap, the
`imageToBitmap(img)` method?

**Comment by janbolat** [comment]
Any luck guys?
I also opened a ticket, but haven't heard anything:
https://github.com/google-ar/sceneform-android-sdk/issues/996

**Comment by devbridie** [comment]
`DeadlineExceededException` is thrown when you ask an old `Frame` for data when a new frame has arrived via `session.update()`. 

It's hard to tell without code, but it seems like the frame has passed by, by the time the lambda is executed.
