### ISSUE TITLE
Fatal Exception: java.util.concurrent.TimeoutException

### ISSUE THREAD

**Issue by shin-dongkyu** [google-ar/arcore-android-sdk#979]
Fatal Exception: java.util.concurrent.TimeoutException: 
com.google.ar.core.Session.finalize() timed out after 60 seconds
       at com.google.ar.core.Session.nativeDestroySessionWrapper(Session.java)
       at com.google.ar.core.Session.finalize(Session.java:37)
       at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
       at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
       at java.lang.Daemons$Daemon.run(Daemons.java:103)
       at java.lang.Thread.run(Thread.java:764)

device : only galaxy note 10+
version : android 9, 10

augmented image detect -> 3d object add ->  video play -> freezing app -> this issue

**Comment by henrikyn** [comment]
I'm facing this same issue with the same device Galaxy Note10+ only.
